KSP-CKAN/CKAN-meta

PartWizard/PartWizard-1.1.2.ckan

Hand-packaged as mod is curse-only at the moment

---

SpaceFactory-Unofficial/SpaceFactory-Voskhod-v1-unofficial.ckan
SpaceFactory-Unofficial/SpaceFactory-Vostok-v1-unofficial.ckan

SpaceFactory

---

ExtraPlanetaryLaunchpads/Extraplanetary-Launchpads-5.0.1.ckan

Only version and download fields amended

ExtraPlanetaryLauchpads Update

---

AstronomersPack-Clouds-High/AstronomersPack-Clouds-High-Interstellar-V2.ckan
AstronomersPack-Clouds-Low/AstronomersPack-Clouds-Low-Interstellar-V2.ckan
AstronomersPack-Clouds-Medium/AstronomersPack-Clouds-Medium-Interstellar-V2.ckan
AstronomersPack-DistantObjectEnhancement/AstronomersPack-DistantObjectEnhancement-Interstellar-V2.ckan
AstronomersPack-PlanetShine/AstronomersPack-PlanetShine-Interstellar-V2.ckan

This reverts commit f7371848d4a39e399a00de4b7f417cb573260a14.
Fixes #279.

Revert "Removed the core packages, they are in another branch"

---

KSPInterstellar/KSPInterstellar-0.13.6.ckan

Requested with ticket https://github.com/KSP-CKAN/NetKAN/issues/535

Hand-packaged ckan for 0.90 maintenance version of Interstellar

---

ForScienceContinued/ForScienceContinued-0.25.2.ckan
ForScienceContinued/ForScienceContinued-0.25.ckan
ForScienceContinued/ForScienceContinued-v_0.25.1.ckan

ckan was showing v_0.25.1 as newest version. hope these changes will show 0.25.2 as newest

updated files for ForScienceContinued

---

BackgroundProcessing/BackgroundProcessing-0.4.0.1.ckan

Netkan fails this time
See KSP-CKAN/NetKAN#658
Tested so It would be nice to have a merged soon :rocket:

Added new Background Processing 0.4.0.1 manually

---

BDAnimationModules/BDAnimationModules-v0.5.2.ckan

BDAnimationModules works for 0.90

---

KPseudonym/KPseudonym2.ckan

Hand crafted ckan because Curse
This will be usefull in KSP-CKAN/NetKAN#579

Added KPseudonym

---

CustomShaderLoader/CustomShaderLoader-1.ckan

related to KSP-CKAN/NetKAN#629 (not sure if closes would work here)
We can't create netkan until KSP-CKAN/CKAN-netkan#41 (like in ModuleManager etc)
Version in dll file name, everything in root directory of zip file and this:
:trollface:

Added Custom Shader Loader

---

RCSBuildAid/RCSBuildAid-v0.6.1.ckan

forked v0.6 and updated version number and download link

manual update for v0.6.1

---

RasterPropMonitor/RasterPropMonitor-v0.19.ckan

Unofficial Raster Prop Monitor update for 0.90

---

KISFunPack/KISFunPack-1.0.0.ckan

Added KIS fun pack

---

DiverseKerbalHeads/DiverseKerbalHeads-1.0.ckan

Works great on my system with `ckan install -c`.
Alas, had to do the hand-rolled file as it looks like it's only on Curse.

Added hand-rolled DiverseKerbalHeads

---

KSPInterstellar/KSPInterstellar-0.13.6.ckan

Based on https://github.com/KSP-CKAN/NetKAN/issues/862 and https://github.com/KSP-CKAN/CKAN-meta/issues/318

KSPI - Treeloader->Techmanager

---

RSSTextures2048/RealSolarSystemTextures_2048-1.0.ckan
RSSTextures4096/RealSolarSystemTextures_4096-1.0.ckan
RSSTextures8192/RealSolarSystemTextures_8192-1.0.ckan
RSSTexturesDDS2048/RSSTexturesDDS2048-1.0.ckan
RSSTexturesDDS4096/RSSTexturesDDS4096-1.0.ckan
RSSTexturesDDS8192/RSSTexturesDDS8192-1.0.ckan

nabaal.net is having cert problems. Thanks @sarbian !

Update RSS textures to Sarbian's site`

---

SolarScience/SolarScience-v1.03.ckan

Update SolarScience-v1.03.ckan to have homepage link.

---

KIS/KIS-1.0.2.ckan

Here you go.
no clue if it's possible, else it might be wise to use "http://kerbal.curseforge.com/ksp-mods/228561-kerbal-inventory-system-kis/files/latest" for the auto-update checker.

Update KIS to 1.0.2 - CKAN file supplied.

---

PartIconFixer/PartIconFixer-1.2.ckan

It's recommended mod for Kerbal Foundries (they need update but first I have to wait for this mod to be merged)

added PartIconFixer

---

InfernalRobotics/InfernalRobotics-0.19.4.ckan
InfernalRobotics/InfernalRobotics-0.20c.ckan

Needed to resolve https://github.com/KSP-CKAN/CKAN-meta/issues/370

Manual update of IR until a stable release is caught by NetKAN

---

Kopernicus-Config-Default/Kopernicus-Config-Default-pre-alpha-06.ckan
Kopernicus/Kopernicus-pre-alpha-06.ckan

There are no real releases of this yet and since the bot doesn't index pre-releases I'm doing this one manually.

Update Kopernicus to newest version

---

Goodspeed/Goodspeed.netkan

Add Goodspeed.ckan

---

build.sh

Jenkins: Display all installed mods and files at end of testing.

---

AtomicAge/AtomicAge-0.1.ckan

As requested [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-10-20-Apr-2015?p=1846907&viewfull=1#post1846907)
...and perhaps mostly because I want to try out the modifications to Jenkins.

Add AtomicAge to CKAN

---

InFlightWaypoints/InFlightWaypoints-2.0.3.ckan
InFlightWaypoints/InFlightWaypoints-2.1.0.ckan
MapResourceOverlay/MapResourceOverlay-0.2.8.ckan
MapResourceOverlay/MapResourceOverlay-0.2.9.ckan
ProceduralParts/ProceduralParts-v0.9.21.ckan
ProceduralParts/ProceduralParts-v1.0.0.ckan
ProceduralParts/ProceduralParts-v1.0.1.ckan
WernherChecker/WernherChecker-v0.3.4.ckan

information fetched from .version files when available. Otherways by looking through github release notes.

Fix broken vref stanza

---

HyperEdit/HyperEdit-1.4.ckan

Someone on irc pointed out that the download link for 1.3 was broken, this should fix that. Also adding version 1.4 which works in 1.0.

update Hyperedit 1.3 and add 1.4

---

MechJeb2/MechJeb2-2.5.0.ckan

Add MJ2 for 1.0

---

TALSphericalToroidalPack/TALSphericalToroidalPack-3.12.ckan

This is a quick and dirty solution in wait for a potential takeover of the mod by taniwha as can be seen here http://forum.kerbalspaceprogram.com/threads/30673-0-23-5-Spherical-and-Toroidal-Tank-Pack-%28Updated-05-02-14%29-%28New-download-link%29?p=1873503&viewfull=1#post1873503

Fix TALs fueltank pack

---

ResetSAS/ResetSAS-0.01.ckan

This functionallity is now standard in 1.0 so this mod will be bumped down to only 0.90.

ResetSAS is a no-go for 1.0

---

MissionController2/MissionController2-1.12.1.ckan
build.sh

MissionController2 was indexed with a really silly version.

---

ToadicusTools/ToadicusTools-8a.ckan

closes #410 
I like TweakableEverything, this mod not updating prevents me from using TE ergo I'm doing it manually since our bot is on a break.
.ckan file generated through netkan from the indexed .netkan file in our repo.

netkan-bot is lazy, update ToadicusTools

---

Kopernicus-Config-Default/Kopernicus-Config-Default-pre-alpha-04.ckan
Kopernicus-Config-Default/Kopernicus-Config-Default-pre-alpha-06.ckan
Kopernicus/Kopernicus-pre-alpha-04.ckan
Kopernicus/Kopernicus-pre-alpha-06.ckan

[Source](http://forum.kerbalspaceprogram.com/threads/114649-0-90-Kopernicus-Pre-Alpha-%280-0-6%29?p=1869292&viewfull=1#post1869292)
There are dev-versions out that fix the issue but nothing official yet.

Kopernicus doesn't work in 1.0

---

LSPFlags/LSPFlags-1.6.ckan

I was to quick in merging https://github.com/KSP-CKAN/CKAN-meta/pull/399
This fixes it.

Fix Daz screwup with LSPFlags

---

ModuleManager/ModuleManager-2.6.1.ckan

closes https://github.com/KSP-CKAN/CKAN-meta/issues/408

Fix dl for ModuleManager 2.6.1

---

ReflectionPlugin/ReflectionPlugin-1.2.ckan

Better version of https://github.com/KSP-CKAN/NetKAN/pull/1053 which will instead be breaking the plugin out of FASA and adding this as a new dependency, also needed for https://github.com/KSP-CKAN/NetKAN/pull/939

Add ReflectionPlugin to CKAN

---

HotRockets/HotRockets-7.9.ckan

Updated KSP Version 1.0 and dependencies versions.

Update HotRockets-7.9.ckan for KSP1.0

---

ActiveTextureManagement-x64-Aggressive/ActiveTextureManagement-x64-Aggressive-4-3.ckan
ActiveTextureManagement-x64-Basic/ActiveTextureManagement-x64-Basic-4-3.ckan
ActiveTextureManagement-x86-Aggressive/ActiveTextureManagement-x86-Aggressive-4-3.ckan
ActiveTextureManagement-x86-Basic/ActiveTextureManagement-x86-Basic-4-3.ckan
FirespitterCore/FirespitterCore-7.0.5398.27328.ckan
FirespitterCore/FirespitterCore-7.0.5463.30802.ckan

Not sure how the ATM .netkan files will react but I'll whack them aswell I guess.

Mark FirespitterCore and ATM at incompat with 1.0

---

KopernicusTech/KopernicusTech-0.13.ckan

KopernicusTech works in 1.0 based on http://forum.kerbalspaceprogram.com/threads/114649-0-90-Kopernicus-Pre-Alpha-%280-0-6%29?p=1868813&viewfull=1#post1868813

update KopernicusTech to 1.0 compat

---

KlockheedMartian-Gimbal/KlockheedMartian-Gimbal-3.0.3.0.ckan
ModularFlightIntegrator/ModularFlightIntegrator-1.0.ckan
ModuleManager/ModuleManager-2.6.2.ckan
SmokeScreen/SmokeScreen-2.6.0.ckan

Fixes KlockheedMartian-Gimbal, ModularFlightIntegrator, ModuleManager, SmokeScreen

Fix "ksp_version" field

---

USI-LS/USI-LS-0.1.0.ckan

File was generated manually so now I'm editing it manually aswell.

USI-LS version change to work with 1.0.2

---

KIS/KIS-1.1.1.ckan

Sanitised path for forum thread and updated config for KIS v1.1.1

Added config for KIS v1.1.1

---

build.sh

Mirroring the upgrades in https://github.com/KSP-CKAN/NetKAN/pull/1129

Upgrade Jenkins to 1.0.2

---

RCSSounds/RCSSounds-4.3.ckan

Only available on Curse or Mediafire.

Add RCSSounds

---

FirespitterCore/FirespitterCore-7.1.ckan

Add firespitter

---

xScience/xScience-4.2.ckan
xScience/xScience-4.3.ckan

[x] Science! V4.3 for KSP V1.0.2

[x] Science! V4.3 for KSP V1.0.2

---

InfernalRobotics/InfernalRobotics-v0.21.2.ckan

Re-index IR 0.21.2 as v0.21.2

---

BoxSat-prototypes/BoxSat-prototypes-A.02e.ckan

Add back BoxSat dependency to BoxSat-prototypes

---

ExtraPlanetaryLaunchpads/Extraplanetary-Launchpads-5.1.90.ckan

Adding Meta support for EPLP for KSP 1.0.2 to CKAN

Adding EPLP for 1.0.2 

---

FerramAerospaceResearch/FerramAerospaceResearch-v0.15.0_Euler

The previous release of FAR had a funny version number. This PR fixes
that.
Brings joy to @Felger

Fix version number on FAR

---

FLEET/EPL-ISRU-1.0.ckan
FLEET/EPL-MKS-1.0.ckan
FLEET/EPL-fastbuild-1.0.ckan

Three simple ModuleManager configs. I've had enough "how do I install these" queries that it's simpler if I can just tell them to use CKAN.

Add MM patches for improved EPL experience with stock ISRU & MKS.

---

ReflectionPlugin/ReflectionPlugin-1.2.ckan

I think I'm reading the schema correctly, here. I don't know what previous versions of the schema contained, so I'm bumping this file to 1.4

Add Homepage to reflectionPlugin

---

RCSBuildAid/RCSBuildAid-v0.7.ckan

I'm not familiar with the spec, I just copied and edited the relevant stuff.

RCSBuildAid version 0.7

---

StationScience/StationScience-1.5.ckan

Install stanza removed, let's hope it works :)

Add StationScience 1.5

---

ModularFuelTanks/ModularFuelTanks-5.5.2.ckan

Update Modular Fuel Tanks to 5.5.2

---

MechJeb2/MechJeb2-2.5.1.ckan
MechJebForAll/MechJebForAll-1.2.0.0.ckan

closes #503 
Unable to reopen #514 and #516 so here's the same thing again.

Readd plague006

---

NoOffsetLimits/NoOffsetLimits-2015-05-12.ckan
SelectRoot/SelectRoot-2015-05-17.ckan
WasdEditorCamera/WasdEditorCamera-2015-05-20.ckan

closes #523 
a minor filtering change to SelectRoot and adding NoOffsetLimits and WasdEditorCamera

update and add some mods

---

CryoEngines/CryoEngines-0.1.5.repackaged0.ckan
InterstellarFuelSwitch/InterstellarFuelSwitch-1.2.repackaged0.ckan
NearFutureConstruction/NearFutureConstruction-0.5.2.repackaged0.ckan

To make sure the upgrade paths work.

Manual version bumps for InterstellarFuelSwitch.

---

BananaForScale-large/BananaForScale-large-1.0.ckan
BananaForScale-small/BananaForScale-small-1.0.ckan
PhoenixIndustriesCargoResupplySystem-large/PhoenixIndustriesCargoResupplySystem-large-1.2.ckan
PhoenixIndustriesCargoResupplySystem-small/PhoenixIndustriesCargoResupplySystem-small-1.2.ckan

PhoenixIndustriesCargoResupplySystem

---

HGR-Props/HGR-Props-1.2.1.ckan
HGR/HGR-1.2.1.ckan

Fixes the forum links pointing to a different thread.

Fix HGR forum links

---

RasterPropMonitor/RasterPropMonitor-v0.19.3.ckan

RPM is KSP 1.0.x compatible, not just 1.0.2

Update RPM release to KSP 1.0

---

SoundingRockets/SoundingRockets-0.1.1.ckan

Part of the solution for https://github.com/KSP-CKAN/CKAN-meta/issues/537, thank to @ShaggyGoblin for noticing the broken links on 0.90.

Change broken DropBox link to GitHub.

---

TacFuelBalancer/TacFuelBalancer-v2.4.1.1008.ckan

For https://github.com/KSP-CKAN/CKAN-meta/issues/537
I think this represents the last fix for #537 ?

Add TacFuelBalancer for 0.90

---

build.sh

Testing: Pretty-print metadata when verifying.

---

Protractor/Protractor-v2.5.1.ckan

Workaround for https://github.com/KSP-CKAN/NetKAN/issues/1445

Add Protractor 2.5.1

---

MiniAVC/MiniAVC-1.0.3.0.ckan

Related to KSP-CKAN/NetKAN#1455

added MiniAVC

---

InterstellarFuelSwitch-Core/InterstellarFuelSwitch-Core-1.6.ckan
InterstellarFuelSwitch/InterstellarFuelSwitch-1.6.ckan
OpenTree/OpenTree-2.1.ckan

OpenTree requested for update in the CKAN forum thread [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-18-29-May-2015?p=1987626&viewfull=1#post1987626) and IFS was somewhere... irc maybe?
All files generated from their respective .netkan files in NetKAN

IFS, IFS-Core and OpenTree

---

RCSBuildAid/RCSBuildAid-v0.7.1.ckan

new version, review everything is alright since I updated the file to spec v1.4

RCSBuildAid 0.7.1

---

Mk2Essentials/Mk2Essentials-5.ckan

In proper directory and filename convention

Adding Mk2Essentials

---

ContractConfigurator/ContractConfigurator-1.4.2.ckan
WaypointManager/WaypointManager-2.3.2.ckan
WiderContractsApp/WiderContractsApp-1.1.2.ckan

Not re-releasing said mods at present, so updating CKAN-meta directly.

Confirmed mods working in 1.0.3

---

ContractConfigurator/ContractConfigurator-1.4.2.ckan

As such the netkan bot will not pick it up.

Author changed versions without making a new release. 

---

WaypointManager/WaypointManager-2.3.3.ckan
WiderContractsApp/WiderContractsApp-1.1.2.ckan

I made these changes manually in the .version files but didn't officially re-release the mods.  Since netkan doesn't pick up on my hack, doing a PR.
@RichardLake was kind enough to fix ContractConfigurator already.

WaypointManager and WiderContractsApp to 1.0.4

---

WaypointManager/WaypointManager-2.3.3.ckan
WiderContractsApp/WiderContractsApp-1.1.2.ckan

I assume CKAN would be unhappy if these are wrong...

Fix download size on WaypointManager and WiderContractsApp

---

SETI-Contracts/SETI-Contracts-0.9.1.ckan

[Acknowledged by the author by the download link](http://forum.kerbalspaceprogram.com/threads/106130?p=1649006&viewfull=1#post1649006)

Marks the SETI contract pack as 1.0.4 compatible

---

SETI-CommunityTechTree/SETI-CommunityTechTree-0.8.4.ckan

http://forum.kerbalspaceprogram.com/threads/106130?p=2046067&viewfull=1#post2046067

Marking SETI-CTT as 1.0.4 compatible.

---

Mk2Essentials/Mk2Essentials-5.ckan

metadata KSP version bump. Works, unchanged.

KSP Version Bump 1.0.4

---

ColorCodedCans/ColorCodedCans-0.3.ckan
ColorCodedCans/ColorCodedCans-0.4.ckan
ColorCodedCans/ColorCodedCans-0.5.ckan
ColorCodedCans/ColorCodedCans-0.6.ckan
ColorCodedCans/ColorCodedCans-0.7.ckan
ColorCodedCans/ColorCodedCans-0.8.ckan
ColorCodedCans/ColorCodedCans-0.9.ckan
CustomAsteroids/CustomAsteroids-v1.1.0.ckan
DockingPortAlignmentIndicator/DockingPortAlignmentIndicator-4.0.ckan
ImprovedChaseCamera/ImprovedChaseCamera-1.4.0.ckan
JSIPartUtilities/JSIPartUtilities-v0.2.ckan
KerbalFoundries/KerbalFoundries-Alpha_1.7c.ckan
KerbalFoundries/KerbalFoundries-Beta_1.8g.ckan
LargeStructuralComponents/LargeStructuralComponents-10.ckan
Proton-Bobcat/Proton-Bobcat-1.0.ckan
PunishTheLazy/PunishTheLazy-0.01.ckan
RocketdyneF-1/RocketdyneF-1-1.2.ckan
SovietEngines/SovietEngines-1.0.ckan
SovietEngines/SovietEngines-1.1.ckan
SpaceFactory-Unofficial/SpaceFactory-Voskhod-v1-unofficial.ckan
SpaceFactory-Unofficial/SpaceFactory-Vostok-v1-unofficial.ckan
StripSymmetry/StripSymmetry-v1.5.ckan
StripSymmetry/StripSymmetry-v1.6.ckan

This is an updated version of #628, with adjustments based upon my review of that PR. KSP-CKAN/NetKAN#1705 includes the other half of the situation, but they can be merged in any order.
(I may also self-merge, since this is an adjust of an exisitng PR; but I want to see what jenskins says first.)

Updated min/max versions in MANY files.

---

ExtraPlanetaryLaunchpads/Extraplanetary-Launchpads-5.2.0.ckan

Adding the new release and updating KSP compatibility to use the new _min and _max functionality

Extraplanetary Launchpads 5.2.0

---

UniversalStorage-KAS/UniversalStorage-KAS-0.9.0.ckan

Fix homepage in UniversalStorage-KAS

---

xScience/xScience-4.7.ckan

[x] Science! V4.7 Go Live
Thank you!

[x] Science! V4.7 Go Live

---

Fusebox/Fusebox-1.50.ckan

Add Fusebox-1.50

---

FLEET/EPL-ISRU-1.0.ckan
FLEET/EPL-MKS-1.0.ckan
FLEET/EPL-fastbuild-1.0.ckan
KISFunPack/KISFunPack-1.0.0.ckan
OpenResourceSystem/OpenResourceSystem-1.4.2.ckan
RSSTexturesDDS2048/RSSTexturesDDS2048-1.0.ckan
RSSTexturesDDS4096/RSSTexturesDDS4096-1.0.ckan
RSSTexturesDDS8192/RSSTexturesDDS8192-1.0.ckan
TreeLoader/TreeLoader-1.1.5.ckan

When/if KSP-CKAN/CKAN#1254 becomes a thing, these 9 mods will be the last of their kind.
No longer will a mod be homeless and afraid! We bring homes to those in need!

Add homepages

---

repositories.json

This is one of my old copies. Might be not fully up-to-date, but a starting point nevertheless

Copy old archive of repositories.json

---

ContractConfigurator-SCANsat/ContractConfigurator-SCANsat-1.0.2.ckan
ContractConfigurator-SCANsat/ContractConfigurator-SCANsat-Deprecated.ckan

Keeping consistency with identifier

Update ContractConfigurator-SCANsat-1.0.2.ckan and ContractConfigurator-SCANsat-Deprecated.ckan

---

FuelTanksPlus/FuelTanksPlus-1.0.2.ckan
OuterPlanetsMod/OuterPlanetsMod-1-1.7.2.ckan

A few releases added while @netkan-bot is napping.

Adding FTP 1.0.2 and OPM 1.7.2

---

CanadianFlags/CanadianFlags-1.0.ckan

I found my flag pack, where's your flag at Australia? :sunglasses:
@pjf @RichardLake @techman83 
(I did actually [find a pack](http://www.curse.com/shareables/kerbal/224200) but it seems like the download is broken)

Add CanadianFlags-1.0.ckan

---

GCMonitor/GCMonitor-1.2.7

Copied from and closes #691
Thanks to @BasharMilesTeg

Add GCMonitor-1.2.7

---

SETI-CommunityTechTree/SETI-CommunityTechTree-0.9.1.3.ckan

Netkan-bot fails because of AVC version

Manual version add for SETI-CommunityTechTree

---

KIS/KIS-1.2.1.ckan

Updated to work with KAS 0.5.4 - KAS no longer depends on this.

KIS 1.2.1 update

---

xScience/xScience-4.8.ckan

Bug fixes, changed science filters.

Publish new version V4.8 for KSP V1.0.4

---

build.sh

This looks to be doing the correct things. Won't try and validate itself. Exits with failures seemingly when it should.
Thanks to @mgsdk for the dummy install function.

Overhaul build script - KSP-CKAN/CKAN#1273

---

AIESAerospace-Unofficial/AIESAerospace-Unofficial-v1.5.1.ckan
AMEG/AMEG-1.1.ckan
AnimatedDecouplers-x86/AnimatedDecouplers-x86-1.0.2.ckan
AnimatedDecouplers-x86/AnimatedDecouplers-x86-1.1.0.ckan
AnimatedDecouplers-x86/AnimatedDecouplers-x86-1.1.1.ckan
AnimatedDecouplers-x86/AnimatedDecouplers-x86-1.1.2.ckan
AnimatedDecouplers-x86/AnimatedDecouplers-x86-1.1.3.ckan
AnimatedDecouplers-x86/AnimatedDecouplers-x86-1.1.4.ckan
BananaForScale-large/BananaForScale-large-1.0.ckan
BananaForScale-small/BananaForScale-small-1.0.ckan
Tantares/Tantares-29.ckan
TantaresLV/TantaresLV-10.0.ckan
TantaresLV/TantaresLV-11.1.ckan
TantaresLV/TantaresLV-11.ckan
TantaresLV/TantaresLV-12.1.ckan
TantaresLV/TantaresLV-6.0.ckan
TantaresLV/TantaresLV-6.2.ckan
TantaresLV/TantaresLV-9.0.ckan
xScience/xScience-4.2.ckan
xScience/xScience-4.3.ckan
xScience/xScience-4.4.ckan
xScience/xScience-4.5.ckan
xScience/xScience-4.6.ckan

Small steps towards https://github.com/KSP-CKAN/CKAN-meta/issues/623
Companion PR to: https://github.com/KSP-CKAN/NetKAN/pull/2053

Promiscuous versions fixes

---

build.sh

Fix testing fail when 0.23 is supplied

---

BDAnimationModules/BDAnimationModules-v0.5.2.ckan
KopernicusTech/KopernicusTech-0.13.ckan
OblivionAerospace/OblivionAerospace-v0.1.4.ckan
OblivionAerospace/OblivionAerospace-v0.1.5.ckan
Protractor/Protractor-2.5.1.ckan
Protractor/Protractor-v2.5.1.ckan
PunishTheLazy/PunishTheLazy-0.01.ckan
RocketdyneF-1/RocketdyneF-1-1.2.ckan
SovietEngines/SovietEngines-1.1.ckan
USI-LS/USI-LS-0.1.0.ckan

Companion PR to https://github.com/KSP-CKAN/NetKAN/pull/2152
Some mods have their version_max changed, some mods have the range removed and replaced with "1.0" instead.

Assign a ksp_version range

---

build.sh

Similar to KSP-CKAN/NetKAN#2164

Display version info about ckan to make for easier failure diagnosis

---

RCSSounds/RCSSounds-4.3a.ckan

As requested in KSP-CKAN/NetKAN/pull/2173

New update

---

ModuleManager/ModuleManager-2.6.8.ckan

New ModuleManager  with a big bug fix

ModuleManager 2.6.8

---

xScience/xScience-4.10.ckan

Publishing V4.10 for KSP1.0.4

---

BoxSat-prototypes/BoxSat-prototypes-A.02f.ckan
BoxSat/BoxSat-A.02f.ckan

Add boxsat A.02f

---

AlcubierreStandalone/AlcubierreStandalone-0.3.0.0.ckan
CommunityResourcePack/CommunityResourcePack-0.4.5.0.ckan
Karbonite/Karbonite-1-0.6.5.0.ckan
KarbonitePlus/KarbonitePlus-0.5.1.0.ckan
UKS/UKS-1-0.31.11.2.ckan
USI-Core/USI-Core-0.0.1.0.ckan
USI-EXP/USI-EXP-0.4.2.0.ckan
USI-FTT/USI-FTT-0.4.1.ckan
USI-LS/USI-LS-0.1.5.ckan
USI-MKSLite/USI-MKSLite-0.0.6.0.ckan
USI-NuclearRockets/USI-NuclearRockets-0.1.0.1.ckan
USI-SRV/USI-SRV-0.3.2.0.ckan

After merging KSP-CKAN/NetKAN#2476, I'd like to make @BobPalmer's
life easier by re-indexing all the changed mods immediately, saving
us a couple of hours while we wait for the bot.
These are all generated by `netkan.exe` as per normal.

Let's early index RoverDude's mods!

---

PreciseNode/PreciseNode-1.2.0.ckan
Toolbar/Toolbar-1.7.10.ckan

Add the following mods from blizzy78
* PreciseNode (v1.2.0)
* Toolbar (v1.7.10)
closes KSP-CKAN/NetKAN/pull/2551

Add blizzy78's mods

---

EnvironmentalVisualEnhancements-HR/EnvironmentalVisualEnhancements-HR-7-4.ckan
EnvironmentalVisualEnhancements-HR/EnvironmentalVisualEnhancements-HR-EVE-1.05-1.ckan
EnvironmentalVisualEnhancements-LR/EnvironmentalVisualEnhancements-LR-7-4.ckan
EnvironmentalVisualEnhancements/EnvironmentalVisualEnhancements-7-4.ckan

Part of KSP-CKAN/NetKAN/issues/2550

EVE revision - update ksp_version

---

KAS/KAS-0.5.5.ckan
KIS/KIS-1.2.3.ckan

Add the following mods:
* `KIS-1.2.3`
* `KAS-0.5.5`

Add new KIS and KAS

---

Workshop/Workshop-0.11.0.ckan

This version never came through, so adding it manually

Add Workshop-0.11.0

---

AdvancedJetEngine/AdvancedJetEngine-2.5.ckan

Should have been marked 1.0.5, is marked 1.0.4.

Force-update old AJE 2.5

---

xScience/xScience-4.12.ckan

Publishing [x] Science! V4.12 for KSP V1.0.5 

---

PlanetShine-Config-Default/PlanetShine-Config-Default-0.2.4.ckan
PlanetShine/PlanetShine-0.2.4.ckan

Add `0.2.4` as KSP-CKAN/NetKAN/pull/2715 will add `0.2.4.1`

Add PlanetShine 0.2.4

---

AlternisKerbolRekerjiggered-flags/AlternisKerbolRekerjiggered-flags-1.4.1.ckan
AlternisKerbolRekerjiggered-flags/AlternisKerbolRekerjiggered-flags-1.4.ckan

These flag-only mods should be version-promiscuous. The old versions need to updated.

Update old AlternisKerbolRekerjiggered-flags .ckans 

---

HangarExtender/HangarExtender-2.0.ckan
HangarExtender/HangarExtender-3.0.ckan

Reverts KSP-CKAN/CKAN-meta#855
This didn't fix the issue. Will create a PR shortly that does.

Revert "Add 'v' to fix displaying wrong version"

---

KerBalloons/KerBalloons-v0.3.ckan

Add KerBalloons-v0.3

---

ClampsBeGone/ClampsBeGone-1.0.0.ckan
ClampsBeGone/ClampsBeGone-1.1.0.ckan
ClampsBeGone/ClampsBeGone-1.1.1.ckan
ClampsBeGone/ClampsBeGone-1.1.2.ckan

Obsolete mod, this bug was fixed in 1.0.5

Update old ClampsBeGone versions

---

StockPlus/StockPlus-v1.0.2d.4.ckan
StockPlus/StockPlus-v1.0.2d.5.ckan
StockPlus/StockPlus-v1.0.2e.1.ckan
StockPlus/StockPlus-v1.0.2e.2.ckan
StockPlus/StockPlus-v1.0.2e.3.ckan
StockPlus/StockPlus-v1.0.4a.1.ckan
StockPlus/StockPlus-v1.0.4b.1.ckan
StockPlus/StockPlus-v1.0.4b.2.ckan
StockPlus/StockPlus-v1.0.4c.1.ckan

Restrict KSP versions from promiscuous settings.

Update StockPlus old versions

---

StockBugFixModules/StockBugFixModules-1.0.2d.1.ckan
StockBugFixModules/StockBugFixModules-v1.0.0.ckan
StockBugFixModules/StockBugFixModules-v1.0.2a.ckan
StockBugFixModules/StockBugFixModules-v1.0.2b.ckan
StockBugFixModules/StockBugFixModules-v1.0.2c.1.ckan
StockBugFixModules/StockBugFixModules-v1.0.2c.2.ckan
StockBugFixModules/StockBugFixModules-v1.0.2d.2.ckan
StockBugFixModules/StockBugFixModules-v1.0.2d.3.ckan
StockBugFixModules/StockBugFixModules-v1.0.2d.4.ckan
StockBugFixModules/StockBugFixModules-v1.0.2d.5.ckan
StockBugFixModules/StockBugFixModules-v1.0.2e.1.ckan
StockBugFixModules/StockBugFixModules-v1.0.2e.2.ckan
StockBugFixModules/StockBugFixModules-v1.0.2e.3.ckan
StockBugFixModules/StockBugFixModules-v1.0.4a.1.ckan
StockBugFixModules/StockBugFixModules-v1.0.4b.1.ckan
StockBugFixModules/StockBugFixModules-v1.0.4b.2.ckan
StockBugFixModules/StockBugFixModules-v1.0.4c.1.ckan

Less promiscuous version numbers

Update StockBugFixModules old versions KSP versions

---

ContractConfigurator-KerbinSpaceStation/ContractConfigurator-KerbinSpaceStation-1-3.0.1.ckan
ContractConfigurator-KerbinSpaceStation/ContractConfigurator-KerbinSpaceStation-1-3.0.2.ckan
ContractConfigurator-KerbinSpaceStation/ContractConfigurator-KerbinSpaceStation-1-3.0.3.ckan

Force updates for users. Related to https://github.com/KSP-CKAN/CKAN-meta/pull/879. Merge after  https://github.com/KSP-CKAN/NetKAN/pull/2809.

Add epoch to KerbinSpaceStation

---

ETT/ETT-1.0_20150731.ckan
ETT/ETT-Version_1.0.2_20150904.ckan

Reverts KSP-CKAN/CKAN-meta#864

Revert "Rename and version number fix ETT ckan files"

---

ETT/ETT-1.0.2_20150904.ckan
ETT/ETT-1.0_20150622.ckan

Remake of https://github.com/KSP-CKAN/CKAN-meta/pull/864 that maintains the author's versioning style while giving us proper version ordering/sorting.

Change versions to be uniform/sort properly.

---

ETT/ETT-1.0.0_20150622.ckan
ETT/ETT-1.0.0_20150731.ckan

Fix KSP version and version number to be consistent with version sequence.

Update and rename ETT-1.0 ckans to ETT-1.0.0

---

WindowShineTR/WindowShineTR-v11.ckan

Finally found a comment from Avera9eJoe saying he'd be happy for this to be added to CKAN as long as someone is willing to maintain it here.

Add WindowShineTR to CKAN-Meta

---

MK2KSPIIntegration/MK2KSPIIntegration-8.6.0_Perfectly_Ultimate_Great_Main_Sequence_Panthera_leo.ckan
MK2KSPIIntegration/MK2KSPIIntegration-8.7.0_Perfectly_Ultimate_Great_SuperGiant_Felis.ckan
MK2KSPIIntegration/MK2KSPIIntegration-8.7.1_Perfectly_Ultimate_Great_SuperGiant_Lynx.ckan
SETI-BalanceMod/SETI-BalanceMod-0.9.5.ckan

Merge after KSP-CKAN/NetKAN/pull/2827
Update all "older" versions compatible with 1.0.5 that the bot won't update. Jenkins will fail because this mod isn't added yet.

Use new mod

---

RetroFuture/RetroFuture-1.7.0.ckan
RetroFuture/RetroFuture-1.7.2b.ckan

Merge after KSP-CKAN/NetKAN/pull/2813

Retro future

---

TACLS-Config-Stock/TACLS-Config-Stock-v0.11.2.ckan

Same as #899 but then the stock config file

Add TACLS-Config-Stock-v0.11.2

---

ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-v1.ckan

http://forum.kerbalspaceprogram.com/index.php?/topic/62533-10x-procedural-parts-textures-procedural-kw-june-8/&do=findComment&comment=1988186

Updated ProceduralParts-Textures to new version

---

RCSBuildAid/RCSBuildAid-v0.7.7.ckan

RCSBuildAid v0.7.7

---

KerBalloons/KerBalloons-v0.3.1.ckan

Add KerBalloons 0.3.1

---

AsteroidDay/AsteroidDay-1.0.5.ckan

Noticed we're installing the source incidentally while looking into another issue.

Filter source

---

ASETAvionics/ASETAvionics-1.0.ckan

Moved to a seperate PR so that ASET Props can be checked seperately
First merge #959 and test this PR again.

Update ASET Avionics

---

ImprovedChaseCamera/ImprovedChaseCamera-v1.5.1.ckan

This Curse link seems to be the last one remaining to the latest version

Fix ImprovedChaseCamera download link and compatibility

---

DockingPortAlignmentIndicator/DockingPortAlignmentIndicator-5.0.ckan
DockingPortAlignmentIndicator/DockingPortAlignmentIndicator-5.1.ckan
DockingPortAlignmentIndicator/DockingPortAlignmentIndicator-6.1.ckan
DockingPortAlignmentIndicator/DockingPortAlignmentIndicator-6.2.ckan

Changed kerbalstuff to curse download links.

Fix DockingPortAlignmentIndicator download links

---

KIS/KIS-1.2.4.ckan

Looked like this was all it would take to get KIS up to date, is that so?

Add KIS 1.2.4

---

KSCPlusPlus/KSCPlusPlus-v3.ckan

Ref #947
Only a Dropbox download, unfortunately.

Add Ksc plus plus

---

KIS/KIS-1.2.5.ckan

Apparently they release quite often :smile:

Add KIS 1.2.5

---

UCAeronautictechnology/AUCAeronautictechnology-0.0.1.ckan
UCAeronautictechnology/AUCAeronautictechnology-0.1.ckan

Picked a version number at random. I don't know why my CKAN-meta keeps showing all these catch-up commits when my NetKAN repo doesn't do the same.

Add AUC Aeronautic technology from Curse

---

CommunityAmmunitionLibrary/CommunityAmmunitionLibrary-0.0.8.ckan

Required for KSP-CKAN/NetKAN/pull/3275
Required for KSP-CKAN/NetKAN/pull/3276

Update CAL to use mirror

---

PhoenixIndustriesFlags/PhoenixIndustriesFlags-1.1.ckan

Allows proper Jenkins tests of https://github.com/KSP-CKAN/NetKAN/pull/3294 and https://github.com/KSP-CKAN/NetKAN/pull/3293

Update download for PhoenixIndustriesFlags

---

WildBlueTools/WildBlueTools-1.0.29.ckan

CRP's folder is included in WBT's .zip. Thanks to @godarklight's tool for finding this. =)

Add dependency for WildBlueTools

---

SpaceLaunchSystemPartPack/SpaceLaunchSystemPartPack-1.0.5.0.9.ckan

This commit should pass, but the next will fail (adding a recommend that Jenkins can't download)

Add depends and recommends to SpaceLaunchSystemPartPack

---

ChineseTianGongScienceSpaceStation/ChineseTianGongScienceSpaceStation-0.1.4.ckan
ChineseTianGongScienceSpaceStation/ChineseTianGongScienceSpaceStation-0.1.5.ckan
ChineseTianGongScienceSpaceStation/ChineseTianGongScienceSpaceStation-0.2.0.ckan
ChineseTianGongScienceSpaceStation/ChineseTianGongScienceSpaceStation-0.2.1.ckan

Remove the Chinese letters from the name and download from the mirror
Needed for KSP-CKAN/NetKAN/pull/3358

KerbalStuff to mirror

---

KerbalKrashSystem/KerbalKrashSystem-1-0.2.1.ckan
KerbalKrashSystem/KerbalKrashSystem-1-0.2.5.ckan
KerbalKrashSystem/KerbalKrashSystem-1-0.2.ckan

Update old versions with homepage, remove all kerbalstuff resources.
Fix versioning with an epoch

Add Kerbal Krash System recent versions

---

FieldExperience/FieldExperience-1.0.1.ckan
FieldExperience/FieldExperience-1.0.2.ckan
FieldExperience/FieldExperience-1.0.ckan

Remove KS resources, update licence.

Move Field Experience to Author hosted DLs

---

EditorTime/EditorTime-1.0.1.ckan
EditorTime/EditorTime-1.0.ckan

Move Editor Time to Author-hosted DLs

---

Deltaglider/Deltaglider-1-v0.4.ckan
Deltaglider/Deltaglider-1-v0.5.ckan
Deltaglider/Deltaglider-Version_Work_In_Progress_V0.3.ckan
Deltaglider/Deltaglider-Work_In_Progress_V0.1.ckan
Deltaglider/Deltaglider-Work_In_Progress_V0.2.ckan
Deltaglider/Deltaglider-Work_In_Progress_V0.3.ckan
Deltaglider/Deltaglider-v0.3.ckan

Only noticed this after @plague006 merged #993

Use correct identifier

---

CriticalTemperatureGauge/CriticalTemperatureGauge-1.0.2-b.ckan
CriticalTemperatureGauge/CriticalTemperatureGauge-1.0.2-c.ckan
CriticalTemperatureGauge/CriticalTemperatureGauge-1.0.2-d.ckan
CriticalTemperatureGauge/CriticalTemperatureGauge-1.0.2-e.ckan
CriticalTemperatureGauge/CriticalTemperatureGauge-1.0.2-f.ckan
CriticalTemperatureGauge/CriticalTemperatureGauge-1.0.4-a.ckan
CriticalTemperatureGauge/CriticalTemperatureGauge-1.0.5-a.ckan

Move CrtiticalTemperatureGauge to mirror

---

KDEX/KDEX-v1.04.ckan

Remove Kerbalstuff resources
Closes KSP-CKAN/NetKAN#3372

Move KDEX to Curse

---

SimpleNuclear/SimpleNuclear-v0.9.ckan

Pushing as soon as Jenkins clears this as we shouldn't have a mod that fails on installation.

Fix conflicting recommends

---

Kethane/Kethane-0.9.4.ckan

Allows proper Jenkins run of https://github.com/KSP-CKAN/CKAN-meta/pull/1000

Kethane download from mod author site

---

LLL-Extras/LLL-Extras-14.ckan
LLL/LLL-14.ckan

Compatible with KSP 1.0.4 and 1.0.5

Update Lack Luster Labs

---

NoOffsetLimits/NoOffsetLimits-2015-05-12.ckan

No Offset Limits still works in 1.0.5

---

kOS/kOS-0.19.0.ckan

@hvacengi updated the zip file in the release but our bot keeps failing because of the previous zipfile had an error, so adding this manually.

Add kOS v0.19.0

---

FMRS/FMRS-v1.0.1.ckan

Netkan file is kerbalstuff frozen

Move current FMRS to Curse

---

SteampunkColorCodedSpaceSuits/SteampunkColorCodedSpaceSuits-2.ckan

Suit textures are compatible between KSP versions

Move Steampunk Color-Coded Space Suits to mirror

---

TestFlightConfigRO/TestFlightConfigRO-1.5.1.0.ckan

Adds explanation for no further versions.

Update TestFlightConfigRO - Deprecated

---

HabitatPlugin/HabitatPlugin-0.41.ckan
PorkjetHabitats/PorkjetHabitats-0.41.ckan

The Plugin has wider use possibilities, was written by someone else, and has different KSP version support.

Separate HabitatPlugin for re-use by EnduranceSpaceExplorationSystem

---

NavUtilities/NavUtilities-0.5.1_RC_1_repacked.ckan

Only source remaining for this mod.

Move NavUtils to Github download

---

KerbalFoundries/KerbalFoundries-1-1.9g.ckan

The Spacedock entry does not appear to be from the team taking over this mod.

Redirect KerbalFoundries 1:1.9g to Dropbox

---

build.sh

This should make @politas a little happier. I thought we'd updated this build script at the same time as netkan's. Apparently not!
Credit to @pjf for his git-fu.

Get commit delta from HEAD

---

AutoAction/AutoAction-1.2.ckan

Does what it says on the tin. :)

AutoAction-1.2: Only runs on KSP 0.90, not *everything*

---

DockingcameraKURSstyle/DockingcameraKURSstyle-1.1.ckan
DockingcameraKURSstyle/DockingcameraKURSstyle-1.2.ckan
DockingcameraKURSstyle/DockingcameraKURSstyle-1.4.ckan

License is CC-BY-SA-3.0
Closes KSP-CKAN/NetKAN#3510

Point DockingCameraKURSstyle CKANs to mirror

---

ProceduralProbes/ProceduralProbes-1.1.ckan
ProceduralProbes/ProceduralProbes-1.ckan

ProceduralProbes to mirror

---

TweakScale/TweakScale-v1.48.ckan
TweakScale/TweakScale-v1.49.ckan
TweakScale/TweakScale-v1.50.ckan

Closes https://github.com/KSP-CKAN/NetKAN/issues/3522

Set ksp_version_max for old tweakscale versions

---

CustomBarnKit/CustomBarnKit-1.1.1.ckan
GCMonitor/GCMonitor-1.2.4.0.ckan
GCMonitor/GCMonitor-1.2.5.ckan
GCMonitor/GCMonitor-1.2.6.ckan
GCMonitor/GCMonitor-1.2.7.ckan
GCMonitor/GCMonitor-1.2.8.0.ckan
GCMonitor/GCMonitor-1.2.9.0.ckan
GCMonitor/GCMonitor-1.3.0.0.ckan
GCMonitor/GCMonitor-1.3.1.0.ckan
GCMonitor/GCMonitor-1.3.2.0.ckan
ModularFlightIntegrator/ModularFlightIntegrator-1.0.ckan
ModularFlightIntegrator/ModularFlightIntegrator-1.0.repackaged0.ckan
ModularFlightIntegrator/ModularFlightIntegrator-1.1.1.ckan

Restricted version ranges of old versions of Sarbian's mods according to .version files.
Removing all these old x_generated_by : nyankan lines makes me feel like I'm killing someone's joke.

Sarbian mods .version info

---

ProceduralProbes/ProceduralProbes-1.ckan

Failed jenkins test in PR #1035

Add missing "x_screenshot":

---

build.sh

Noticed some build failures due to the 1.1 short version.

Update version overrides for 1.1

---

build.sh

Overriding such a weird looking word

---

KerbalKrashSystem/KerbalKrashSystem-1-0.3.ckan

(We are using an epoch thanks to past issues)

Add KerbalKrashSystem-0.3 from Curse

---

KramaxAutoPilot/KramaxAutoPilot-0.2.ckan

Multiple reports on forum thread of compatibility, but author has ceased development.

Add 1.0.5 compatibility for Kramax_Autopilot

---

KAP/KAP-2.2.2.ckan
KashCorpSA/KashCorpSA-2.2.2.ckan

Direct output from netkan. Pushing a manual update to properly test https://github.com/KSP-CKAN/NetKAN/pull/3583

Update from new netkan

---

repositories.json

Great little collection of dev releases, for those that want to live on the bleeding edge. 
All using a modified identifier with a conlflict to the original mod.

Add Fwiffos-Dev-Repo to repositories list

---

xScience/xScience-4.15.ckan

Publishing [x] Science 4.15 for KSP V1.1

---

Kopernicus/Kopernicus-2-release-1-0.ckan

Netkan output, merging after Jenkins' assent

Add Kopernicus-2-release-1-0

---

build.sh

Also decide once and for all how to spell "override"
Ref https://github.com/KSP-CKAN/NetKAN/pull/3629

Update ksp_version defaults and add overrides for 1.1.X versions

---

RasterPropMonitor-Core/RasterPropMonitor-Core-1-v0.25.0.36940.ckan
RasterPropMonitor/RasterPropMonitor-1-v0.25.0.36940.ckan

To expedite https://github.com/KSP-CKAN/CKAN/issues/1672

Direct output of netkan (RPM)

---

Impact/Impact-v1.4.1.ckan

Output from https://github.com/KSP-CKAN/NetKAN/pull/3661

Impact - direct netkan output

---

ForScience/ForScience-v1.3.ckan

New mod, review with care.
Closes https://github.com/KSP-CKAN/CKAN-meta/issues/1074

Add ForScience-v1.3

---

KAS/KAS-0.5.6.ckan
KIS/KIS-1.2.7.ckan

KIS/KAS versions for KSP 1.1

---

MakeItSmall/MakeItSmall-1.1.ckan

With thanks and credit to @labo-css

Add MakeItSmall

---

LaunchCountDown/LaunchCountDown-1.7.6.ckan

Unfortunately now only on Curse.
Ref KSP-CKAN/NetKAN#3670

Add LaunchCountdown 1.7.6 for KSP1.1

---

CommunityTechTree/CommunityTechTree-2.4.0.ckan

Only on Curse.
Ref KSP-CKAN/NetKAN#3670

Add CommunityTechTree 2.4 for KSP 1.1

---

MechJebEmbeddedUniversalCareer/MechJebEmbeddedUniversalCareer-1.3.ckan
MechJebEmbeddedUniversalFree/MechJebEmbeddedUniversalFree-1.3.ckan

With credit and thanks to @janbrohl
Closes https://github.com/KSP-CKAN/CKAN-meta/issues/1096

Add MechJebEmbeddedUniversalFree-1.3 and MechJebEmbeddedUniversalCareer-1.3

---

HullcamVDS/HullcamVDS-0.52.ckan

Closes https://github.com/KSP-CKAN/CKAN-meta/issues/1088

Add HullcamVDS-0.52

---

HyperEdit/HyperEdit-1.5.0.0.ckan

Pinging @techman83 to see if you can have a look into why the bot didn't pick this up.

Add HyperEdit-1.5.0.0.ckan

---

MechJebForAll/MechJebForAll-1.2.0.0.ckan

As this module is only a ModuleManager config file it works with any
version of KSP.

Set ksp_version to any in MechJebForAll-1.2.0.0.ckan

---

CustomAsteroids-Pops-Stock-Inner/CustomAsteroids-Pops-Stock-Inner-v1.2.0.ckan
CustomAsteroids-Pops-Stock-Outer/CustomAsteroids-Pops-Stock-Outer-v1.2.0.ckan

Closes https://github.com/KSP-CKAN/NetKAN/issues/3841

Match ksp_version compatibility to core mod

---

MK12PodIVAReplacementbyASET/MK12PodIVAReplacementbyASET-1.1_BETA.ckan

for Chaka Monkey KSP-CKAN/NetKAN#3777

Push CKAN to get a working dependency

---

ShowFPS/ShowFPS-v1.1.ckan

ShowFPS v1.1 for KSP 1.1
add ksp_version_max entry for ShowFPS v1.0, set to 1.0.5.

ShowFPS update.

---

MK12PodIVAReplacementbyASET/MK12PodIVAReplacementbyASET-1.1_BETA.ckan

One of those things that @godarklight's metadata checker would be useful for, but wouldn't effectively catch, unfortunately.

Fix MK12PodIVA Install

---

KerBalloons/KerBalloons-v0.3.4.ckan

Part of https://github.com/KSP-CKAN/CKAN-meta/issues/1134

Add KerBalloons-v0.3.4.ckan

---

KerbalPlanetaryBaseSystems/KerbalPlanetaryBaseSystems-v1.0.10.ckan

Netkan is failing for some reason, but this installs fine locally for me.

Add KerbalPlanetaryBaseSystems v1.0.10

---

KerbalStats/KerbalStats-2.1.0.ckan

Closes https://github.com/KSP-CKAN/NetKAN/issues/3896

Add KerbalStats-2.1.0.ckan

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
README.md

Changes to reflect https://github.com/KSP-CKAN/NetKAN/issues/3890

Modify contributing and readme docs to follow the new metadata management system. Add issue template.

---

SwitchVessel/SwitchVessel-0.5.ckan
TCShipInfo/ShipInfo-0.4.ckan

Update avivey's mods

---

KerbalKrashSystem/KerbalKrashSystem-1-0.3.3.ckan

Add latest KerbalKrashSystem release

---

ModularFuelTanks/ModularFuelTanks-5.7.4.ckan

Add ModularFuelSystems 5.7.4

---

YongeTechTreesPlugin/YongeTechTreesPlugin-1.4.ckan

Add YongeTechTreesPlugin split out of ETT

---

SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.1.0.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.1.1.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.2.0.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.2.1.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.3.0.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.3.1.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.3.2.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.3.3.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.5.0.ckan
SigmaBinary-DunaIke/SigmaBinary-DunaIke-1-v1.5.1.ckan

Ref KSP-CKAN/NetKAN#4113 
This brings old releases up to the correct versions.

Update SigmaBinary-DunaIke old release KSP versions

---

ContractConfigurator-SCANsat/ContractConfigurator-SCANsat-1.0.1.ckan
ContractConfigurator-SCANsat/ContractConfigurator-SCANsat-1.0.2.ckan
ContractConfigurator-SCANsat/ContractConfigurator-SCANsat-1.0.ckan

Explicitly state *which* public domain license the mod is under.

Refine license precision

---

VNG-Parachute-EVALoading/VNG-Parachute-EVALoading-1.0.ckan

Closes https://github.com/KSP-CKAN/CKAN/issues/1749

Correct license

---

KWRocketry-CommunityFixes-interstage/KWRocketry-CommunityFixes-interstage-0.4.10.ckan
KWRocketry-CommunityFixes/KWRocketry-CommunityFixes-0.4.10.ckan

Per discussion in KSP-CKAN/NetKAN#4141

Restrict KWCommunityFix Releases to KSP 1.0.5

---

KRnD/KRnD-1.3.ckan
KRnD/KRnD-1.8.ckan

Ampersands are not handled well by the client

KRnD fix Name

---

Graphotron/Graphotron-0.4.0.0.ckan
HyperEdit/HyperEdit-1.5.1.0.ckan
HyperEdit/HyperEdit-1.5.2.0.ckan
HyperEdit/HyperEdit-1.5.2.1.ckan

I believe this qualifies, as it corrects meta data for older versions of the HyperEdit mod.
EDIT: And, since the bot has already indexed our latest version, I corrected that as well.
But, I'm new at this, so let me know if I've done something stupid.

Corrected KSP versions for older HyperEdit versions.

---

ReentryParticleEffect/ReentryParticleEffect-1.0.ckan

Advised by mod author on #ckan

ReentryParticleEffect1.0 Install Directory fix.

---

ExtraPlanetaryLaunchpads/ExtraPlanetaryLaunchpads-5.3.2.ckan

Limit ExtraPlanetaryLaunchpads 5.3.2 KSP compatibility

---

USI-Core/USI-Core-0.2.4.0.ckan

Matching up to BobPalmer/CKAN#10

USI-Core fix installation

---

Toolbar/Toolbar-1.7.10.ckan

Fix download URL

---

KerbalAlarmClock/KerbalAlarmClock-v3.6.1.0.ckan
KerbalAlarmClock/KerbalAlarmClock-v3.6.2.1.ckan

Following up on KSP-CKAN/NetKAN#4283

Restrict KSP version on old KAC releases

---

KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.24.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.25.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.26.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.27.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.28.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.29.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.30.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.31.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.32.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.33.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.34.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.35.ckan
KerbalConstructionTime-RP-0-Config/KerbalConstructionTime-RP-0-Config-v0.36.ckan

Restrict KSP Version on obsolete KCT-RP0 Configs 

---

KerBalloons/KerBalloons-v0.3.2.ckan
KerBalloons/KerBalloons-v0.3.4.ckan

Ref KSP-CKAN/NetKAN#4517
KSP-CKAN/NetKAN#4520 must be merged before this PR

Fix old Kerballoons releases KSP versions

---

MemGraph/MemGraph-Release_1.0.0.10.ckan

This will add the 1.1.3 release
ref KSP-CKAN/NetKan#4653, KSP-CKAN/NetKan4648

Add MemGraph-Release_1.0.0.10

---

KRASH/KRASH-0.5.22.ckan

Adding file manually because the bot cached a previous version and keeps failing on the cached zip.

Add KRASH manually

---

Toolbar/Toolbar-1.7.11.ckan
Toolbar/Toolbar-1.7.12.ckan
Toolbar/Toolbar-1.7.7.ckan
Toolbar/Toolbar-1.7.8.ckan
Toolbar/Toolbar-1.7.9.ckan

Move old Toolbar releases to Dropbox downloads

---

ModularFuelTanks/ModularFuelTanks-5.7.6.ckan

Should enable KSP-CKAN/NetKAN#4488 to build

Add ModularFuelTanks v5.7.6 for KSP 1.1.3

---

GroundConstruction-Core/GroundConstruction-Core-1.1.2.1.ckan

Temporary fix for KSP-CKAN/NetKAN#5289

Force add GroundConstruction-Core-1.1.2.1

---

CustomBarnKit/CustomBarnKit-1.1.10.0.ckan

Should enable KSP-CKAN/NetKAN#5358

CustomBarkKit 1.10 to KSP 1.2.1 as per changelog

---

USI-SRV/USI-SRV-0.6.3.0.ckan
USI-SubPack/USI-SubPack-0.2.4.0.ckan

From Forum:
>Yup!  Sub pack and Srv-Pack are now part of the expedition pack.

RoverDude merge advice

---

TransferWindowPlanner/TransferWindowPlanner-v1.2.1.0.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.2.2.0.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.2.3.0.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.3.0.0.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.3.0.1.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.3.1.0.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.4.0.0.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.5.0.0.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.5.1.0.ckan
TransferWindowPlanner/TransferWindowPlanner-v1.6.0.0.ckan

TransferWindowPlanner URL fixes

---

AstronomersPack-AtmosphericScattering/AstronomersPack-AtmosphericScattering-Interstellar.V2.ckan
AstronomersPack-Auroras-4K/AstronomersPack-Auroras-4K-Interstellar.V2.ckan
AstronomersPack-Auroras-8K/AstronomersPack-Auroras-8K-Interstellar.V2.ckan
AstronomersPack-Clouds-High/AstronomersPack-Clouds-High-Interstellar.V2.ckan
AstronomersPack-Clouds-Low/AstronomersPack-Clouds-Low-Interstellar.V2.ckan
AstronomersPack-Clouds-Medium/AstronomersPack-Clouds-Medium-Interstellar.V2.ckan
AstronomersPack-DistantObjectEnhancement/AstronomersPack-DistantObjectEnhancement-Interstellar.V2.ckan
AstronomersPack-Eve-Jool-Clouds-2K/AstronomersPack-Eve-Jool-Clouds-2K-Interstellar.V2.ckan
AstronomersPack-Eve-Jool-Clouds-4K/AstronomersPack-Eve-Jool-Clouds-4K-Interstellar.V2.ckan
AstronomersPack-Eve-Jool-Clouds-8K/AstronomersPack-Eve-Jool-Clouds-8K-Interstellar.V2.ckan
AstronomersPack-Lightning/AstronomersPack-Lightning-Interstellar.V2.ckan
AstronomersPack-PlanetShine/AstronomersPack-PlanetShine-Interstellar.V2.ckan
AstronomersPack-Sandstorms/AstronomersPack-Sandstorms-Interstellar.V2.ckan
AstronomersPack-Snow/AstronomersPack-Snow-Interstellar.V2.ckan
AstronomersPack-SurfaceGlow/AstronomersPack-SurfaceGlow-Interstellar.V2.ckan
AstronomersPack/AstronomersPack-Interstellar.V2.ckan

Replace Download link for Astronomer's Visual Pack

---

TACLS/TACLS-v0.10.1.ckan
TACLS/TACLS-v0.11.1.20.ckan
TACLS/TACLS-v0.11.3.ckan
TACLS/TACLS-v0.11.ckan
TACLS/TACLS-v0.12.0.ckan
TACLS/TACLS-v0.12.1.ckan
TACLS/TACLS-v0.12.2.ckan
TACLS/TACLS-v0.12.3.ckan
TACLS/TACLS-v0.12.5.ckan
TACLS/TACLS-v0.12.6.ckan
TACLS/TACLS-v0.12.7.ckan
TACLS/TACLS-v0.12.8.ckan
TACLS/TACLS-v0.12.9.ckan

- Added missing versions v0.11 and v0.11.1.20
- Added missing dependency `CommunityResourcePack` for v0.12.0
- Added missing dependency `TACLS-Config` for v0.12.1 to v0.12.3
- Removed dependency `TACLS-Config` for v0.12.5 to v0.12.9 (KSP 1.2)

TACLS Configs - 1. Fix TACLS

---

Karbonite/Karbonite-1-0.8.8.0.ckan
Konstruction/Konstruction-0.2.0.0.ckan
MalemuteRover/MalemuteRover-0.3.0.0.ckan
SoundingRockets/SoundingRockets-0.6.0.0.ckan
UKS/UKS-1-0.52.0.0.ckan
USI-ART/USI-ART-1-0.10.0.0.ckan
USI-Core/USI-Core-0.4.0.0.ckan
USI-EXP/USI-EXP-0.8.0.0.ckan
USI-FTT/USI-FTT-0.7.0.0.ckan
USI-LS/USI-LS-0.6.0.0.ckan
USI-NuclearRockets/USI-NuclearRockets-0.4.0.0.ckan

This can maybe fix the USI problem by fixing the older 1.3 versions.

Fix USI metadata

---

SmartActuation/SmartActuation-1.0.1.ckan
SmartActuation/SmartActuation-1.0.ckan

Add `ksp_version` to SmartActuation

Fix SmartActuation

---

TestFlight/TestFlight-1.8.0.0.ckan
TestFlightConfigStock/TestFlightConfigStock-1.8.0.0.ckan

Fixes https://github.com/KSP-CKAN/NetKAN/issues/5583

Update TestFlight compatibility

---

AviationLights/AviationLights-v3.13.ckan

Fix AviationLights-3.13 KSP version

---

KSPInterstellarExtended/KSPInterstellarExtended-1.4.3.ckan

This reverts commit 7a3659a1663109303d2117c726766de6c5ca0ff0.
Author accidentally used old verision number uploading to Spacedock - now fixed
Closes #1278

Revert " "NetKAN generated mods - KSPInterstellarExtended-1.4.3""

---

RealFuels/RealFuels-rf-v12.2.2.ckan

Add RealFuels 12.2.2

---

AviationLights/AviationLights-v3.13.ckan

Update KSP Compatibility for AviationLights 3.13

---

KerbalKrashSystem/KerbalKrashSystem-1-0.4.0.ckan
KerbalKrashSystem/KerbalKrashSystem-1-0.4.1.ckan
KerbalKrashSystem/KerbalKrashSystem-1-0.4.2.ckan

Three releases for KSP 1.3 snuck past me!

KerbalKrashSystem 1.3 previous versions

---

AstronomersPack/AstronomersPack-Interstellar.V2.ckan

Rename old Astronomers Pack 

---

Trajectories/Trajectories-v1.6.7.ckan
Trajectories/Trajectories-v1.6.8.ckan

Update old Trajectories versions

---

ExceptionDetector/ExceptionDetector-1.ckan
ExceptionDetector/ExceptionDetector-2.ckan

Clean up old ExceptionDetector versions 

---

SoundTrackEditor/SoundTrackEditor-4.3.frozen

Freeze SoundTrackEditor

---

TimeControl/TimeControl-1-2.7.ckan
TimeControl/TimeControl-1-2.8.1.ckan

It looks like the Netkan bot is failing without reporting the failures to the status page.

Add new TimeControl releases

---

ESLDCore/ESLDCore-0.4.ckan
ESLDCore/ESLDCore-0.5.ckan
ESLDCore/ESLDCore-0.6.ckan
ESLDCore/ESLDCore-0.6a.ckan

Rename Old ESLD Jump Beacons

---

MiniAirbrakes/MiniAirbrakes-1.1.ckan

Updated compatible KSP version data from "1.0.4" to "any"

MiniAirbrakes compatible version update

---

Kerbalized-SpaceX/Kerbalized-SpaceX-1.31.ckan

Changed download link from GitHub to Spacedock for kerbalized SpaceX. I am the Author

Download link Change

---

TweakableEverything/TweakableEverything-1.15.ckan

Up the compatible ksp versions. I checked this on the forums and in-game.
Needed for https://github.com/KSP-CKAN/NetKAN/pull/6333

Update ksp version

---

AnyResContinued/AnyResContinued-2.0.2.1.ckan

This mod has out of date size and hashes.
Fixes https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1240-bruce/&do=findComment&comment=3338173

Update hashes of AnyResContinued old download

---

Kerbalism/Kerbalism-1.4.4.ckan

As noted on https://github.com/KSP-CKAN/CKAN-meta/commit/cd0d954e4da4808b5e4a7c5d23be9142463e8e35

Fix Kerbalism 1.4.4 download_size

---

SpeedUnitAnnex/SpeedUnitAnnex-1.2.0.1.ckan

This version of this mod got skipped over by the bot due to timing issues.
See KSP-CKAN/NetKAN#6823.

Add SpeedUnitAnnex 1.2.0.1

---

WaypointManager/WaypointManager-2.7.3.ckan

Replaced download, see https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1254-kennedy/&do=findComment&comment=3503578

Update WaypointManager 2.7.3 hashes

---

InnerLock-0.0.4_ksp-1.3.1.ckan
InnerLock-0.0.4_ksp-1.5.1.ckan

Add Innerlock releases uploaded to spacedock before the mod has been indexed by CKAN.

Add Innerlock releases

---

Kopernicus/Kopernicus-2-release-1.3.1-10.ckan
Kopernicus/Kopernicus-2-release-1.3.1-11.ckan
Kopernicus/Kopernicus-2-release-1.3.1-12.ckan
Kopernicus/Kopernicus-2-release-1.3.1-13.ckan
Kopernicus/Kopernicus-2-release-1.3.1-14.ckan
Kopernicus/Kopernicus-2-release-1.3.1-15.ckan
Kopernicus/Kopernicus-2-release-1.3.1-16.ckan
Kopernicus/Kopernicus-2-release-1.3.1-17.ckan
Kopernicus/Kopernicus-2-release-1.3.1-18.ckan
Kopernicus/Kopernicus-2-release-1.3.1-19.ckan
Kopernicus/Kopernicus-2-release-1.3.1-8.ckan
Kopernicus/Kopernicus-2-release-1.3.1-9.ckan
Kopernicus/Kopernicus-2-release-1.4.5-10.ckan
Kopernicus/Kopernicus-2-release-1.4.5-5.ckan
Kopernicus/Kopernicus-2-release-1.4.5-6.ckan
Kopernicus/Kopernicus-2-release-1.4.5-7.ckan
Kopernicus/Kopernicus-2-release-1.4.5-8.ckan
Kopernicus/Kopernicus-2-release-1.4.5-9.ckan
Kopernicus/Kopernicus-2-release-1.5.1-2.ckan
Kopernicus/Kopernicus-2-release-1.5.1-3.ckan
Kopernicus/Kopernicus-2-release-1.5.1-4.ckan
Kopernicus/Kopernicus-2-release-1.5.1-5.ckan
Kopernicus/Kopernicus-2-release-1.6.1-3.ckan

See KSP-CKAN/NetKAN#7219.
This pull request indexes the missing backports of Kopernicus.

Backfill Kopernicus backports

---

BobsPanicBox/BobsPanicBox-0.0.0.1.ckan
BobsPanicBox/BobsPanicBox-0.0.0.2.ckan
BobsPanicBox/BobsPanicBox-0.0.0.3.ckan
BobsPanicBox/BobsPanicBox-0.0.1.1.ckan
BobsPanicBox/BobsPanicBox-0.0.1.2.ckan
BobsPanicBox/BobsPanicBox-0.0.1.3.ckan
BobsPanicBox/BobsPanicBox-0.0.1.4.ckan
BobsPanicBox/BobsPanicBox-0.0.1.5.ckan
BobsPanicBox/BobsPanicBox-0.0.1.6.ckan
BobsPanicBox/BobsPanicBox-0.0.1.7.ckan
BobsPanicBox/BobsPanicBox-0.0.1.8.ckan
BobsPanicBox/BobsPanicBox-0.0.1.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.0.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.10.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.12.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.13.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.14.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.15.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.16.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.17.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.18.ckan
BobsPanicBox/BobsPanicBox-1-0.0.1.9.ckan

This is KSP-CKAN/NetKAN#7267 for old versions.

Fix BobsPanicBox repo link for historical versions

---

AstronomersVisualPack/AstronomersVisualPack-1-v3.7.ckan

Epoch old version of AVP

---

CameraFocusChanger/CameraFocusChanger-1-1.0.2.ckan

This mod had an epoch bump a while back, and one version is still out of order.

Epoch old CameraFocusChanger version

---

CrowdSourcedScience/CrowdSourcedScience-v5.0.ckan
CrowdSourcedScience/CrowdSourcedScience-v5.1.ckan
CrowdSourcedScience/CrowdSourcedScience-v5.2.ckan
CrowdSourcedScience/CrowdSourcedScience-v5.3.ckan

This pull request indexes the missing versions of Crowd Sourced Science.

Backfill Crowd Sourced Science

---

AJEExtendedConfigs/AJEExtendedConfigs-1-202.ckan

See https://github.com/KSP-CKAN/NetKAN/pull/7335

Epoch 'AJEExtendedConfigs-202.ckan'

---

KSPInterstellarExtended/KSPInterstellarExtended-1.22.5.1.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.22.5.2.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.22.5.3.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.22.9.0.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.22.9.1.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.22.9.2.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.22.9.3.ckan

Add KSPIE backports

---

MechJebFARExt/MechJebFARExt-1.0.0.ckan
SpacetuxSA/SpacetuxSA-0.1.0.ckan
SpacetuxSA/SpacetuxSA-0.3.1.ckan
SpacetuxSA/SpacetuxSA-0.3.2.ckan
USI-Core/USI-Core-0.1.8.0.ckan
VersatileToolboxSystem-TACLSPack/VersatileToolboxSystem-TACLSPack-3.1.ckan
VersatileToolboxSystem-TACLSPack/VersatileToolboxSystem-TACLSPack-3.ckan
VersatileToolboxSystem-USIPack/VersatileToolboxSystem-USIPack-3.1.ckan
VersatileToolboxSystem-USIPack/VersatileToolboxSystem-USIPack-3.ckan

See KSP-CKAN/CKAN#2880; KSP-CKAN/NetKAN#7419 repaired affected netkans, this PR fixes historical metadata.

Normalize historical install_to paths

---

ProjectManager/ProjectManager-v1.0.ckan
ProjectManager/ProjectManager-v1.1.ckan
ProjectManager/ProjectManager-v1.2.ckan
ProjectManager/ProjectManager-v1.3.ckan
ProjectManager/ProjectManager-v1.4.ckan
ProjectManager/ProjectManager-v2.0.ckan
ProjectManager/ProjectManager-v2.1.ckan
ProjectManager/ProjectManager-v2.2.ckan

See KSP-CKAN/NetKAN#7477; older versions of this mod aren't compatible with KSP 1.8.

Mark old ProjectManager versions as only compatible up to 1.7

---

Astrogator/Astrogator-v0.8.0.ckan
Astrogator/Astrogator-v0.8.1.ckan
Astrogator/Astrogator-v0.9.0.ckan
Astrogator/Astrogator-v0.9.1.ckan
SmartTank/SmartTank-v0.2.0.ckan
SmartTank/SmartTank-v0.2.1.ckan

This is KSP-CKAN/CKAN#2913 for old versions.

Add missing resources on old HebaruSan mods

---

CrewLight/CrewLight-1-1.19.1.ckan

See https://github.com/KSP-CKAN/NetKAN/pull/7520

Epoch old CrewLight release

---

Kopernicus/Kopernicus-2-release-1.3.1-26.ckan
Kopernicus/Kopernicus-2-release-1.4.5-17.ckan
Kopernicus/Kopernicus-2-release-1.5.1-12.ckan
Kopernicus/Kopernicus-2-release-1.6.1-10.ckan

Kopernicus backports

---

EarnYourStripes/EarnYourStripes-2.0.ckan
EarnYourStripes/EarnYourStripes-2.1.ckan
EarnYourStripes/EarnYourStripes-2.2.ckan

https://forum.kerbalspaceprogram.com/index.php?/topic/182372-18x-flighttracker-library-for-tracking-a-kerbals-flight-data-30-18012020/&do=findComment&comment=3716312
KSP-CKAN/NetKAN#7018
Historical version of fix from KSP-CKAN/NetKAN#7568.

Fix historical EarnYourStripes homepages

---

TalisarParts/TalisarParts-v1.2.1.ckan

Author confirmation of compatibility up to 1.7.1:
https://forum.kerbalspaceprogram.com/index.php?/topic/116849-18-talisar-parts-v130/&do=findComment&comment=3610249

Extend historical TalisarParts compatibility

---

Spectra/Spectra-v1.2.1.ckan
Spectra/Spectra-v1.2.2.ckan

This is KSP-CKAN/NetKAN#7663 for historical versions.

Update historical Spectra relationships

---

AlternateResourcePanel/AlternateResourcePanel-2.6.2.0.ckan
AlternateResourcePanel/AlternateResourcePanel-2.6.3.0.ckan
AlternateResourcePanel/AlternateResourcePanel-2.7.0.0.ckan
AlternateResourcePanel/AlternateResourcePanel-2.7.1.0.ckan
AlternateResourcePanel/AlternateResourcePanel-2.7.2.0.ckan
AlternateResourcePanel/AlternateResourcePanel-2.7.2.ckan
AlternateResourcePanel/AlternateResourcePanel-2.7.3.0.ckan
AlternateResourcePanel/AlternateResourcePanel-2.7.4.0.ckan
AlternateResourcePanel/AlternateResourcePanel-v2.7.4.0.ckan
AlternateResourcePanel/AlternateResourcePanel-v2.8.0.0.ckan
AlternateResourcePanel/AlternateResourcePanel-v2.8.1.0.ckan
AlternateResourcePanel/AlternateResourcePanel-v2.9.0.0.ckan
AlternateResourcePanel/AlternateResourcePanel-v2.9.1.0.ckan
AlternateResourcePanel/AlternateResourcePanel-v2.9.2.0.ckan
BoxSat/BoxSat-A.02c.kerbalstuff
BoxSat/BoxSat-A.02d.kerbalstuff
BoxSat/BoxSat-A.02e.ckan
Corvus125mTwoKerbalPod/Corvus125mTwoKerbalPod-1.1.1.kerbalstuff

First group to have the resource properties cleaned up, see #1816.

Cleanup first group of historical resources properties

---

Spectra/Spectra-v1.2.1.ckan
Spectra/Spectra-v1.2.2.ckan
Spectra/Spectra-v1.2.3.ckan

Historical side of KSP-CKAN/NetKAN#7706

Spectra shouldn't provide Scatterer-config

---

xScienceContinued/xScienceContinued-5.24.ckan

See https://forum.kerbalspaceprogram.com/index.php?/topic/182683-ksp-190-x-science-continued-ksp-science-report-and-checklist-v523/&do=findComment&comment=3741869

Fix historical xScienceContinued compat

---

ActsEW/ActsEW-1.5.ckan

This mod is discontinued, and the author has indicated a replacement:
Fixes KSP-CKAN/NetKAN#7822.

Mark ActsEW replaced by ModActions

---

KSPInterstellarExtended/KSPInterstellarExtended-1.25.15.1.ckan

A release was missed while SpaceDock's downloads were glitched out.

Backfill KSPIE

---

PAWRangeBuff/PAWRangeBuff-0.2.1.ckan

https://forum.kerbalspaceprogram.com/index.php?/topic/193572-180-19x-pawrangebuff-increase-your-eva-right-click-menu-distance/&do=findComment&comment=3782527

Historical compatibility for PAWRangeBuff

---

PayToPlay/PayToPlay-1.2.2.ckan
PayToPlay/PayToPlay-1.2.3.ckan

Grammar fix

---

JNSQ/JNSQ-0.8.1.ckan
JNSQ/JNSQ-0.8.5.ckan
JNSQ/JNSQ-0.8.6.ckan

Historical component of Galileo88/JNSQ#27.

Fix historical JNSQ sunflares

---

SpaceTuxLibrary/SpaceTuxLibrary-0.0.2.1.ckan

Remove extra zero from historical SpaceTuxLibrary version

---

RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.4.3.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.4.4.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.4.6.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.4.7.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.4.8.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.5.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.6.1.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.6.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.1.7.ckan
RecycledPartsAtomicAge/RecycledPartsAtomicAge-0.2.0.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.4.3.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.4.4.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.4.6.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.4.7.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.4.8.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.5.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.6.1.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.6.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.1.7.ckan
RecycledPartsFarscape/RecycledPartsFarscape-0.2.0.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.4.3.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.4.4.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.4.6.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.4.7.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.4.8.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.5.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.6.1.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.6.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.1.7.ckan
RecycledPartsRSCapsuledyne/RecycledPartsRSCapsuledyne-0.2.0.ckan

Historical counterpart of KSP-CKAN/NetKAN#7994.

Fix RecycledParts craft installs

---

StockishProjectOrion/StockishProjectOrion-1.7.5.ckan
StockishProjectOrion/StockishProjectOrion-1.7.ckan
StockishProjectOrion/StockishProjectOrion-1.8.0.ckan

Historical version of KSP-CKAN/NetKAN#8035.
The ships were added in 1.7.5.

Fix StockishProjectOrion compatibility

---

EnvironmentalVisualEnhancements/EnvironmentalVisualEnhancements-3-1.10.1-1.ckan

This is KSP-CKAN/NetKAN#8145 for the previous release from the new fork.

New homepage for historical EVE version

---

.github/workflows/validate.yml

See KSP-CKAN/xKAN-meta_testing#61.
This is HebaruSan/CKAN-meta#1 except with the master branch, the test data removed, and debugging output turned off.

Validate with GitHub Action

---

KSCExtended/KSCExtended-2.0.ckan
KSCExtended/KSCExtended-2.1.ckan

Backport of https://github.com/KSP-CKAN/NetKAN/pull/8308

Add KerbinSideRemastered to KSCExtended's depdenencies

---

MissingHistory/MissingHistory-1.9.ckan

Noted some clear and specific authorial statements while browsing for other reasons:
https://forum.kerbalspaceprogram.com/index.php?/topic/172232-111-missinghistory-v192-handy-parts-to-complement-making-history/&do=findComment&comment=3897589

Fix MissingHistory 1.9 compat and install

---

ReStockPlus/ReStockPlus-1.3.0.ckan

Fix ReStockPlus 1.3.0 min compat

---

VultureSystem/VultureSystem-1.0.2.ckan

Replaces KSP-CKAN/NetKAN#8383 because there's a 1.0.3 release on SpaceDock.

Set VultureSystem min compat

---

KSPInterstellarExtended/KSPInterstellarExtended-1.26.13.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.14.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.15.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.16.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.17.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.18.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.19.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.20.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.21.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.22.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.23.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.24.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.25.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.26.26.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.27.0.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.27.1.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.27.2.ckan
KSPInterstellarExtended/KSPInterstellarExtended-1.27.3.ckan

See KSP-CKAN/NetKAN#8497, CRP and CTT became dependencies in KSPIE 1.26.13.

Fix KSPIE dependencies

---

.github/workflows/validate.yml

Requires https://github.com/KSP-CKAN/xKAN-meta_testing/pull/76, see that link for more information.

Pass PR URL instead of body to xKAN-meta_testing action

---

RP-0/RP-0-v1.10.0.1.ckan

Fix RP-0 compat

---

EditorExtensionsRedux/EditorExtensionsRedux-3.4.3.ckan

Fix EditorExtensionsRedux compat

---

xScienceContinued/xScienceContinued-6.0.0.7.ckan

Historical component of KSP-CKAN/NetKAN#8677, this one will actually fix the problems users are having (the netkan update will only apply to future releases).

Fix xScienceContinued dependencies

---

SpeedUnitAnnex/SpeedUnitAnnex-1.4.2.ckan

https://forum.kerbalspaceprogram.com/index.php?/topic/169611-112-speed-unit-annex-%E2%80%94-enhanced-navball-panel-contextually-2021-11-17/&do=findComment&comment=4060979

Fix historical SpeedUnitAnnex compat

---

RSSDateTimeFormatter/RSSDateTimeFormatter-v1.12.0.0.ckan

Fix RSSDateTimeFormatter compat

---

Konstruction/Konstruction-0.1.10.0.ckan
Konstruction/Konstruction-0.1.11.0.ckan
Konstruction/Konstruction-0.1.12.0.ckan
Konstruction/Konstruction-0.1.4.0.ckan
Konstruction/Konstruction-0.1.5.0.ckan
Konstruction/Konstruction-0.1.6.0.ckan
Konstruction/Konstruction-0.1.7.0.ckan
Konstruction/Konstruction-0.1.8.0.ckan
Konstruction/Konstruction-0.1.9.0.ckan
Konstruction/Konstruction-0.2.0.0.ckan
Konstruction/Konstruction-0.2.1.0.ckan
Konstruction/Konstruction-0.2.2.0.ckan
Konstruction/Konstruction-0.3.0.0.ckan
Konstruction/Konstruction-0.3.1.0.ckan
Konstruction/Konstruction-0.4.0.0.ckan
Konstruction/Konstruction-0.5.0.0.ckan
Konstruction/Konstruction-1.1.0.0.ckan
Konstruction/Konstruction-1.2.0.0.ckan
Konstruction/Konstruction-1.3.0.0.ckan

Follow-up of #2524, #2522, #2521, #2520, #2512, #2511, #2510, #2509, #2508, #2507
Updating the repo and download links of Konstruction

Update Konstruction links after repo move

---

DepthMask/DepthMask-1.1.1.ckan

Historical version of DepthMask for convenience of RealismOverhaul

---

PlanetShine/PlanetShine-0.2.6.4.ckan
PlanetShine/PlanetShine-0.2.6.5.ckan

Historical component of KSP-CKAN/NetKAN#9200 for the versions between it and KSP-CKAN/NetKAN#9011.

Fix historical PlanetShine resources.repository

---

FoxDefenseContracts/FoxDefenseContracts-1.2.ckan
FoxDefenseContracts/FoxDefenseContracts-1.3.ckan
FoxDefenseContracts/FoxDefenseContracts-1.4.ckan
FoxDefenseContracts/FoxDefenseContracts-2.0.ckan

Historical component of KSP-CKAN/NetKAN#9293, going back to the version where the change was made.

Switch FoxDefenseContracts to BDArmoryForRunwayProject

---

ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-0.ckan
ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-1.ckan

After #3098 I noticed that these mods had broken old style forum links.
Now they're updated.

Fix blackheart textures homepage

---

APPLE/APPLE-1-1.1.9.ckan
FIG/FIG-1-1.0.2.ckan
GRAPES/GRAPES-1-1.0.2.ckan
LIME/LIME-1-1.1.3.ckan
MANGO/MANGO-1-1.1.1.ckan
ORANGE/ORANGE-1-1.0.3.1.ckan
PEAR/PEAR-1-1.0.2.ckan
PRUNES/PRUNES-1-1.0.1.ckan
VertikalSpeedIndicator/VertikalSpeedIndicator-1-1.2.1.1.ckan
VertikalSpeedIndicator/VertikalSpeedIndicator-1-1.2.1.2.ckan
VertikalSpeedIndicator/VertikalSpeedIndicator-1-1.2.1.ckan

This is KSP-CKAN/NetKAN#9351 for historical versions.

Add FruitGoose as author to FruitGoose's mods

---

TourismExpanded/TourismExpanded-1.0.2.ckan

Updated to be more consistent with other contract packs

Update TourismExpanded name

---

KcalbelohSystem/KcalbelohSystem-v1.0.1.ckan
KcalbelohSystem/KcalbelohSystem-v1.1.0.ckan
KcalbelohSystem/KcalbelohSystem-v1.1.1.ckan

<https://forum.kerbalspaceprogram.com/index.php?/topic/203753-*>
Noticed during KSP-CKAN/NetKAN#9744.
___
ckan compat add 1.12

Set compatibility for historical KcalbelohSystem

---

DSDMobileProcessingLabs/DSDMobileProcessingLabs-1.2.1.ckan

This repo is deleted, but there's an archive.org copy.

Fix download for DSDMobileProcessingLabs

---

BetterRocketDesigns/BetterRocketDesigns-v1.0.0.ckan

This author requested an older version to be added.
See KSP-CKAN/NetKAN#9929 for original indexing.

Add historical version of BetterRocketDesigns

---

RustyStarRockets/RustyStarRockets-1-1.8.99.1-prerelease.ckan
RustyStarRockets/RustyStarRockets-1-1.8.99.2-prerelease.ckan
RustyStarShipyards/RustyStarShipyards-0.9.99.0-prerelease.ckan

This is the historical component of KSP-CKAN/NetKAN#10091 and KSP-CKAN/NetKAN#10092.

Fix historical RustyStar installs

---

SimpleRepaint/SimpleRepaint-0.3.1.ckan
SimpleRepaint/SimpleRepaint-0.3.2.ckan
SimpleRepaint/SimpleRepaint-0.3.3.ckan
SimpleRepaint/SimpleRepaint-0.4.0.ckan
SimpleRepaint/SimpleRepaint-0.4.1.ckan

This is the historical component of KSP-CKAN/NetKAN#10245.

Fix SimpleRepaint version specific depends

---

TurboNisuReloaded/TurboNisuReloaded-2015-05-06.ckan

This PR fix mod homepage and KSP max version.
- https://forum.kerbalspaceprogram.com/topic/92020-10-turbonisureloaded-stock-a-like-parts-pack-060515/

Fix: TurboNisuReloaded
