KSP-CKAN/CKAN-meta

- ContractConfigurator-ContractPack-SCANsat/ContractConfigurator-ContractPack-SCANsat-v0.3.1.ckan
- ContractConfigurator-ContractPack-SCANsat/ContractConfigurator-ContractPack-SCANsat-v0.4.0.ckan
The spec special-cases `1` as a spec version, which is defined as an
integer. However these files contained `1` as a string. My whiny
pedantic validator complains as a result. :)
> Fix spec_version on ContractConfigurator-ContractPack-SCANsat

- TechManager/TechManager-1.5-compat.ckan
Nobody ever¹ has had any problems with TechManager 1.5 for 0.90, and
the author hasn't been seen in WEEKS. Since evrything good in the world²
uses TechManager and the Community Tech Tree, here's a compatibility
shim that will install v1.5 for 0.90.
"Why not change the existing metadata?", I hear you ask. Mainly it's
because it's generated by netkan, and if KerbalStuff ever gets
updated, or if the metadata ever gets regenerated, we don't want
anything to break.
Many thanks to Daz for the prompting.
Attentioning @NathanKell, because relevance.
Also, this means I might finally upgrade to KSP 0.90.
¹ Allegedly.
² RP-0
> TechManager compatibility file for 0.90

- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.19.ckan
From forum thread [link](http://forum.kerbalspaceprogram.com/threads/57603-0-25-RasterPropMonitor-putting-the-A-in-your-IVA-%28v0-18-3%29-8-Oct)
> A Note on 0.90.0 Compatibility:
>In Mihara's absence, MOARdv has kindly recompiled fixed versions of the RasterPropMonitor DLL for KSP 0.90.0
It's marked as a Pre-release on github (netkan.exe by default won't index this) however I think it should be used now instead v0.18.3
> RasterPropMonitor Core update

- Fusebox/Fusebox-1.3.ckan
According to forum post, not on curse, and only on Dropbox, so updated link to
point to new version.
> Manually added Fusebox 1.3

- MunarSurfaceExperimentPackage/MunarSurfaceExperimentPackage_v0.11.ckan
Permission to do so was requested and granted via private forum post.
Upstream package is currently only provided via Dropbox.
> Add CKAN configuration for AlbertKermin's Munar Surface Experiment Package mod.

- DDSLoader/DDSLoader-1.9.0.0.ckan
Now loads DDS textures boringly fast, with boringly fewer bugs!
```
$ ckan.exe show DDSLoader
DDSLoader: Loads DDS Textures boringly fast!
Module info:
- version:  1.9.0.0
- authors:  sarbian
- status:   stable
- license:  CC-BY-NC-SA-4.0
Provides:
- DDSLoader
Resources:
- homepage: http://forum.kerbalspaceprogram.com/threads/96729
- repository: https://github.com/sarbian/DDSLoader/
Showing 4 installed files:
- GameData/DDSLoader
- GameData/DDSLoader/DDSLoader.cfg
- GameData/DDSLoader/DDSLoader.dll
- GameData/DDSLoader/LICENSE.txt
```
> Add DDSLoader 1.9.0.0

- NearFutureSpacecraft/NearFutureSpacecraft-0.3.1.ckan
Nertea updated the [forum page for Near Future Technologies](http://forum.kerbalspaceprogram.com/threads/52042), confirming that Near Future Spacecraft Parts v3.1 is compatible with KSP 0.90.
> Update Near Future Spacecraft

- AJE/AJE-1.7a.ckan
closes https://github.com/KSP-CKAN/CKAN-meta/issues/217
Doing what I can to make it obvious that this version of AJE is the incorrect one and shouldn't be used.
> Making AJE more obviously deprecated

- HotRockets/HotRockets-7.9.ckan
- HotRocketsCommunityConfigs/HotRocketsCommunityConfigs-7.25.ckan
- HotRocketsEmissivePatch/HotRocketsEmissivePatch-7.9.ckan
closes https://github.com/KSP-CKAN/CKAN-meta/issues/5
Community Configs are only 0.25 compliant in accordance with curseforge, they probably work with 0.90 but right now I don't have the motivation to confirm this by reading through the whole HotRockets thread on forums so they're stuck at 0.25 for now.
Do note! I remembered newlines at the end of BOTH files \o/
> Updating HotRockets to 0.90 and adding Community Configs

- ModuleFixer/ModuleFixer.ckan
Needed for https://github.com/KSP-CKAN/NetKAN/pull/960 and the version does not appear to have changed from the 0.25 one so as such I'll bump this to 0.90 and keep it alive for a little longer.
> Making ModuleFixer.ckan 0.90 compatible

- ModuleFixer/ModuleFixer.ckan
Changing this to no longer conflict with Regolith since that has extremely detrimental effects on RO which recommends both `ModuleFixer` and `UniversalStorage` where the latter depends on `Regolith`.
This change makes ModuleFixer maintain its conflict with all USI partmods but not with the regolith.dll which should appease all parties.
> ModuleFixer conflict updates

- FirespitterCore/FirespitterCore-7.0.5463.30802.ckan
A bucketload of mods depend on this. Right now the older version is showing up for 1.0 and if we assume the original author was right in it working for any ksp version, this will aswell.
> Manual change so newest firespittercore shows in CKAN

- TreeLoader/TreeLoader-1.1.5.ckan
Yay TechTree config files in a KSP 1.0 install near you, this mod was already deprecated by TechManager and now we're putting it to sleep in 0.90 land.
> Treeloader should not show up in 1.0

- Tantares/Tantares-24.0.ckan
- TantaresLV/TantaresLV-9.0.ckan
Right now the mods are very old in CKAN and 1.0 is breaking them. This is causing grief to the mod author so I built these using the .netkan files we have indexed using an older netkan.exe (netkan 124 over at nightly builds).
If Jenkins approves (he works here since they are ksp_version_min 0.25) I'll add these.
> Manual additions of Tantares for 1.0

- kOS/kOS-0.17.2.ckan
Since 0.17.2 pre-release is only version that works with 1.0.0 and avaliable only on GitHub, I manually added ckan file for it. Tested it locally and it installs correctly.
> Added kOS 0.17.2 pre-release to get 1.0.0 compat

- USI-LS/USI-LS-0.1.0.ckan
Built with `netkan USI-LS.netkan --prerelease` from the .netkan file in https://github.com/KSP-CKAN/NetKAN/pull/1021 so once we have that one going this one will be consistent.
> Manual addition of USI-LS pre-release

- HotRockets/HotRockets-7.9.ckan
Reverts KSP-CKAN/CKAN-meta#421
Just found a bug making some FX incompatible with the current KSP jet engines.
Sorry for the inconveniences.
> Revert "Update HotRockets-7.9.ckan for KSP1.0"

- Toolbar/Toolbar-1.7.9.ckan
made the versioning schema for 1.7.8 stricter but only strict enought to provide an upgrade path for users running ksp 1.0.2.
1.7.9 only seems to want to play nice with 1.0.2 so that's why it's set to only that version.
> Add toolbar 1.7.9, stricter versioning on 1.7.8

- RealRoster/RealRoster-v2.1.ckan
only available for 0.25, download currently dead but author is looking to rehost it. Keeping the mod around so if anyone acctually ever gets an error report for 0.25 well... check http://forum.kerbalspaceprogram.com/threads/87473-25-x-RealRoster-Editor-Crew-Tab-Fixed?p=1882939&viewfull=1#post1882939 and forward in hope a rehost.
> Fix RealRoster to have the right ksp_version

- KerbalAlarmClock/KerbalAlarmClock-v3.3.0.0.ckan
closes #437 
3.3.0.1 is basically just an update fix to KerbalStuff metadata which contains no codechanges but it's also the latest version netkan-bot catches from github so by doing this we get the latest version (codewise) available in CKAN without the risk of our beloved bot overwriting the ksp_version field.
Author of KAC has been contacted and it would be good if this PR was reverted once https://github.com/KSP-CKAN/NetKAN/issues/1114 and/or https://github.com/TriggerAu/KerbalAlarmClock/issues/129 has been adressed as to ensure that the authors intended versioning is ensured.
> Ugly fix to KAC not showing up in 1.0.2

- BoxSat-prototypes/BoxSat-prototypes-A.02e.ckan
- BoxSat/BoxSat-A.02e.ckan
BoxSat developers have [decided to no longer distribute via Kerbal Stuff](http://forum.kerbalspaceprogram.com/threads/91616?p=1924575#post1924575).
These are manual CKAN files for the newest release on Curse.
- Removed Kerbal Stuff resource
- Added dependencies on `ModuleManager`
- ~~Made `BoxSat-prototypes` dependent on `BoxSat`~~ Removed dependency until both are updated
- Filtered out `.ddsified` files that were not removed from the distribution
> Update BoxSat and BoxSat-prototypes

- MechJebForAll/MechJebForAll-1.2.0.0.ckan
This module will work with either installed, and will not break in the extreme case that neither are installed.
There's a strong argument to be made that these should be requirements instead of suggestions.  I'd be okay with that, too, but I went with the conservative approach.
> Make MechJeb2 and KerbalEngineerRedux suggestions in MechJebForAll

- KAS/KAS-0.5.1.ckan
Using previous versions b0rks hard.
> Add min_version for KAS's KIS dependency

- ZeroPointInlineFairings-Lite/ZeroPointInlineFairings-Lite-0.8.ckan
- ZeroPointInlineFairings-Lite/ZeroPointInlineFairings-Lite-0.9.ckan
- ZeroPointInlineFairings/ZeroPointInlineFairings-0.8.1.ckan
- ZeroPointInlineFairings/ZeroPointInlineFairings-0.9.1.ckan
- ZeroPointInlineFairings/ZeroPointInlineFairings-0.9.ckan
Seems I forgot to fix the older versions of this mod in my last PR that update the newest ones.
> Fix older versions of 0point fairings

- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.19.0.ckan
- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.19.1.ckan
- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.19.2.ckan
See https://github.com/Mihara/RasterPropMonitor/issues/228
v0.19.0 does not seem to exist - use the version the author has said is for 0.90
If that is the version for 0.90 then the later ones allowing installs to 0.90 must be mistakes.
> Fix download link and fix versioning issue.

- SmokeScreen/SmokeScreen-2.5.0.ckan
- SmokeScreen/SmokeScreen-2.5.3.ckan
- SmokeScreen/SmokeScreen-2.6.0.ckan
Prompted by #536.
SmokeScreen is a pure library, no user would really be installing it directly. It shouldn't be recommending any other mods (I think even `suggests` is too strong of a relationship).
With the `recommends`, users installing CoolRockets would receive HotRockets by default, which isn't likely what the user wants.
> Remove HotRockets recommendation in SmokeScreen

- HGR-Props/HGR-Props-1.2.1.ckan
- HGR/HGR-1.2.1.ckan
These are two hand-written ckan files for the Home Grown Rockets 1.875m part pack. I split the pack in the actual 1.875m parts package and the props package, which is used by HGR's Corvus package.
DO-NOT-MERGE until we have explicit permission from the mod author to index and distribute the mod through CKAN.
> Add HGR 1.875m mod pack

- build.sh
an update to #548 to match https://github.com/KSP-CKAN/NetKAN/blob/master/build.sh#L88:L94 and have our builds generate similar output, because Daz likes it that way.
> prettify the console output of Jenkins to match NetKAN

- build.sh
After each 'mono --debug ckan show <identifier>' in Jenkins NetKAN console outputs we have an echo of --------------- 2 times to show that we're now showing another mod.
My hope is that this will do something similar, however I have never used perl in my life so this might aswell be asking it to delete the universe or just flat out be wrong.
> Add newlines in Jenkins output to almost match NetKAN output

- AerojetKerbodyne/AerojetKerbodyne-3.0.5.ckan
- AerojetKerbodyne/AerojetKerbodyne-3.04.ckan
- RealPlume/RealPlume-v7.0.4.ckan
- RealPlume/RealPlume-v7.0.5.ckan
- RealPlume/RealPlume-v7.0.6.ckan
- RealPlume/RealPlume-v7.0.7.ckan
- RealPlume/RealPlume-v8.0.0.ckan
- RealPlume/RealPlume-v8.0.1.ckan
- RealPlume/RealPlume-v8.1.0.ckan
- RealPlume/RealPlume-v8.1.1.ckan
- RealPlume/RealPlume-v8.2.0.ckan
- RealPlume/RealPlume-v8.4.1.ckan
- SmokeScreen/SmokeScreen-2.5.0.ckan
- SmokeScreen/SmokeScreen-2.5.3.ckan
- SmokeScreen/SmokeScreen-2.6.0.ckan
- SmokeScreen/SmokeScreen-2.6.1.ckan
This removes the `ModuleManager` dependency from `SmokeScreen`, since it's *not actually* a dependency for `SmokeScreen` itself.
However, we need to make sure no mod was implicitly depending on `SmokeScreen` to pull in `ModuleManager`. Of the mods which themselves depended on `SmokeScreen` here are their dispositions with regards to `ModuleManager`:
- `HotRockets`
- `CoolRockets`
- `RealEffects`
- `RetroFuture`
- `KerbinShuttleOrbiterSystem`
- `KerbalStockLauncherOverhaul`
- `RealismOverhaul`
- `SpaceShuttleEngines`
- `AerojetKerbodyne`
- `RealPlume`
This PR removes the dependency from `SmokeScreen` and backports the `ModuleManager` dependency to `AerojetKerbodyne` and `RealPlume`. KSP-CKAN/NetKAN#1446 adds those changes to those mod's respective netkan files.
> Remove ModuleManager Dependency from SmokeScreen

- AdaptiveDockingNode/AdaptiveDockingNode-1.6.ckan
Adds `ksp_version` to `AdaptiveDockingNode-1.6` to prevent it from showing up for future versions of KSP.
This should be mergeable when the NetKarmgeddon (#558) is resolved and fbdbad944f8e0cbe33f86a25a7b9aa0c9dffaa3c is reverted.
> Add KSP version to AdaptiveDockingNode-1.6

- Workshop/Workshop-0.7.3.ckan
Generated this file from Workshop.netkan over in the NetKAN repository. Manually adding it since indexing is currently down and this mod is linked to the new KIS version added in #562 aka players using OSE Workshop need this version to be able to use them with KIS 1.1.5.
This might seem like a minor thing but it's affecting me so I'm fixing it.
> manual addition of Workshop-0.7.3.ckan

- ModularFlightIntegrator/ModularFlightIntegrator-1.0.repackaged0.ckan
Based on #577 I'm adding a manual update of this mod.
https://github.com/KSP-CKAN/CKAN-meta/commit/cffba41fb297d16c450ae47c8991dc35b1be8dcd should have probably triggered us to repackage this back then so if anyone is acctually using the version prior to that commit they might run into trouble.
> Add a repackaged version of ModularFlightIntegrator

- RSSTextures2048/RealSolarSystemTextures_2048-1.0.ckan
- RSSTextures4096/RealSolarSystemTextures_4096-1.0.ckan
- RSSTextures8192/RealSolarSystemTextures_8192-1.0.ckan
- RSSTexturesDDS2048/RSSTexturesDDS2048-1.0.ckan
- RSSTexturesDDS4096/RSSTexturesDDS4096-1.0.ckan
- RSSTexturesDDS8192/RSSTexturesDDS8192-1.0.ckan
Based on https://github.com/KSP-CKAN/NetKAN/pull/1522
I've also elected not to rewrite the malformed naming on these files since there is a slight chance that would make new generated files from the referenced NetKAN PR overwrite these ones.
Basically I'm hiding all past sins by confining them to 0.90.
This PR will fail because Jenkins is running KSP 1.0.2.
> Confine the old RSS-Textures to 0.90 and below

- ExtraPlanetaryLaunchpads-RegolithAdaptation/ExtraPlanetaryLaunchpads-RegolithAdaptation-30.ckan
- ExtraPlanetaryLaunchpadsExtendedPartPack/ExtraPlanetaryLaunchpadsExtendedPartPack.ckan
Closes #486 - See #486 for extra details on this change.
New name + new function = New mod
Homepage of 0.30 is changed to the KerbalStuff page since the forum thread is dedicated to the new mod.
I have the new mod (extended) conflict with the old (regolith) since the author is using a lot of the same files/file names.
I'm unclear on what to do with/about the CommunityResourcePack folder. It was ignored in the Regolith releases in terms of both install stanza as well as dependencies/recommendations.
> EPL RegolithAdaptation/ExtendedPartPack split

- PorkjetHabitats/PorkjetHabitats-0.4.ckan
This is going to fail the build because it's capping the KSP version to before the current one.
> Put KSP version cap on old verison of PorkjetHabitats

- KerbalJointReinforcement/KerbalJointReinforcement-v3.1.4.ckan
As received from KerbalStuff:
Hi there! Thought you would like to know that ferram4 told us that version v3.1.4 of Kerbal Joint Reinforcement works great with Kerbal Space Program 1.0.4.
If you are already up-to-date, you don't need to do anything. Otherwise, you can grab the latest version here:
http://kerbalstuff.com/mod/53/Kerbal_Joint_Reinforcement
If you'd prefer us not to email you about this mod, you can hit "Unfollow" on this mod's page and you won't get them any more.
> KJR 3.1.4 is compatible with KSP 1.0.4

- EditorExtensions/EditorExtensions-2.3.ckan
Reported by @SkyMarshal in KSP-CKAN/CKAN#1184.
> EditorExtensions 2.3 isn't *THAT* forward compatible.

- BackgroundProcessing/BackgroundProcessing-0.2.3.ckan
- CommunityTechTree/CommunityTechTree-1.0.ckan
- UniversalStorage-ECLSS/UniversalStorage-ECLSS-0.9.2.ckan
- UniversalStorage-IFI/UniversalStorage-IFI-0.9.0.ckan
- UniversalStorage-SNACKS/UniversalStorage-SNACKS-0.9.0.ckan
- UniversalStorage-TAC/UniversalStorage-TAC-0.9.2.ckan
- UniversalStorage/UniversalStorage-0.9.4.ckan
- UniversalStorage/UniversalStorage-1.0.0.ckan
- UniversalStorage/UniversalStorage-1.0.90.0.ckan
This should hopefully be an easy merge. This stops the potential for us seeing warnings that we're got bad metadata in our repo.
> Tidy-up of not-quite-right URLs in resource metadata

- PartWizard/PartWizard-1.2.1.ckan
Changed static ksp_version to ksp_version_min and _max.
> PartWizard 1.2.1 Added min-max KSP override for 1.0.4

- FLEET/EPL-ISRU-1.0.ckan
- FLEET/EPL-MKS-1.0.ckan
- FLEET/EPL-fastbuild-1.0.ckan
No changes needed to the actual patches, but the metadata needed to be updated to signify 1.0.4 compatibility.
> Update ksp_version information for EPL ModuleManager tweaks

- MechJebFARExt/MechJebFARExt-1.0.0.ckan
This change means we're happy with any version of FAR from
v0.15.2 *or later*, rather than insisting on v0.15.2 *exactly*.
Attn @Sarbian in case we really *do* need an exact version (our
user reports say that current FAR releases have been working fine).
> MechJebFARExt requires *at least* FAR v0.15.2

- ModularFlightIntegrator/ModularFlightIntegrator-1.1.1.ckan
- SmokeScreen/SmokeScreen-2.6.5.ckan
Where's the automatic testing gone?
~~One of my test installs is not offering the upgrade to MFI, can someone please test that it does offer the upgrade properly.~~ Should be fine: the test install was still on 1.0.2.
Is
>"ksp_version": "1.0.4"
preferred to
>"ksp_version_min": "1.0.4",
>"ksp_version_max": "1.0.4"
as produced by netkan from the avc file?
> Create .ckan files for ModularFlightIntegrator and SmokeScreen

- build.sh
CKAN artifacts are built by travis now and this has stopped working now that the old build server is MIA.
Pinched from @mgsdk's script :-)
> Update ckan build url

- build.sh
This will stop build.sh changes always failing.
I think @mgsdk's work on the NetKAN build script would apply to the CKAN-Meta. So I might take a look into porting it.
> Stop testing build

- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.18.3.ckan
- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.19.0.ckan
- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.19.1.ckan
- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.19.2.ckan
- RasterPropMonitor-Core/RasterPropMonitor-Core-v0.19.ckan
In the case of `v0.19.2` I only changed `ksp_version_min` to `ksp_version`, in all other cases I copied the `ksp_version` that was present in the equivalent RPM version.
More details see #623
> RasterPropMonitor-Core promiscuous versions

- SETI-CommunityTechTree/SETI-CommunityTechTree-0.9.1.4.ckan
- SETI-CommunityTechTree/SETI-CommunityTechTree-0.9.1.ckan
The latest available version of SETI-CTT is 0.9.1.4 but it gets indexed as (And have overwritten) 0.9.1.
This moves the edited file to 0.9.1.4 so the upgrade path should work, and restores the 0.9.1 file.
> SETI-CommunityTechTree version fix.

- KWRocketry-CommunityFixes-interstage/KWRocketry-CommunityFixes-interstage-0.1.0.ckan
- KWRocketry-CommunityFixes/KWRocketry-CommunityFixes-0.1.0.ckan
- KWRocketry/KWRocketry-2.7.0-community.ckan
- KWRocketry/KWRocketry-2.7.1-community.ckan
by @linuxgurugamer
[Forum thread](http://forum.kerbalspaceprogram.com/threads/129918-KW-Rocketry-Community-Fixes)
I'm not sure what licence is this. At forum
>License is GPL  
however KS says MIT
This PR contains 3 packages
KWRocketry-2.7.1 - this is 2.7 but set to works on KSP 1.0.4 and depends on Community-Fixes
KWRocketry-CommunityFixes -  Community-Fixes :+1: 
KWRocketry-CommunityFixes-interstage - optional config. May break your crafts. 
Would be great if someone test it. Works for me.
> Added KW Community fixes

- KAS/KAS-0.5.4.ckan
New release. Remove dependency on KIS. Changed to recommends and new KIS versions
> KAS-0.5.4 New Release - no dep on KIS anymore

- ModuleFixer/ModuleFixer-3.ckan
Apart from making the filename match our given convention this also prepares this file for https://github.com/KSP-CKAN/CKAN/pull/1304 which has a dislike for multiple non-nested comments.
> Update and rename ModuleFixer.ckan to ModuleFixer-3.ckan

- repositories.json
The client has been able to handle .tar.gz for a while. Recent releases (at least since v1.12) use it by default. This updates our list of repos to use the .tar.gz versions which require less bandwidth than their zippy counterparts.
(This is the file that users see when they go to the CKAN settings in the GUI, and check out available repos)
> Common metadata repos can now download in .tar.gz format

- build.sh
I'm hoping this alleviates the issue of older versions of MM not being available (and thus causing failures in Jenkins installs). Most recent PR with this issue: #748
> Use ksp_version_max instead of ksp_version_min in build script

- build.sh
Many mods have `ksp_version_max: 1.0.99` and dependencies fail because not all mods have such a high compatibility ceiling. So instead lets use the default ksp version when we hit 1.0.99.
> Add case in build script for ksp_version being 1.0.99

- Airlock/Airlock-1.0.ckan
The mod's author listed the mod under MIT originally ([KerbalStuffBot's PR](https://github.com/KSP-CKAN/NetKAN/pull/1950/files)), but the abstract reflected the license he wanted (my error for not catching the abstract). I'm willing to give the author the benefit of the doubt that they simply chose the license incorrectly. This is why it's nice when mods have KSP forum threads and/or include the license in their package.
Closes  #762
> Correct abstract and change license for Airlock

- HotRocketsEmissivePatch/HotRocketsEmissivePatch-7.9.ckan
This mod is actually hard to find info about, but the curseforge info on it says it's for 0.90, and since there's no mention of it anywhere else I'm confident saying we can lock it to that version.
Closes #761
> Restrict HotRocketsEmissivePatch to 0.90

- GPWS/GPWS-0.3.2.0.ckan
Previous discussion: https://github.com/KSP-CKAN/NetKAN/pull/2412
This is a stop-gap solution to index GPWS since netKAN is not able to index mods on github that are released with the pre-release tag.
This closes KSP-CKAN/netKAN#2406.
> Add Ground Proximity Warning System v0.3.beta-2 mod

- ModuleManager/ModuleManager-2.6.10.ckan
- ModuleManager/ModuleManager-2.6.11.ckan
- ModuleManager/ModuleManager-2.6.12.ckan
- ModuleManager/ModuleManager-2.6.4.ckan
- ModuleManager/ModuleManager-2.6.9.ckan
@sarbian, I saw that ModuleManager was updated to 2.6.12 on Jenkins. I also added an earlier version while I was at it.
> Add missing ModuleManager's

- CactEyeTelescopesContinued/CactEyeTelescopesContinued-0.6.10.ckan
The latest version of CactEyeTelescopesContinued is only compatible with KSP 1.0.5
> Uncompatible KSP version

- SurfaceMountedLights/SurfaceMountedLights-1.1.ckan
- surfacelights/SurfaceLights-1.0.ckan
- surfacelights/surfacelights-1.1.ckan
We're terminating the `SufaceMountedLights` identifier and giving the existing user base of `surfacelights` an upgrade path. We're making the deprecation of `SufaceMountedLights` clear to users.
Merge after https://github.com/KSP-CKAN/NetKAN/pull/2567
> Surfacemounted

- KittopiaTech/KittopiaTech-0.192.ckan
- KopernicusTech/KopernicusTech-0.13.ckan
Let KittopiaTech and KopernicusTech conflict with each other and with the new Kopernicus.
Part of the PlanetPack overhaul
> Update planet packs

- AdvancedJetEngine/AdvancedJetEngine-2.5.1.ckan
Was marked 1.0.4, should be 1.0.5.
> Force-update AJE 2.5.1 metadata

- ActiveTextureManagement-x86-Basic/ActiveTextureManagement-x86-Basic-5-0.ckan
It produces lots of "Method not found: 'GameDatabase.TextureInfo..ctor'" errors in log and all parts in game are white.
> ATM 5 does not work with KSP 0.90

- ModuleRCSFX/ModuleRCSFX-v4.0.ckan
- ModuleRCSFX/ModuleRCSFX-v4.1.ckan
ModuleRCSFX is obsolete as of KSP 1.0.5 Version 4.2 is marked as incompatible, but  4.0 and 4.1 have looser ksp_version data.
> Fix KSP version range on old ModuleRCSFX versions

- B9AerospaceProceduralParts/B9AerospaceProceduralParts-0.40.ckan
I spent a few hours building seaplanes with this, both with and without FAR.  No issues reported on the forum.  Seems to work fine in 1.0.5.
> Mark B9 Procedural Parts compatible with 1.0.5.

- HangarExtender/HangarExtender-2.0.ckan
- HangarExtender/HangarExtender-3.0.ckan
CKAN is always showing `3.0` instead of `1:v3.4.6`. Adding a `v` before the version numbers fixes this problem.
Part of KSP-CKAN/NetKAN/pull/2775
> Add 'v' to fix displaying wrong version

- FShangarExtender/FShangarExtender-2.0.ckan
- FShangarExtender/FShangarExtender-3.0.ckan
Part of a fix for https://github.com/KSP-CKAN/NetKAN/pull/2441 and https://github.com/KSP-CKAN/NetKAN/pull/2775
Second part is a ksp_version bump in the `HangarExtender` netkan
> Rename old mod to allow new one to use the `name` they share

- ContractConfigurator-KerbinSpaceStation/ContractConfigurator-KerbinSpaceStation-3.0.2.ckan
Per @severedsolo in https://github.com/KSP-CKAN/NetKAN/issues/2798 this version of the mod is not compatible with ksp_versions < 1.0.5.
Closes https://github.com/KSP-CKAN/NetKAN/issues/2798.
> Update ksp version compatibility.

- CrewManifest/CrewManifest-0.6.1.0.ckan
- CustomBarnKit/CustomBarnKit-1.1.3.0.ckan
- GCMonitor/GCMonitor-1.2.8.0.ckan
- MechJeb2/MechJeb2-2.5.5.0.ckan
- ModularFlightIntegrator/ModularFlightIntegrator-1.1.0.0.ckan
- ModularFlightIntegrator/ModularFlightIntegrator-1.1.2.0.ckan
- SmokeScreen/SmokeScreen-2.6.9.0.ckan
Merge before https://github.com/KSP-CKAN/NetKAN/pull/2837
This will set up current .ckans to allow a smooth transition to netkan automation. It should also avoid any potential versioning awkwardness.
> Bring current versions in line with what netkans

- Toolbar/Toolbar-1.7.10.ckan
- Toolbar/Toolbar-1.7.9.ckan
It is my hope that this will "unblock" Jenkins and stop tests failing due to it not being able to download toolbar.
> Change toolbar download links to mirror

- SmokeScreen/SmokeScreen-2.6.0.ckan
- SmokeScreen/SmokeScreen-2.6.1.ckan
- SmokeScreen/SmokeScreen-2.6.2.ckan
- SmokeScreen/SmokeScreen-2.6.3.ckan
- SmokeScreen/SmokeScreen-2.6.4.ckan
- SmokeScreen/SmokeScreen-2.6.5.ckan
- SmokeScreen/SmokeScreen-2.6.6.ckan
- SmokeScreen/SmokeScreen-2.6.7.ckan
- SmokeScreen/SmokeScreen-2.6.8.ckan
- SmokeScreen/SmokeScreen-2.6.9.0.ckan
2.6.10 has fixed some stuff that was broken in 1.0.5, so restricting older versions to 1.0.4
> Update Smokescreen 2.6.* to limit KSP version

- KerbalAircraftExpansion/KerbalAircraftExpansion-1-KAX_v2.5.3.ckan
- KerbalAircraftExpansion/KerbalAircraftExpansion-1-KAX_v2.5.4.ckan
KerbalAircraftExpansion recently started inserting "KAX-" at the start of their version numbers. Epoch required to fix versioning. Also, install example craft to Ships/SPH.
> Set Epoch on recent KAX ckans

- AdvancedJetEngine/AdvancedJetEngine-1.6.4.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.6.8.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.6.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.7a.ckan
Changing identifiers is a taboo but in this case `AJE` has not had a new .ckan since the days of ksp 0.90 and is, for many intents and purposes, a dead identifier. So with this we unify AJE and AdvancedJetEngine giving a clear upgrade path and reducing confusion overall.
Closes https://github.com/KSP-CKAN/CKAN/issues/1439
> Unify AdvancedJetEngine under a single identifier

- repositories.json
I now have a CKAN repository where my jenkins server adds all new Mechjen2 Dev builds.
You have a look at the generated files here : 
https://ksp.sarbian.com/ckan/
> Use Sarbian repository for Mechjeb2-Dev

- RCSBuildAid/RCSBuildAid-v0.7.6.ckan
RCSBA 0.7.6 fails in KSP 1.0.4
> RCSBuildAid 0.7.6 only supports 1.0.5

- CustomAsteroids-Pops-Stock-Inner/CustomAsteroids-Pops-Stock-Inner-v1.1.0.ckan
- CustomAsteroids-Pops-Stock-Inner/CustomAsteroids-Pops-Stock-Inner-v1.2.0.ckan
- CustomAsteroids-Pops-Stock-Outer/CustomAsteroids-Pops-Stock-Outer-v1.1.0.ckan
- CustomAsteroids-Pops-Stock-Outer/CustomAsteroids-Pops-Stock-Outer-v1.2.0.ckan
- CustomAsteroids/CustomAsteroids-v1.1.0.ckan
- CustomAsteroids/CustomAsteroids-v1.2.0.ckan
Removed references to KerbalStuff, fixed bad Kopernicus reference to match KSP-CKAN/NetKAN#3226 (since it appears old `.ckan` files don't get updated by the bot).
> Custom Asteroids manual updates

- HeatManagement/HeatManagement-0.26.3.ckan
- VanguardAstrodynamicsVXSeries/VanguardAstrodynamicsVXSeries-1.2.1.ckan
Reverts KSP-CKAN/CKAN-meta#980
Spacedock links died.
> Revert "HeatManagement and VanguardAstrodynamicsVXSeries to spacedock downloads"

- VesselView/VesselView-v0.71.ckan
Primary download on forum thread, takes the load off the KS mirror.
Advised this mod is functional in 1.0.5 in CKAN forum thread
Next version of this mod is probably going to need an epoch.
> Move VesselView to Dropbox

- DockingPortAlignmentIndicator/DockingPortAlignmentIndicator-6.2.ckan
netkan file is currently frozen pending Curse scraping. It has been updated.
Found missing file through Godarklights metadata checker
> Add missing file installation

- KduffersKorpHotrodWheels/KduffersKorpHotrodWheels-1.0.ckan
- KduffersKorpHotrodWheels/KduffersKorpHotrodWheels-1.1.ckan
- KduffersMultiwheels/KduffersMultiwheels-1.0.ckan
- KduffersMultiwheels/KduffersMultiwheels-1.3.ckan
- kdufferskorpracewheel/kdufferskorpracewheel-1.0.ckan
Multiwheels contains the other two packs.
Also sets homepage to forum link and removes kerbalstuff links.
Closes #1031
> Add conflicts for Kduffers Wheels packs

- build.sh
A little early to set the new default to 1.1.0. This reverts it and brings it back in line with NetKAN.
> Revert default ksp version to 1.0.5 - #1045

- TransferWindowPlanner/TransferWindowPlanner-v1.2.1.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.2.2.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.2.3.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.3.0.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.3.0.1.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.3.1.0.ckan
Using information included on Github.
Ref KSP-CKAN/NetKAN#3569, which should lead to 1.4.0.0 being corrected.
> Set KSP Version for old TransferWindowPlanner releases

- KWRocketry-CommunityFixes-interstage/KWRocketry-CommunityFixes-interstage-0.4.10.ckan
This fails for the reason this PR exists; It can't be installed under 1.1.0.
> Explicitly depend KWRocketry so that we don't show this mod as compatible

- ContractConfigurator-SCANsat/ContractConfigurator-SCANsat-1.0.1.ckan
- ContractConfigurator-SCANsat/ContractConfigurator-SCANsat-1.0.2.ckan
- ContractConfigurator-SCANsat/ContractConfigurator-SCANsat-1.0.ckan
Per this mod's github page (Latest commit https://github.com/SimonTheSourcerer/CCSCANsatMissionPack/commit/faad93e166c83f7713182bb167fa5539244dbe4e on Jan 23, 2015):
>Stopped in development, please use: DBT85's pack: http://forum.kerbalspaceprogram.com/threads/108097-0-90-Contract-Pack-SCANSat-v0-5-0-2015-01-22 instead.
The link is a reference to the mod we ID as `ContractConfigurator-ContractPack-SCANsat`.
I think when the .netkan for this was deleted in https://github.com/KSP-CKAN/NetKAN/commit/40c0302401916ddf877b40d2cd3a20fcc16c2257 these .ckans were simply forgotten about. This is a correction to that oversight.
> Add compatibility ceiling for deprecated mod.

- PlanetShine-Config-Default/PlanetShine-Config-Default-0.2.5.ckan
- PlanetShine/PlanetShine-0.2.5.ckan
I had a few users reporting that PlanetShine was not properly displaying its toolbar icons, and I realized that CKAN was messing with the intended install paths. I don't know since when this issue has been there, but this should fix it.
The intended folder structure is:
* GameData
* PlanetShine
* Config
* Icons
* Plugins
However currently CKAN is giving this result:
* GameData
* PlanetShine
* Config
* PlanetShine
* Icons
* Plugins
> Fixed PlanetShine install path and URL

- PlanetShine-Config-Default/PlanetShine-Config-Default-1-0.2.5.ckan
- PlanetShine/PlanetShine-1-0.2.5.ckan
#1071 showed we were installing `PlanetShine` incorrectly and its changes will fix future installs, however by using an epoch we can have ckan think that planetshine has an update and will force a re-install to the correct path (to those that choose to update). 
cc @valerian
> Bump PlanetShine epoch

- KSP-AVC/KSP-AVC-1.1.5.0.ckan
Unity 5 finally broke KSP-AVC's compatibility.
Closes #1089
> KSP-AVC - 1.1.5 - Limit KSP compatibility

- RoverWheelSounds/RoverWheelSounds-2.2.ckan
Stripped out the old kerbalstuff references.  The github hasn't been updated since 1.3 - but might as well leave it in I suppose.
> RoverWheelSounds seems to live on curseforge for the time being.

- RealChute/RealChute-v1.4.1.1.ckan
The current version's .version file has a JSON error. This was generated from a netkan with vref removed and ksp_versions hardcoded from the info within the .version file. .netkan left intact so that it picks up the next release without issue.
> Add RealChute-v1.4.1.1.ckan

- KIS/KIS-1.2.9.ckan
Hey,
Is there a way to make CKAn automatically pickup latest file from CurseForge? E.g. for this particular project latest release is always available via link: http://kerbal.curseforge.com/projects/kerbal-inventory-system-kis/files/latest. Though, if I add such link into the `.ckan` file people won't be able to browse previous versions.
I'm fine to post ckan updates on every release. Just curious :)
> KIS 1.2.9 release

- TacFuelBalancer/TacFuelBalancer-v2.5.3.ckan
For KSP V1.1.2
I added this to Space Dock but it hasn't shown up in CKAN.  Do I need to make a NetKAN?  If you have the time let me know.  http://spacedock.info/mod/640/TacFuelBalancer
Thank you!
> Publishing TacFuelBallancer 2.5.3

- ProceduralDynamics/ProceduralDynamics-0.9.3.ckan
No idea how many users we have still running 0.90. I suspect not many, and this will fix up the "Max KSP" in the GUI
> ProceduralDynamics-0.9.3 - lose the "v"

- AdvancedJetEngine/AdvancedJetEngine-1.6.4.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.6.8.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.6.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.7a.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.0.2.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.0.3.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.0.4.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.2.0.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.2.1.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.3.0.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.4.0.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.4.1.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.5.1.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.5.2.ckan
- AdvancedJetEngine/AdvancedJetEngine-2.5.ckan
- AdvancedJetEngine/AdvancedJetEngine-v2.5.4.ckan
- AdvancedJetEngine/AdvancedJetEngine-v2.6.1.ckan
- AdvancedJetEngine/AdvancedJetEngine-v2.6.ckan
- AdvancedJetEngine/AdvancedJetEngine-v2.7.ckan
As mentioned in KSP-CKAN/NetKAN#4157, seems like AJE's license was incorrectly specified from the beginning as LGPL-2.1 when it has always been LGPL-2.0.
> Update AJE license to LGPL-2.0

- RCSBuildAid/RCSBuildAid-v0.7.8.ckan
v0.7.7-14 has been removed from Curseforge and the new v0.8 is the only KSP 1.1 compatible release.
Hmmph. Didn't expect that to turn into a rename.
> Clean up old RCSBuildAid releases

- ModularFlightIntegrator/ModularFlightIntegrator-1.1.3.0.ckan
1.1.3 is not compatible with all 1.1 releases.
> ModularFlightIntegrator Compatibility fix

- VenStockRevamp/VenStockRevamp-v1.9.2.ckan
Ref KSP-CKAN/NetKAN#4336
@NathanKell, can you confirm that 1.9.2 should top out at KSP 1.1.1, or is it ok for 1.1.2 as well?
> VSR Restrict KSP versions

- WiderContractsApp/WiderContractsApp-1.3.4.ckan
This final release does nothing other than display a message saying it is obsolete.
Ref KSP-CKAN/CKAN#1805
Waiting on KSP-CKAN/NetKAN#4325 to be merged
> Mark WiderContractApp final release as obsolete

- KerbalKrashSystem/KerbalKrashSystem-1-0.3.2.ckan
- KerbalKrashSystem/KerbalKrashSystem-1-0.3.3.ckan
- KerbalKrashSystem/KerbalKrashSystem-1-0.3.4.ckan
- KerbalKrashSystem/KerbalKrashSystem-1-0.3.5.ckan
1:0.3.6 has been released with 1.1.3
1:0.3.1 has KSP 1.1.0
In between releases had KSP 1.1 on Curse
Setting in between releases to 1.1.0 - 1.1.2
> Restrict old KerbalKrashSystem release KSP versions

- DeadlyReentry/DeadlyReentry-v7.4.6.frozen
Ref KSP-CKAN/CKAN#1822
7.4.5.1 is now the highest available DeadlyReentry for KSP 1.1.2
> Deadly Reentry 7.4.6 is 404

- repositories.json
It was useful for a while, but as was stated from the start, this repository is not being maintained, and is now almost completely useless.
> Remove Fwiffos Dev Repository

- RadialHeatShields/RadialHeatShields-0.9.1.4.1.ckan
- RadialHeatShields/RadialHeatShields-1.0.ckan
Mod removed from Spacedock. No further development expected. The last two releases are on GitHub, so users of KSP 1.0.5 can grab them from there if they have some requirement.
> Move RadialHeatShields downloads to GitHub

- ChopShop/ChopShop-0.10.0.2.ckan
- ChopShop/ChopShop-0.10.0.3.ckan
- ChopShop/ChopShop-0.10.1.1.ckan
- ChopShop/ChopShop-0.10.1.2.ckan
- ChopShop/ChopShop-0.10.1.ckan
- ChopShop/ChopShop-1.10.0.2.ckan
The misnaming of ChopShop 0.10.0.2 as 1.10.0.2 caused the most recent version (0.10.0.3) for KSP 1.1.3 not to be picked up by NetKAN. It is renamed here to the correct version and adds a .ckan for 0.10.0.3. Since the download 0.10.0.2 is no longer available, ChopShop will not install for KSP 1.1.3. This pull request fixes these issues.
> Fixes ChopShop for KSP 1.1.3

- RealismOverhaul/RealismOverhaul-v10.1.0.ckan
- RealismOverhaul/RealismOverhaul-v10.6.0.ckan
- RealismOverhaul/RealismOverhaul-v10.9.0.ckan
- RealismOverhaul/RealismOverhaul-v10.9.1.ckan
- RealismOverhaul/RealismOverhaul-v10.9.2.ckan
- RealismOverhaul/RealismOverhaul-v11.2.0.ckan
- RealismOverhaul/RealismOverhaul-v6.1.2c.ckan
- RealismOverhaul/RealismOverhaul-v7.0.0.ckan
- RealismOverhaul/RealismOverhaul-v7.0.0a.ckan
- RealismOverhaul/RealismOverhaul-v7.0.0b.ckan
- RealismOverhaul/RealismOverhaul-v7.0.1.ckan
- RealismOverhaul/RealismOverhaul-v7.0.2.ckan
- RealismOverhaul/RealismOverhaul-v7.0.3.ckan
- RealismOverhaul/RealismOverhaul-v7.0.4.ckan
- RealismOverhaul/RealismOverhaul-v7.0.5.ckan
- RealismOverhaul/RealismOverhaul-v7.0.6.ckan
- RealismOverhaul/RealismOverhaul-v7.0.7.ckan
- RealismOverhaul/RealismOverhaul-v8.0.0.ckan
- RealismOverhaul/RealismOverhaul-v8.0.1.ckan
- RealismOverhaul/RealismOverhaul-v8.1.0.ckan
- RealismOverhaul/RealismOverhaul-v8.1.1.ckan
- RealismOverhaul/RealismOverhaul-v8.2.0.ckan
- RealismOverhaul/RealismOverhaul-v8.3.0.ckan
- RealismOverhaul/RealismOverhaul-v8.3.1.ckan
- RealismOverhaul/RealismOverhaul-v8.4.0.ckan
- RealismOverhaul/RealismOverhaul-v8.4.1.ckan
* Added missing versions v7.0.0, v10.1.0 and v10.6.0
* Added missing provides `TestFlightConfig` for v10.9.0 to v10.9.2
* Reformated `.ckan` file of v7.0.0a
* Removed duplicate versions (git sees them as renamed)
* Removed all trailing zeros for `0.25` and `0.90`
> TACLS Configs - 2. Fix RealismOverhaul

- FerramAerospaceResearch/FerramAerospaceResearch-3-0.15.8.ckan
There was an error in the .version file used to create the current metadata for FAR v0.15.8.  FAR v0.15.8 should be compatible with KSP 1.2.0, 1.2.1 and 1.2.2; this change should address that.
> Update version error for FAR v0.15.8

- KerbalEngineerRedux/KerbalEngineerRedux-1.1.3.0.ckan
Zip file for this release was updated and reloaded, we are stuck with a failing cached copy, it seems.
> Add KerbalEngineerRedux 1.1.3.0

- FerramAerospaceResearch/FerramAerospaceResearch-3-0.15.9.ckan
For some reason, it says that FAR v0.15.9 is for KSP 1.2.  It is not; it is for KSP 1.3.
> Fix FAR v0.15.9 KSP compatibility

- Astrogator/Astrogator-v0.1.1.ckan
- Astrogator/Astrogator-v0.2.0.ckan
- Astrogator/Astrogator-v0.3.0.ckan
- Astrogator/Astrogator-v0.3.1.ckan
- Astrogator/Astrogator-v0.4.0.ckan
- Astrogator/Astrogator-v0.5.0.ckan
- Astrogator/Astrogator-v0.5.1.ckan
- Astrogator/Astrogator-v0.5.2.ckan
- Astrogator/Astrogator-v0.6.0.ckan
- Astrogator/Astrogator-v0.6.1.ckan
- Astrogator/Astrogator-v0.6.2.ckan
Just in case anyone still has the 1.2.9 prerelease, this marks the 1.2 editions of Astrogator as incompatible with it. Previously it would have been possible to install them with CKAN and crash KSP, since 1.2.9 made backwards incompatible changes with 1.2.2.
> 1.2 versions incompatible with 1.2.9 prerelease

- HotSpot/HotSpot-0.2.0.ckan
- HotSpot/HotSpot-0.3.0.ckan
- HotSpot/HotSpot-0.4.1.ckan
- HotSpot/HotSpot-0.4.2.ckan
- HotSpot/HotSpot-0.4.3.ckan
- HotSpot/HotSpot-0.4.4.ckan
- PlaneMode/PlaneMode-0.3.0.ckan
- PlaneMode/PlaneMode-0.4.0.ckan
- PlaneMode/PlaneMode-0.4.1.ckan
- PlaneMode/PlaneMode-1.0.0.ckan
- PlaneMode/PlaneMode-1.1.0.ckan
- PlaneMode/PlaneMode-1.2.0.ckan
Latest releases of PlaneMode and HotSpot have an author of "Dwayne Bent."
Earliest releases are by "dbb".
I think it's fair to infer this is the same person. This PR replaces the older name with the newer name in old metadata to make author searches easier.
> Change author dbb to Dwayne Bent

- OuterPlanetsMod/OuterPlanetsMod-1-2.1.ckan
This version of OPM was released to work on KSP 1.2, but the ksp_version_min is listed as 1.1.2, which is currently causing CKAN to try to install this version on KSP 1.1.3, which fortunately fails because the Kopernicus dependency specifies a min_version of 1.2.1-1, which is only compatible with KSP 1.2.1.
https://forum.kerbalspaceprogram.com/index.php?/topic/93999-121-outer-planets-mod-21-biome-overhaul-more-biomes-more-interesting-names-better-looking-etc-17-nov/&do=findComment&comment=2853267
This pull request fixes the transposed digits.
> Fix ksp_version_min for OPM 2.1

- AlternisKerbolRekerjiggered/AlternisKerbolRekerjiggered-1.4.1.ckan
- AlternisKerbolRekerjiggered/AlternisKerbolRekerjiggered-1.5.1.ckan
Most versions of this mod were released with an X.Y.Z version format, but two old versions are vX.Y.Z or Version_X.Y.Z instead. This PR makes them consistent by removing the extra prefixes from the old versions.
This is one of the problems pointed out in https://github.com/KSP-CKAN/NetKAN/issues/5945.
> AlternisKerbolRekerjiggered, clean up old versions with bad version formats

- NewTantares/NewTantares-v6.0.ckan
- NewTantares/NewTantares-v7.0.ckan
v7.0 and v6.0 are explicitly stated to be 1.3 compatible:
https://github.com/Tantares/Tantares/releases
v8.0 already fixed by updating the netkan.
> Update KSP versions on old versions of NewTantares

- KSPInterstellarExtended/KSPInterstellarExtended-1.15.4.ckan
KSPInterstellarExtended 1.15.3 was removed from SpaceDock and effectively replaced by 1.15.4 as the latest release for KSP 1.3.0. However, the CKAN index still has 1.15.3, so users get failed download messages even with an up to date registry as per KSP-CKAN/CKAN#2196. This pull request adds 1.15.4.
> Index KSPIE 1.15.4 (fixes KSP-CKAN/CKAN#2196)

- GPPCloudsHighRes/GPPCloudsHighRes-1.5.3.ckan
- GPPCloudsLowRes/GPPCloudsLowRes-1.5.3.ckan
- GPPSecondary/GPPSecondary-1.5.3.ckan
These mods were installing version 1.5.88 while CKAN said 1.5.3.
This pull request restores the actual 1.5.3 versions from the previous commits.
> Restore 1.5.3 versions of GPP side mods

- NewTantaresLV/NewTantaresLV-v4.0.ckan
- NewTantaresLV/NewTantaresLV-v5.1.ckan
This mod supported KSP 1.3 in its 4.0 version and KSP 1.3.1 in 5.0 and 5.1:
https://github.com/Tantares/TantaresLV/releases
The netkan is updated in https://github.com/KSP-CKAN/NetKAN/pull/6095 to fix the latest version, and this pull request handles the older versions.
> Fix NewTantaresLV versions

- ASETAvionics/ASETAvionics-1.0.ckan
- ASETProps/ASETProps-1.3.ckan
- Astrogator/Astrogator-v0.1.1.ckan
- Astrogator/Astrogator-v0.2.0.ckan
- Astrogator/Astrogator-v0.3.0.ckan
- Astrogator/Astrogator-v0.3.1.ckan
- Astrogator/Astrogator-v0.4.0.ckan
- Astrogator/Astrogator-v0.5.0.ckan
- Astrogator/Astrogator-v0.5.1.ckan
- Astrogator/Astrogator-v0.5.2.ckan
- Astrogator/Astrogator-v0.6.0.ckan
- Astrogator/Astrogator-v0.6.1.ckan
- Astrogator/Astrogator-v0.6.2.ckan
ASETAvionics 1.0 and ASETProps 1.3 were using dropbox links that are now broken, but they're still on archive.org. Also their homepage URLs weren't valid, even though the forum threads didn't move.
Fixes KSP-CKAN/NetKAN#6114.
> Point old ASET downloads to archive.org

- DoubleDouble/DoubleDouble-1.0.ckan
- DoubleDouble/DoubleDouble-v1.1.ckan
- SamBelangerFlags/SamBelangerFlags-1-v1.0.ckan
- SamBelangerFlags/SamBelangerFlags-1.4.9.1.ckan
These mods have been removed from GitHub and SpaceDock.
This pull request updates them to download from the archive.org locations.
> Get SamBelanger mods from archive.org

- CactEyeTelescopesContinued/CactEyeTelescopesContinued-0.6.10.frozen
- CactEyeTelescopesContinued/CactEyeTelescopesContinued-v0.6.10.frozen
- CactEyeTelescopesContinued/CactEyeTelescopesContinued-v0.6.11.frozen
- CactEyeTelescopesContinued/CactEyeTelescopesContinued-v0.6.8.frozen
- CactEyeTelescopesContinued/CactEyeTelescopesContinued-v7.1.0.frozen
This mod was frozen in #1198 and comments were added to the CKAN-meta files, but a comma was missing between the JSON properties. Now it's added.
Fixes KSP-CKAN/CKAN#2261.
> Missing commas in frozen CactEyeTelescopesContinued files

- GPP/GPP-1-1.6.1.1.ckan
- GPP/GPP-1.6.1.1.ckan
- GPPCloudsHighRes/GPPCloudsHighRes-1.6.1.1.ckan
- GPPCloudsLowRes/GPPCloudsLowRes-1.6.1.1.ckan
- GPPSecondary/GPPSecondary-1.6.1.1.ckan
GPP updated and had to re-upload, and the netkan bot is stuck on the original file.
This PR sets the hashes to match the new download. The bot will blow these changes away when it runs, but we can re-apply them after that. This will allow people to update GPP while we figure out the bot stuff.
> Fix GPP hashes

- ThroughTheEyesOfaKerbal/ThroughTheEyesOfaKerbal-2.0.0.2.ckan
KSP 1.4 has wiped the slate clean; with an unupdated registry, all you can see are mods that are compatible with all versions.
This mod jumped out at me because the Max KSP Version column shows as 1.3.1, but it still shows up to install with 1.4. Turns out one of the older versions has no version specified. I checked the release announcement for that version, and it says it's for 1.3, so this pull request sets it to that version.
> Set game version to 1.3 for ThroughTheEyes 2.0.0.2

- DeadlyReentry/DeadlyReentry-v7.6.1.ckan
An old release of DeadlyReentry seems to have been updated in-place as we try to handle now in KSP-CKAN/CKAN#2337, but that method only fixes the issue when it happens to the most recent release, since netkan only checks the most recent release.
This pull request updates the download size and hashes to match the current download.
Fixes https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1240-bruce/&do=findComment&comment=3317213
> Update hashes for DRE for KSP 1.3.0

- KerbalXMod/KerbalXMod-0.1.2.ckan
- KerbalXMod/KerbalXMod-0.1.3.ckan
>katateochi  2,892
>Started conversation: Saturday at 10:09 PM
>
>Hey Politas!
>
>Wondering if you could sort something out for me. I've updated the KerbalX mod to work with KSP 1.4.0, but that version is incompatible with KSP 1.3.x. But I've just heard from someone that CKAN updated the KXmod in their 1.3.1 install to the latest version. 
>
>Can you make it so that the 0.1.4 version of the mod is only for KSP 1.4.0, and any older versions of KSP should stick with the 0.1.3 version of the mod?
>KSP <= 1.3.1 - https://github.com/Sujimichi/KerbalXMod/releases/tag/0.1.3
>KSP == 1.4.0 - https://github.com/Sujimichi/KerbalXMod/releases/tag/0.1.4
>
>Thanks! 
>
>Kat
> Change KerbalXMod compatibility as per forum PM

- ShowFPS/ShowFPS-v1.1.ckan
This mod has not been updated in a long time, and it's marked as compatible with KSP 1.1 and later even though there's a comment on its Curse page saying it doesn't work with 1.2.0.
Now it's 1.1-only.
Fixes https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1240-bruce/&do=findComment&comment=3325096
> Limit ShowFPS to game version 1.1

- LaserDist/LaserDist-v0.9.1.ckan
- LaserDist/LaserDist-v0.9.2.ckan
- LaserDist/LaserDist-v0.9.3.ckan
- LaserDist/LaserDist-v0.9.4.ckan
This mod is marked as compatible with KSP 1.1.0–99.99.99, but that doesn't appear to be accurate. The forum thread regularly features reports of crashes after new game versions are released, followed by new recompiled releases (e.g., the latest release is entitled, "Recompile for KSP 1.3").
This pull request updates the metadata for the old versions to reflect their apparent actual compatibility based on the descriptions in the release listing of the GitHub repo. It also adds an old version, v0.9.3, which was skipped because the download was done via a hyperlink in the description rather than a proper asset.
This will help users of KSP-AVC, CKAN, and any other tools that parse .version files to avoid installing incompatible mod versions.
Current release to be fixed by …
> Fix game versions for old LaserDist releases

- CraftManager/CraftManager-1.0.1.ckan
CraftManager has two release streams; 1.0.X is for KSP 1.3, and 1.1.X is for KSP 1.4.
KSP-CKAN/NetKAN#6528 added the current 1.1.X stream with an override for the 1.0.X stream.
This pull request adds the most recent 1.0.X version.
Closes Sujimichi/CraftManager#2.
> Add old CraftManger version

- CraftManager/CraftManager-1.0.2.ckan
CraftManager 1.0.2 and 1.1.2 were uploaded in the same pass of the bot, so only 1.1.2 got indexed.
This pull request adds 1.0.2.
> Add CraftManager 1.0.2

- KerbalKonstructs/KerbalKonstructs-1.3.9.12.ckan
This is one of those mods that puts out several releases at once for different versions, so the bot misses some of them.
Fixes KSP-CKAN/NetKAN#6574.
> Add skipped KerbalKonstructs release

- ProceduralFairings/ProceduralFairings-1.4.3.1.ckan
- ProceduralFairings/ProceduralFairings-v5.0.ckan
Before ProceduralFairings had a version file, two of its releases for 1.4.3 were marked as compatible with 1.3. This pull request updates them.
Closes #1348, which was deleting one of these instead.
> Fix old versions for ProceduralFairings

- SASAG/SASAG-1.0.0.0.ckan
This version was incorrectly indexed for KSP 1.2.2, should be 1.4.2.
> Fix version for SASAG 1.0.0.0

- AnimatedAttachment/AnimatedAttachment-v1.2.2.ckan
This version was entered incorrectly [as per the author](https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1251-broglio/&do=findComment&comment=3421531); it should start with `v1` instead of `v.1`.
This pull request renames the file and updates the version in the metadata.
> Remove extra period / dot / full stop from version

- DecoupleWithControl/DecoupleWithControl-v1.2.1.ckan
This mod's 1.2.1 version was entered on GitHub as v.1.2.1. The dot after the 'v' is causing CKAN to consider it newer than later versions.
This pull request removes the extra dot.
Fixes KSP-CKAN/CKAN#2479.
> Remove extra dot from DecoupleWithControl version

- LaserDist/LaserDist-v1.0.1.ckan
There's a new LaserDist release, which means the previous current version is no longer covered by Dunbaratu/LaserDist#23 or KSP-CKAN/CKAN-meta#1338. This pull request fixes it.
> Fix old LaserDist version

- InterstellarFuelSwitch-Core/InterstellarFuelSwitch-Core-3.6.15.1.ckan
This download was replaced on SpaceDock.
Now the size and hashes are updated. This will work because there's a already newer version to distract the bot.
Fixes KSP-CKAN/CKAN#2568.
> Update hashes for InterstellarFuelSwitch-Core

- NearFutureProps/NearFutureProps-1-0.3.4.ckan
NearFutureProps 0.3.4 was released as 0.4.4:
[![image](https://user-images.githubusercontent.com/1559108/48396367-130f5680-e712-11e8-838b-a166e7143e8d.png)](https://github.com/ChrisAdderley/NearFutureProps/releases)
Now the metadata is fixed.
Fixes KSP-CKAN/NetKAN#6840.
> Fix faulty NFP 0.3.4 version

- SXTContinued/SXTContinued-1-0.3.23.4.ckan
- SXTContinued/SXTContinued-1-0.3.23.7.ckan
Two old versions of SXTContinued are out of order:
Now these entries are updated to their intended versions:
| Old | New |
| --- | --- |
| 1:3.2.23.4 | 1:0.3.23.4 |
| 1:03.23.7 | 1:0.3.23.7 |
Fixes KSP-CKAN/CKAN#2581.
@linuxgurugamer, does this look OK?
> Fix old SXTContinued versions

- SolverEngines/SolverEngines-v3.7.2.ckan
The bot thinks SolverEngines v3.7.1 is the current version even though v3.7.2 exists, because the GitHub API is returning them out of order:
https://api.github.com/repos/KSP-RO/SolverEngines/releases
Now the missing version is indexed.
Fixes KSP-CKAN/NetKAN#6935.
> Index SolverEngines v3.7.2

- Trajectories/Trajectories-v2.2.0.ckan
Trajectories has some weird version numbers lately that are breaking things.
Now that top one is changed to just "v2.2.0".
> Fix weird Trajectories version number

- ScienceSituationInfo/ScienceSituationInfo-1-1.3.3.ckan
This mod wasn't indexed when this version was uploaded. Now it's added for completeness.
Part of the fix to KSP-CKAN/NetKAN#6980.
> Add missing version of adopted ScienceSituationInfo

- PicoPort/PicoPort-0.1.4.ckan
An old version of PicoPort was uploaded with a 'v' prefix, which none of the other versions have. This pull request removes it.
Fixes KSP-CKAN/NetKAN#6988
> Update and rename PicoPort-v0.1.4.ckan to PicoPort-0.1.4.ckan

- B9-PWings-Fork/B9-PWings-Fork-1-0.50.ckan
This mod mostly doesn't have 'v' prefixes in versions, but one version does, which is messing things up. Now it's fixed.
Fixes https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1254-kennedy/&do=findComment&comment=3537829
> Clean up old version of pwings

- UniversalStorage2/UniversalStorage2-1.3.1.2.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.3.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.4.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.5.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.6.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.7.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.8.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.9.ckan
- UniversalStorage2/UniversalStorage2-1.4.5.2.ckan
- UniversalStorage2/UniversalStorage2-1.4.5.3.ckan
- UniversalStorage2/UniversalStorage2-1.5.1.5.ckan
- UniversalStorage2/UniversalStorage2-1.5.1.6.ckan
- UniversalStorage2/UniversalStorage2-1.5.1.7.ckan
- UniversalStorage2/UniversalStorage2-1.5.1.8.ckan
Some versions of UniversalStorage2 are missing (partly due to KSP-SpaceDock/SpaceDock#192), and others have too narrow game compatibility.
Now KSP-CKAN/CKAN#2681's `--backfill` option is used to regenerate all versions of UniversalStorage2.
Some old versions are newly added:
- 1.3.1.2
- 1.3.1.3
- 1.3.1.4
- 1.3.1.8
- 1.3.1.9
- 1.4.5.2
- 1.4.5.3
Existing versions have their `resources.x_screenshot` updated and game versions revised based on the .version files (since a `$vref` has been added to the netkan in KSP-CKAN/NetKAN#7005):
- 1.3.1.5
- 1.3.1.6
- 1.3.1.7
- 1.4.5.4
- 1.5.1.5
- 1.5.1.6
- 1.5.1.7
- 1.5.1.8
Fixes KSP-CKAN/NetKAN#7003.
> Backfill UniversalStorage2

- ToolbarController/ToolbarController-0.1.3.1.ckan
- ToolbarController/ToolbarController-0.1.3.4.ckan
- ToolbarController/ToolbarController-0.1.3.5.ckan
- ToolbarController/ToolbarController-0.1.4.1.ckan
- ToolbarController/ToolbarController-0.1.4.2.ckan
- ToolbarController/ToolbarController-0.1.4.ckan
- ToolbarController/ToolbarController-1-0.1.4.3.ckan
- ToolbarController/ToolbarController-1-0.1.4.4.ckan
- ToolbarController/ToolbarController-1-0.1.4.5.ckan
- ToolbarController/ToolbarController-1-0.1.4.6.ckan
- ToolbarController/ToolbarController-1-0.1.4.7.ckan
Several old versions of ToolbarController are indexed as compatible with all game versions, while the later ones have specific game versions:
This means that anytime KSP updates, users end up installing ToolbarController 0.1.4.7 until there's a new release or a metadata update.
Now those old versions are marked as compatible with KSP 1.3.1, which was the current game version when they were released.
> Set compatibility for old ToolbarController versions

- IR-Model-Rework-Core/IR-Model-Rework-Core-v01a.kerbalstuff
- IR-Model-Rework-Core/IR-Model-Rework-Core-v01b.kerbalstuff
- IR-Model-Rework-Expansion/IR-Model-Rework-Expansion-v01a.kerbalstuff
- IR-Model-Rework-Expansion/IR-Model-Rework-Expansion-v01b.kerbalstuff
This is the CKAN-meta correlate of KSP-CKAN/NetKAN#7058.
Some modules have `version_min` instead of `min_version` in their relationships. The live data was all fixed by the commit hook of the above PR, but there are a few old `.kerbalstuff` files that still have the problem. This has no functional impact, but it might confuse metadata maintainers looking through files to see how to do things.
Now they're cleaned up.
> Fix bad min version syntax

- ScottManleyHeadPack/ScottManleyHeadPack-1.0.0.ckan
The version of the Scott Manley Head Pack for KSP 1.3 worked equally well for SigmaReplacements-Heads or TextureReplacerReplaced, but at the time there was no way to express that directly, so one of them is a suggestion and the other is a recommendation. This could make it easy to install both or neither, which would result in the mod not working.
Now this module is updated to have an `any_of` dependency on these two mods. This will prompt the user to choose one of them at install.
The `spec_version` is updated to v1.26, which will make this version disappear for anyone not using the pre-release, but probably no one will miss it.
Sort of related to KSP-CKAN/NetKAN#7027 in that this is a new feature in 1.26, but strictly speaking that issue is focused on `replaced_by`.
> Use any_of depends for old ScottManleyHeadPack version

- Scatterer-config/Scatterer-config-2-v0.0520.ckan
- Scatterer-config/Scatterer-config-2-v0.0530.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0520.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0530.ckan
- Scatterer/Scatterer-2-v0.0520.ckan
- Scatterer/Scatterer-2-v0.0530.ckan
Scatterer had some non-consecutive versions recently:
Scatterer seems to be following real-number style versions rather than semantic versioning style.
Now these each have `0` added to the end so they sort in the right order.
> Make Scatterer versions consecutive

- ABCORS/ABCORS-0.5.0.2.ckan
ABCORS 0.5.0.3 has invalid hashes and file size.
ABCORS 0.5.0.2 is missing.
Closes https://github.com/KSP-CKAN/NetKAN/issues/7124
> Add ABCORS 0.5.0.2 and update 0.5.0.3

- TextureReplacerReplaced/TextureReplacerReplaced-V0.5.3.ckan
See KSP-CKAN/NetKAN#7149 for details; TextureReplacerReplaced should provide TextureReplacer, and one version of it (still) doesn't.
Fixes another part of KSP-CKAN/CKAN#2738.
> Make old TRR provide TR

- InnerLock/InnerLock-0.0.4_ksp-1.3.1.ckan
- InnerLock/InnerLock-0.0.4_ksp-1.5.1.ckan
@DasSkelett pointed out that #1434 added two .ckan files to the root folder of the repo. Now they're moved to the InnerLock folder.
KSP-CKAN/NetKAN#7212 added an install stanza to handle a missing folder and added support for InnerLock's version file. Now these changes are applied to the older versions as well.
> Update old InnerLock versions

- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.0.ckan
- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.10.ckan
- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.3.ckan
- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.4.ckan
- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.5.ckan
- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.6.ckan
- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.7.ckan
- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.8.ckan
- KerbalJointReinforcementNext/KerbalJointReinforcementNext-v4.0.9.ckan
See KSP-CKAN/NetKAN#7221; KJRNext providing KJR has caused problems, so we're removing that.
This pull request covers already indexed versions.
> Remove KJR provides from old versions of KJRNext

- ModularFuelTanks/ModularFuelTanks-5.11.1.ckan
- ModularFuelTanks/ModularFuelTanks-5.12.0.ckan
- ModularFuelTanks/ModularFuelTanks-5.12.2.ckan
These are the release announcements for the last eight versions of [ModularFuelTanks](https://forum.kerbalspaceprogram.com/index.php?/topic/58235-*):
> I have released MFT 5.10.0 for KSP 1.3.1. Links in the first post, changes in the second.
> I have released MFT 5.11.0 for KSP 1.4.[0-1]. Links in the first post, changes in the second.
> I've released MT 5.11.1 for KSP 1.5.1. It's really just a version check tweak and recompile: it should be compatible with 1.4 still (I did my initial testing with 1.4's MFT).
> I have released version 5.11.2 of ModularFuelTanks. This fixes the delta-v indicator for ships with edited tanks (especially for LV-N).
> I have released version 5.12.0 of ModularFuelTanks, updating MFT for KSP 1.6's delta-v calculation.
> And 5.12.1 with the fix for the broken …
> Clean up old ModularFuelTank versions

- KIS/KIS-1.19.ckan
- KIS/KIS-1.20.ckan
- KIS/KIS-1.21.ckan
See https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1260-baikonur/&do=findComment&comment=3613097
Some recent versions of KIS are the victims of unexpected stock API changes. They don't work on KSP 1.7.1, but their version files and CKAN metadata announce compatibility with 1.7.0 through 1.7.99.
Now they're marked as 1.7.0 only.
> Limit three versions of KIS to KSP 1.7.0

- Kopernicus/Kopernicus-2-release-1.3.1-23.ckan
- Kopernicus/Kopernicus-2-release-1.4.5-14.ckan
- Kopernicus/Kopernicus-2-release-1.5.1-9.ckan
- Kopernicus/Kopernicus-2-release-1.6.1-7.ckan
- Kopernicus/Kopernicus-2-release-1.7.1-4.ckan
Successor to #1456. New Kopernicus release today.
https://forum.kerbalspaceprogram.com/index.php?/topic/181547-171-1-backports-kopernicus-kittopiatech/&do=findComment&comment=3613945
The main one for 1.7.1 will be handled by the bot, but the others won't be without KSP-CKAN/NetKAN-bot#91. So for now we do it manually via
```sh
netkan.exe NetKAN/NetKAN/Backports/Kopernicus.netkan --releases 8
```
Several intermediate versions are skipped because they had bugs that were immediately reported on the forum. This is also true of 1.7.1-2, which the bot just indexed, so 1.7.1-4 is added as well to reduce the number of people using a broken version.
ckan compat add 1.6
> Add new batch of Kopernicus backports

- Kerbalism/Kerbalism-2.1.2.ckan
This reverts commit ccc774db21e76b40df919fe907861c730b54e5e8.
Kerbalism 2.1.2 had KSP-CKAN/NetKAN#7228 applied to it, but those changes were for 3.0. Now they're reverted.
> Revert " "NetKAN generated mods - Kerbalism-2.1.2""

- Kopernicus/Kopernicus-2-release-1.3.1-24.ckan
- Kopernicus/Kopernicus-2-release-1.4.5-15.ckan
- Kopernicus/Kopernicus-2-release-1.5.1-10.ckan
- Kopernicus/Kopernicus-2-release-1.6.1-8.ckan
Successor to #1460.
These fix the issue of Kopernicus freezing with .bin files in GameData that weren't intended for it.
> More Kopernicus backports

- NewTantares/NewTantares-v16.0.ckan
- NewTantares/NewTantares-v17.0.ckan
- NewTantares/NewTantares-v17.1.ckan
This mod's game versions are hard coded in the netkan and were 4 versions out of date.
KSP-CKAN/NetKAN#7246 updated the current version and enabled staging.
This pull request fixes the older verisons.
> Fix NewTantares game versions

- AllYAll/AllYAll-1-0.11.17.1.ckan
- AllYAll/AllYAll-1-0.11.17.ckan
See KSP-CKAN/NetKAN#7260; this module needs an epoch to compensate for an out of order release.
> Epoch AllYAll

- KSPInterstellarExtended/KSPInterstellarExtended-1.21.10.2.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.10.3.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.8.1.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.8.2.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.8.3.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.8.4.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.9.0.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.9.1.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.9.2.ckan
The SpaceDock new upload web hooks is working, but it's missing versions, presumably due to timing.
This pull request indexes a few missing releases of KSPInterstellarExtended. Localization data is added to older versions that weren't missed, so we don't have a weird disappearance of localizations as the version numbers increase.
ckan compat add 1.7
> Backfill missing KSPIE versions, add localizations

- StationScienceContinued/StationScienceContinued-v2.5.2.ckan
This module released with incorrect data in its .version file. It was built for KSP 1.6, but the version file says 1.4.
Now it's fixed.
Fixes KSP-CKAN/NetKAN#7262.
> Fix StationScienceContinued compatibility

- KSPInterstellarExtended/KSPInterstellarExtended-1.21.11.3.ckan
- KSPInterstellarExtended/KSPInterstellarExtended-1.21.11.4.ckan
This module uploaded a set of releases between KSP-CKAN/CKAN#2788 and KSP-CKAN/CKAN#2808, so the ones for game versions after 1.4.5 got rejected. Now they're indexed.
ckan compat add 1.7
> Backfill missed KSPIE versions

- AstronomersVisualPack/AstronomersVisualPack-2-3.7.0.0.ckan
- AstronomersVisualPack/AstronomersVisualPack-2-3.7.1.0.ckan
- AstronomersVisualPack/AstronomersVisualPack-2-3.7.2.0.ckan
- AstronomersVisualPack/AstronomersVisualPack-2-3.7.3.0.ckan
- AstronomersVisualPack/AstronomersVisualPack-2-3.7.4.0.ckan
- AstronomersVisualPack/AstronomersVisualPack-2-3.8.0.0.ckan
- AstronomersVisualPack/AstronomersVisualPack-2-3.8.1.0.ckan
See KSP-CKAN/NetKAN#7286; this module has an old version listed as its newest due to two separate "epoch events". Now the actually-newer versions have their epochs increased.
> Fix old AVP epochs

- LaserDist/LaserDist-v1.1.0.ckan
See KSP-CKAN/NetKAN#7324, this version of LaserDist has an incorrect min game version.
Now it's set based on the .version file.
> Fix min version of old LaserDist version

- MechJebForAll/MechJebForAll-1.2.0.0.ckan
This mod has an old version that falsely claims far greater compatibility than later versions:
People on the forum thread started reporting problems on KSP 1.3, and that's when LGG's fork picks up, so I marked it 1.0 through 1.2.
https://forum.kerbalspaceprogram.com/index.php?/topic/75295-0235-mechjeb-and-engineer-for-all/
> Add game versions to old MechJebForAll

- KerbalKonstructs/KerbalKonstructs-1.7.3.0.ckan
This is the historical update for KSP-CKAN/NetKAN#7423.
> Add depends to old KerbalKonstructs version

- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.2.1.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.2.2.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.2.3a.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.2.5.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.2.5a.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.2.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.3.5.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.3.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.4.1.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.4.2.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.4.ckan
This mod had 8 versions uploaded to SpaceDock in 7 days, and somehow the webhooks missed them all.
Now they're added.
FYI to @HyperFunOriginal
> Backfill missed StockalikeRealismOverhaul versions

- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.5.1.ckan
- StockalikeRealismOverhaul/StockalikeRealismOverhaul-1.5.2.ckan
Our current webhook for SpaceDock seems to be not working.
Those two versions (among others) were missed .
> Add StockalikeRealismOverhaul 1.5.1 and 1.5.2

- OpenTree/OpenTree-2.3.ckan
- OpenTree/OpenTree-2.4.ckan
- OpenTree/OpenTree-2.5.ckan
Mod has been deleted from Spacedock: https://spacedock.info/mod/1623
Discontinuation confirmed on the forum: https://forum.kerbalspaceprogram.com/index.php?/topic/110365-131-opentree-v25-2512018/&do=findComment&comment=3456854
----
This PR changes the download URL to the respective ones on Archive.org for versions 2.3+.
The previous versions have already their download source set to Archive.org, since they've been hosted on KerbalStuff.
----
NetKAN freeze: https://github.com/KSP-CKAN/NetKAN/pull/7436
> Change download source for OpenTree

- Toolbar/Toolbar-1.7.17.15.ckan
One old version of Toolbar is marked as way more compatible than it really is:
Now it has a max version of 1.5.99, just like the versions immediately preceding it.
Fixes KSP-CKAN/NetKAN#7439.
> Fix historical Toolbar max version

- NavBallTextureExport/NavBallTextureExport-1.5.ckan
- TCShipInfo/TCShipInfo-0.3.ckan
- TCShipInfo/TCShipInfo-0.4.ckan
KSP-CKAN/NetKAN#4131 listed several mods without netkans that it thought should use the Unlicense. This was not correct, but investigating those mods nonetheless turned up a few changes that were needed.
- NavBallTextureExport
- License changed from public-domain to MIT
- Homepage fixed
- 1.5 added
- TCShipInfo homepage fixed
Fixes KSP-CKAN/NetKAN#4131.
> Fix license and links for old mods

- Scatterer-config/Scatterer-config-2-v0.0540.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0540.ckan
- Scatterer/Scatterer-2-v0.0540.ckan
There's a Scatterer for 1.6 and one for 1.8, but in between is a gap.
Apparently during the 1.7 period Scatterer folks were expected to use 0.0540. Now the metadata reflects that.
> Mark Scatterer 0.0540 as compatible with KSP 1.6-1.7

- VenStockRevamp-Core/VenStockRevamp-Core-v1.12.0.ckan
- VenStockRevamp-Core/VenStockRevamp-Core-v1.13.0.ckan
- VenStockRevamp-NewParts/VenStockRevamp-NewParts-v1.12.0.ckan
- VenStockRevamp-NewParts/VenStockRevamp-NewParts-v1.13.0.ckan
- VenStockRevamp/VenStockRevamp-v1.12.0.ckan
- VenStockRevamp/VenStockRevamp-v1.13.0.ckan
In KSP-CKAN/NetKAN#7500, VensRevamp is switched to a new fork and split into pieces that conflict with ReStock and those that don't.
There are two backports with earlier versions. This pull request indexes them.
> Backports for VensRevamp new fork

- JNSQ/JNSQ-0.8.1.ckan
- JNSQ/JNSQ-0.8.5.ckan
@linuxgurugamer and @yalov noted on the JNSQ forum thread that if you install the latest JNSQ, an *older* version of JNSQ is offered as an option for satisfying certain dependencies.
https://forum.kerbalspaceprogram.com/index.php?/topic/184880-17x-jnsq-086-13-nov-2019/&do=findComment&comment=3704814
https://forum.kerbalspaceprogram.com/index.php?/topic/184880-17x-jnsq-086-13-nov-2019/&do=findComment&comment=3714954
Older versions of JNSQ provide DistantObject-config and PlanetShine-Config, and the latest version doesn't. @Galileo88 indicated that the provides was a mistake for PlanetShine because the default configs are needed:
https://forum.kerbalspaceprogram.com/index.php?/topic/184880-17x-jnsq-086-13-nov-2019/&do=findComment&comment=3704816
Here he states that DistantObject "can …
> Unprovide configs for historical JNSQs

- OpenResourceSystem/OpenResourceSystem-1.4.2.ckan
There's an old .ckan with no .netkan claiming compatibility only with KSP 0.25. It's a dependency for a mod that failed installation in KSP-CKAN/NetKAN#7544.
It was released on Sept 24, 2014:
- https://forum.kerbalspaceprogram.com/index.php?/topic/58673-open-resource-system-ors-mod-resource-api-version-142/&do=findComment&comment=1420958
But KSP 0.25 was released on Oct 7, 2014:
- https://wiki.kerbalspaceprogram.com/wiki/0.25
So the current version when this mod was released was actually 0.24.
> Fix OpenResourceSystem compatibility

- ProgressiveColonizationSystem/ProgressiveColonizationSystem-0.0.4.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v0.0.5.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v0.0.6.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v0.1.1.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v1.0.0.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v1.0.1.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v1.0.2.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v1.0.3.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v1.0.4.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v1.0.5.ckan
- ProgressiveColonizationSystem/ProgressiveColonizationSystem-v1.0.6.ckan
In KSP-CKAN/NetKAN#7547 we updated this mod's netkan's tags to fit the recommendations of the wiki:
https://github.com/KSP-CKAN/CKAN/wiki/Suggested-Tags
Now the historical versions are updated as well.
> Tags for historical ProgressiveColonizationSystem versions

- Mk1RPMInternal/Mk1RPMInternal-1-2.2.ckan
- Mk1RPMInternal/Mk1RPMInternal-2.11.ckan
- Mk1RPMInternal/Mk1RPMInternal-2.11b.ckan
- Mk1RPMInternal/Mk1RPMInternal-2.11c.ckan
I contacted RPM's new maintainer as part of KSP-CKAN/NetKAN#7608, and in the course of that conversation he discovered that Mk1RPMInternal should depend on RasterPropMonitor but only depends on RasterPropMonitor-Core currently, because it uses the RasterPropMonitorBasicMFD prop which is (erroneously) defined in RasterPropMonitor instead of RasterPropMonitor-Core.
While preparing this fix, I found that the 2.11 version doesn't depend on *either*. And the latest version needs to be epoched because 2.2 followed 2.11.
Now this is all fixed.
> Assorted fixes for Mk1RPMInternal

- ASETProps/ASETProps-1.4.ckan
- ASETProps/ASETProps-1.5.ckan
- CessnaStyleIVAcokpit/CessnaStyleIVAcokpit-2.0.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-1-1.3_Collectors_Edition.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-1-1.3_X.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-1-Chaka_Monkey_Evolution_1.3.1_X.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-1.1_BETA.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-2-Chaka_143.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-3-1.4.3a.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-Chaka_Monkey_Exploration_Systems_1.1.3.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-Chaka_Monkey_Exploration_Systems_1.2.2.A.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-Chaka_Monkey_Exploration_Systems_1.2.2.X.ckan
- ChakaMonkeyExplorationSystems/ChakaMonkeyExplorationSystems-Chaka_Monkey_Exploration_Systems_1.2.2.ckan
- FirespitterCore/FirespitterCore-v7.1.4.ckan
- MK12PodIVAReplacementbyASET/MK12PodIVAReplacementbyASET-1-0.2.ckan
- MK12PodIVAReplacementbyASET/MK12PodIVAReplacementbyASET-1-0.3.ckan
- MK12PodIVAReplacementbyASET/MK12PodIVAReplacementbyASET-1.1.3.ckan
- Super100ShootingStarCommandPod/Super100ShootingStarCommandPod-1.02.ckan
See KSP-CKAN/NetKAN#7610; these modules use RasterPropMonitorBasicMFD, which is provided by RasterPropMonitor, but they only depend on RasterPropMonitor-Core. Now they depend on RasterPropMonitor.
> Update RPM depends for historical modules

- Chatterer/Chatterer-0.9.97.ckan
A fix release of Chatterer got missed. It was uploaded to SpaceDock the same day as a subsequent version that *was* indexed, back in October, so it may have been due to close timing or the new bot's migration growing pains. Now it's added.
Fixes KSP-CKAN/NetKAN#7620.
> Index missing Chatterer version

- Chatterer/Chatterer-0.9.96.ckan
KSP-CKAN/NetKAN#7620 suggested that Chatterer 0.9.96 "throws a bunch of notifications about it being outdated on startup", but that could be KSP-AVC behaving normally. However, some folks on the forum thread indicated they had problems with it on KSP 1.7.3, and version 0.9.97 was specifically a recompile for KSP 1.7.3.
Confused, I asked the author whether this version should be installed on KSP 1.7.3, and he said no:
https://forum.kerbalspaceprogram.com/index.php?/topic/83290-18x-chatterer-v0998-moar-talking-23-oct-2019/&do=findComment&comment=3726176
> Limit Chatterer 0.9.96 to KSP 1.4-1.6

- GammaTextures/GammaTextures-2.0.0.0.1.ckan
- HazardTanksTextures/HazardTanksTextures-1.0.ckan
- MainSailorTextures-Complete/MainSailorTextures-Complete-2.0.0.0.1.ckan
- MainSailorTextures-Essentials/MainSailorTextures-Essentials-2.0.0.0.1.ckan
- MainSailorTextures-Fairings/MainSailorTextures-Fairings-2.0.0.0.1.ckan
- MainSailorTextures-Historical/MainSailorTextures-Historical-2.0.0.0.1.ckan
- MainSailorTextures-Theta/MainSailorTextures-Theta-2.0.0.0.1.ckan
- OffStage/OffStage-1.5.1.ckan
- PhoenixIndustriesFlags/PhoenixIndustriesFlags-2.1.ckan
- ProceduralParts-Textures-SaturnNova/ProceduralParts-Textures-SaturnNova-1.2.ckan
- SamBelangerFlags/SamBelangerFlags-1-v1.0.ckan
- Sarkomand/Sarkomand-v1.0.ckan
- StarTrekRebootUniformPack/StarTrekRebootUniformPack-1.00.ckan
- StructuralDisks/StructuralDisks-1.2.0.1.ckan
- TALSphericalToroidalPack/TALSphericalToroidalPack-3.12.ckan
- Taerobee/Taerobee-1-3.0.ckan
- UpgradesUIextensions/UpgradesUIextensions-1-1.5.0.2.ckan
- VensStylePPTextures/VensStylePPTextures-1.1.ckan
- World-Airforce-Insignia/World-Airforce-Insignia-v1.1.ckan
Successor to #1749. This should finish tagging frozen modules compatible with 1.7 and 1.8.
> Tag frozen modules, group 2

- KerbalOccupationColors/KerbalOccupationColors-v1.2.0.ckan
See KSP-CKAN/NetKAN#7630, the override for this netkan was deleting its own overridden ksp_version_min property. Now it's added back in.
> Set missing compatibility for old KOC version

- SpaceplaneCorrections/SpaceplaneCorrections-v0.12.ckan
- SpaceplaneCorrections/SpaceplaneCorrections-v0.14.1.ckan
- SpaceplaneCorrections/SpaceplaneCorrections-v0.14.ckan
- SpaceplaneCorrections/SpaceplaneCorrections-v0.15.ckan
- SpaceplaneCorrections/SpaceplaneCorrections-v0.17.ckan
- SpaceplaneCorrections/SpaceplaneCorrections-v0.18.ckan
In https://github.com/KSP-CKAN/NetKAN/issues/7672 it was requested to remove the one indexed version of SPPCC, which was a development release for SpaceplaneCorrections.
Instead of removing it, I switched the identifier to SpaceplaneCorrections and replace the broken dropbox download link with the archive.org archive.
This way the old version does not vanish, but it's now part of the SpaceplaneCorections versions.
I also gernerated netkans for the unindexed versions of SpaceplaneCorrections.
This was possible for all but one version, the v0.16, because the zip has no common root folder.
(To be able to do this I had to patch netkan.exe to have an option to skip releases. I wanted this feature for a long long time, and finally implemented it. A PR to CKAN is coming up.)
Closes …
> Fill in old Spaceplane Corrections versions; Rename SPPCC

- ClickThroughBlocker/ClickThroughBlocker-0.1.6.10.ckan
Not good to have old versions installing randomly like that.
Now it shares the same max compat as the preceding release.
> Set max compat for historical ClickThroughBlocker

- SpacetuxSA/SpacetuxSA-0.3.12.4.ckan
Not good to have old versions installing randomly like that.
Now it shares the same max compat as the preceding release.
> Fix max compat for historical SpacetuxSA

- PreciseNode/PreciseNode-1.2.10.2.ckan
- PreciseNode/PreciseNode-1.2.10.ckan
- PreciseNode/PreciseNode-1.2.9.4.ckan
Now they go up to KSP 1.7, since they probably broke with the Unity upgrade in KSP 1.8 (see the compatibility range of 1.2.10.3).
> Set compat max for historical PreciseNodes

- MagiCore/MagiCore-1.3.1.4.ckan
Now it shares a max compat with the preceding version.
> Set max compat for historical MagiCore

- DiazosLandingHeight/DiazosLandingHeight-2.2.0.4.ckan
Now it shares a max compat with the subsequent version.
> Set compat max for historical DiazosLandingHeight

- AntaresCygnus/AntaresCygnus-1-v1.3.ckan
Now it shares min and max compat with the subsequent version.
> Set compatibility for historical AntaresCygnus

- B9-PWings-Fork/B9-PWings-Fork-1-0.90.ckan
- B9-PWings-Fork/B9-PWings-Fork-1-0.91.ckan
Now they're set to KSP 1.7, since the change log says they were recompiled for it (and we know KSP 1.8 required recompiles as well).
> Set compatibility for historical B9-PWings-Fork

- PlanetaryDiversity/PlanetaryDiversity-1-1.7.3.2.ckan
- PlanetaryDiversity/PlanetaryDiversity-1-1.7.3.3.ckan
- PlanetaryDiversity/PlanetaryDiversity-1.3.0-2.ckan
- PlanetaryDiversity/PlanetaryDiversity-1.3.0-3.ckan
- PlanetaryDiversity/PlanetaryDiversity-1.3.0-4.ckan
- PlanetaryDiversity/PlanetaryDiversity-1.7.3.1.ckan
- PlanetaryDiversity/PlanetaryDiversity-1.7.3.2.ckan
- PlanetaryDiversity/PlanetaryDiversity-release-1.4.2-1.ckan
This mod followed a Kopernicus-style versioning system where the first three pieces are the game version, but somehow we missed it until recently. The release notes even say specifically that they are compatible with specific game versions.
Now each version is compatible with the game versions designated by its version number.
> Set historical compat for PlanetaryDiversity

- BoxSat-prototypes/BoxSat-prototypes-A.02c.kerbalstuff
- BoxSat-prototypes/BoxSat-prototypes-A.02d.kerbalstuff
- BoxSat-prototypes/BoxSat-prototypes-A.02e.ckan
- CrewManifest/CrewManifest-0.5.10-25.ckan
- CrewManifest/CrewManifest-0.5.10-26.ckan
- CrewManifest/CrewManifest-0.5.10.ckan
- CrewManifest/CrewManifest-0.6.0.ckan
- CustomBarnKit/CustomBarnKit-1.1.1.ckan
- CustomBarnKit/CustomBarnKit-1.1.2.ckan
- DiscordRP/DiscordRP-1.0.3.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.0.0.0.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.0.1.0.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.0.2.0.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.0.3.0.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.1.1.0.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.10.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.11.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.2.0.0.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.2.0.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.3.0.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.4.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.5.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.6.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.7.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.8.ckan
- EasyVesselSwitch/EasyVesselSwitch-1.9.ckan
- ExperimentTracker/ExperimentTracker-v1.2.ckan
- ExperimentTracker/ExperimentTracker-v1.3.ckan
Successor to #1818, see #1816.
> This PR changes every x_ci to ci, x_preview to x_screenshot, and x_curse to curse.
Additionally, one mistyped respository resource has been fixed and the x_textures property has been removed from NavBallTextureExport, since it doesn't have any real use (especially because the bit.ly link has long expired).
> Clean up second group of historical resource properties

- ForScience/ForScience-v1.4.1.ckan
- ForScience/ForScience-v1.5.0.ckan
- ForScience/ForScience-v1.5.2.ckan
- Fusebox/Fusebox-1.2.ckan
- GCMonitor/GCMonitor-1.2.1.0.ckan
- GCMonitor/GCMonitor-1.2.2.0.ckan
- GCMonitor/GCMonitor-1.2.3.0.ckan
- GCMonitor/GCMonitor-1.2.4.0.ckan
- HGR-Props/HGR-Props-1.2.1.ckan
- HGR-Props/HGR-Props-1.3.0.kerbalstuff
- HGR/HGR-1.2.1.ckan
- HGR/HGR-1.3.0.kerbalstuff
- HooliganLabsAirships/HooliganLabsAirships-3.0.0.ckan
- HullcamVDS/HullcamVDS-0.33.ckan
- HullcamVDS/HullcamVDS-0.34.1.ckan
- HullcamVDS/HullcamVDS-0.34.ckan
- HullcamVDS/HullcamVDS-0.40.ckan
- HullcamVDS/HullcamVDS-0.50.ckan
- HullcamVDS/HullcamVDS-0.51.ckan
- HullcamVDS/HullcamVDS-0.52.ckan
- HumanColoredFaces/HumanColoredFaces-17.ckan
Successor to #1820, see #1816.
> This PR changes every `x_ci` to `ci`, `x_preview` to `x_screenshot`, and `x_curse` to `curse`.
Additionally, one mistyped respository resource has been fixed and the `x_textures` property has been removed from `NavBallTextureExport`, since it doesn't have any real use (especially because the bit.ly link has long expired).
ckan compat add 1.2
> Clean up fourth group of historical resource properties

- KAS/KAS-0.4.10.ckan
- KAS/KAS-0.4.7.ckan
- KAS/KAS-0.4.8.ckan
- KAS/KAS-0.4.9.ckan
- KAS/KAS-0.4.ckan
- KAS/KAS-0.5.0.ckan
- KAS/KAS-0.5.1.ckan
- KAS/KAS-0.5.2.ckan
- KAS/KAS-0.5.3.ckan
- KAS/KAS-0.5.4.ckan
- KAS/KAS-0.5.5.ckan
- KAS/KAS-0.5.6.ckan
- KAS/KAS-0.5.7.ckan
- KAS/KAS-0.5.8.0.ckan
- KAS/KAS-0.5.9.0.ckan
- KAS/KAS-0.6.0.0.ckan
- KAS/KAS-0.6.1.0.ckan
- KAS/KAS-0.6.2.0.ckan
- KAS/KAS-0.6.3.0.ckan
- KAS/KAS-0.6.4.ckan
- KAS/KAS-1.0.ckan
- KAS/KAS-1.1.ckan
- KAS/KAS-1.2.ckan
- KAS/KAS-1.3.ckan
- KAS/KAS-1.4.ckan
Successor to #1820, see #1816.
> This PR changes every `x_ci` to `ci`, `x_preview` to `x_screenshot`, and `x_curse` to `curse` (and adjusts the `spec_version` where needed).
Additionally, one mistyped respository resource has been fixed and the `x_textures` property has been removed from `NavBallTextureExport`, since it doesn't have any real use (especially because the bit.ly link has long expired).
Looks like this one only contains spec version updates because it hasn't been updated for the `curse` field when it has been added back then.
I'll submit it nevertheless, does no harm.
I'll check in the NetKAN repo after I'm through with this whether some netkans containing the `curse` resource also need the spec adjusted (aside from those that I added myself)
> Clean up fifth group of historical resource properties

- KlockheedMartian-Gimbal/KlockheedMartian-Gimbal-3.0.3.0.ckan
- KlockheedMartian-Gimbal/KlockheedMartian-Gimbal-3.0.4.0.ckan
- KlockheedMartian-Gimbal/KlockheedMartian-Gimbal-3.0.5.0.ckan
- LanderControl/LanderControl-814.ckan
- ModularFlightIntegrator/ModularFlightIntegrator-1.0.ckan
- ModularFlightIntegrator/ModularFlightIntegrator-1.0.repackaged0.ckan
- ModularFlightIntegrator/ModularFlightIntegrator-1.1.0.0.ckan
- ModuleManager/ModuleManager-2.5.10.ckan
- ModuleManager/ModuleManager-2.5.9.ckan
- ModuleManager/ModuleManager-2.6.0.ckan
- ModuleManager/ModuleManager-2.6.1.ckan
- ModuleManager/ModuleManager-2.6.2.ckan
- ModuleManager/ModuleManager-2.6.3.ckan
- ModuleManager/ModuleManager-2.6.5.ckan
- NavBallTextureExport/NavBallTextureExport-1.3.ckan
- NavBallTextureExport/NavBallTextureExport-1.5.ckan
- OPTSpacePlaneMain/OPTSpacePlaneMain-1.9.0.ckan
- OPTSpacePlaneMain/OPTSpacePlaneMain-1.9.1.ckan
- OPTSpacePlaneMain/OPTSpacePlaneMain-1.9.2.ckan
- OPTSpacePlaneMain/OPTSpacePlaneMain-1.9.9.ckan
- OPTSpacePlaneMain/OPTSpacePlaneMain-2.0.ckan
- OptionalAtm/OptionalAtm-1.4.9.1.ckan
- OptionalAtm/OptionalAtm-1.4.9.ckan
- PartWizard/PartWizard-1.1.2.ckan
- PartWizard/PartWizard-1.2.1.ckan
- PartWizard/PartWizard-v1.2.4.0.ckan
- PartWizard/PartWizard-v1.2.5.0.ckan
Successor to #1826, see #1816.
> This PR changes every `x_ci` to `ci`, `x_preview` to `x_screenshot`, and `x_curse` to `curse` (and adjusts the `spec_version` where needed).
Additionally, one mistyped `respository` resource has been fixed and the `x_textures` property has been removed from `NavBallTextureExport`, since it doesn't have any real use (especially because the bit.ly link has long expired).
ckan compat add 1.2
> Clean up eighth group of historical resource properties

- CameraTools/CameraTools-v1.12.0.ckan
`"ksp_version_max"` was set to `"1.10.99"`, the new release is only 1.8 compatible.
This commit reduces it to KSP 1.7 compatibility, so that the older version doesn't get pulled in on KSP 1.9.
> Fix CameraTools-v1.12.0 compatibility

- DE-IVAExtension/DE-IVAExtension-v1.0.1.ckan
There is some demand for the previous version of this mod.
The forum page says to use RPM v0.30.6, but that mod's forum thread only certifies it up to KSP 1.6, so users will need to add 1.6 as a compatible version manually to install.
ckan compat add 1.6
> Add previous DE-IVAExtension version

- TransferWindowPlanner/TransferWindowPlanner-v1.2.1.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.2.2.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.2.3.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.3.0.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.3.0.1.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.3.1.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.4.0.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.5.0.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.5.1.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.6.0.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.6.1.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.6.2.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.6.3.0.ckan
- TransferWindowPlanner/TransferWindowPlanner-v1.7.1.0.ckan
- WaterSounds/WaterSounds-2.2.ckan
- kTunes/kTunes-1.2.ckan
- surfacelights/surfacelights-1.0.ckan
- surfacelights/surfacelights-1.10.ckan
- surfacelights/surfacelights-1.11.ckan
- surfacelights/surfacelights-1.12.ckan
- surfacelights/surfacelights-1.13.ckan
- surfacelights/surfacelights-1.4.0.ckan
- surfacelights/surfacelights-1.5.ckan
- surfacelights/surfacelights-1.6.ckan
- surfacelights/surfacelights-1.7.ckan
- surfacelights/surfacelights-1.8.ckan
- surfacelights/surfacelights-1.9.ckan
Successor to #1850, see #1816.
> This PR changes every `x_ci` to `ci`, `x_preview` to `x_screenshot`, and `x_curse` to `curse` (and adjusts the `spec_version` where needed).
Additionally, one mistyped `respository` resource has been fixed and the `x_textures` property has been removed from `NavBallTextureExport`, since it doesn't have any real use (especially because the bit.ly link has long expired).
> Clean up eleventh group of historical resources

- Mk2Essentials/Mk2Essentials-5.ckan
- Mk2Essentials/Mk2Essentials-6.ckan
Successor to #1851, see #1816.
> This PR changes every `x_ci` to `ci`, `x_preview` to `x_screenshot`, and `x_curse` to `curse` (and adjusts the `spec_version` where needed).
Additionally, one mistyped `respository` resource has been fixed and the `x_textures` property has been removed from `NavBallTextureExport`, since it doesn't have any real use (especially because the bit.ly link has long expired).
This is the last PR of this row. `Mk2Essentials` is Curse-hosted, so the inflation fails. I don't want to freeze these though, since from time to time you are able to download them. Unfortunately they don't have a archive.org fallback since they are restrictively licensed.
Closes #1816
> Clean up historical resources for Mk2Essentials

- BeyondHome/BeyondHome-1.2.0.ckan
This is the historical counterpart for https://github.com/KSP-CKAN/NetKAN/pull/7741.
There's only one old version so far, luckily ;)
> Don't provide Scatterer-sunflare and Scatterer-config with BeyondHome

- repositories.json
See KSP-CKAN/NetKAN-Infra#155; the dev, RemoteTech, SCANsat, and Trajectories options in this list are 5 years out of date:
Even if you install a version of KSP from 5 years ago, these options would *still* not be useful, since they were pre-releases and there would long since have been normal releases of these mods with the relevant changes in the meantime.
Now the outdated options are removed. default and MechJeb2-dev remain because they are still actively updated.
(KSP-CKAN/NetKAN-Infra#155 still needs some documentation added to the repos to be closed.)
> Remove dead repos from defaults list

- BeyondHome/BeyondHome-1.2.0.ckan
- BeyondHome/BeyondHome-1.3.1.ckan
- BeyondHome/BeyondHome-1.4.0.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0245.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0246.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0247.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0256.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0300.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0320.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0320b.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0324.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0326.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0329_for_1.4.2.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0331.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0331b.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0336.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0520.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0530.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0540.ckan
- Scatterer-sunflare/Scatterer-sunflare-2-v0.0541.ckan
This is KSP-CKAN/NetKAN#7794 for historical releases. Now modules for older game versions can depend on `Scatterer-sunflare-default` if they require the default sunflare config to be installed, and older versions of BeyondHome do this.
Needed for KSP-CKAN/NetKAN#7800.
> Force default sunflare for BeyondHome historical releases

- GPO/GPO-2.4a.ckan
- GPO/GPO-2.5b.ckan
- GPO/GPO-3.0.1.ckan
- GPO/GPO-3.0.2.ckan
- GPO/GPO-3.0.ckan
- GPO/GPO-3.1.ckan
- GPO/GPO-3.2-HOTFIX.ckan
- GPO/GPO-3.2.4.ckan
- GPO/GPO-3.2.5.ckan
- GPO/GPO-3.2.ckan
- GPO/GPO-3.2d.ckan
- GPO/GPO-3.3.1.ckan
This is KSP-CKAN/NetKAN#7800 for historical releases. Now GPO depends on Scatterer-sunflare-default.
> Sunflare fix for GameslinxPlanetOverhaul historical releases

- PilotAssistant/PilotAssistant-v1.13.4.ckan
The author updated the version file which unintentionally affected the previous release because the version number wasn't truly updated. Now it's back as it was.
> Revert historical PilotAssistant compatibility

- TelemachusReborn/TelemachusReborn-1.7.35.ckan
This release had no version file, see TeleIO/Telemachus-1#33, and no `x_netkan_override` to set the compatibility as the previous release did. The next release was created in part to fix this. Now the same compatibility is copied back to 1.7.35.
> Set compatibility for historical TelemachusReborn release

- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.2.0.ckan
- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.2.1.ckan
- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.3.1.ckan
- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.3.2.ckan
- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.3.3.ckan
- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.3.4.ckan
- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.3.5.ckan
- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.3.6.ckan
- LithobrakeExplorationTechnologies/LithobrakeExplorationTechnologies-0.3.ckan
Historical version of KSP-CKAN/NetKAN#7826. Firespitter shouldn't be a dependency for this mod.
> Remove FirespitterCore depends from LithobrakeExplorationTechnologies

- ColorCodedCans/ColorCodedCans-0.3.ckan
- ColorCodedCans/ColorCodedCans-0.4.ckan
- ColorCodedCans/ColorCodedCans-0.5.ckan
- ColorCodedCans/ColorCodedCans-0.6.ckan
- ColorCodedCans/ColorCodedCans-0.7.ckan
- ColorCodedCans/ColorCodedCans-0.8.ckan
- ColorCodedCans/ColorCodedCans-0.9.ckan
- ColorCodedCans/ColorCodedCans-1.0.ckan
- ColorCodedCans/ColorCodedCans-1.1.0.ckan
- ColorCodedCans/ColorCodedCans-1.1.1.ckan
- ColorCodedCans/ColorCodedCans-1.2.1.ckan
- ColorCodedCans/ColorCodedCans-1.2.ckan
- ColorCodedCans/ColorCodedCans-1.3.1.ckan
- ColorCodedCans/ColorCodedCans-1.3.2.ckan
- ColorCodedCans/ColorCodedCans-1.3.ckan
- ColorCodedCans/ColorCodedCans-1.4.2.ckan
- ColorCodedCans/ColorCodedCans-1.4.3.ckan
- ColorCodedCans/ColorCodedCans-1.4.4.ckan
- ColorCodedCans/ColorCodedCans-1.4.5.ckan
- ColorCodedCans/ColorCodedCans-1.4.6.ckan
- ColorCodedCans/ColorCodedCans-1.4.7.ckan
- ColorCodedCans/ColorCodedCans-1.4.8.ckan
- ColorCodedCans/ColorCodedCans-1.4.ckan
- ColorCodedCans/ColorCodedCans-1.5.1.ckan
- ColorCodedCans/ColorCodedCans-1.5.ckan
- ColorCodedCans/ColorCodedCans-2.0.0.ckan
Historical version of KSP-CKAN/NetKAN#7836. Now all old versions of CCC conflict with ReStock and Vens.
> Historical ColorCodedCans conflicts with mods that change stock tanks

- ModularLaunchPads/ModularLaunchPads-1.01.ckan
- ModularLaunchPads/ModularLaunchPads-1.1.ckan
- ModularLaunchPads/ModularLaunchPads-1.2.1.ckan
- ModularLaunchPads/ModularLaunchPads-1.2.2.ckan
- ModularLaunchPads/ModularLaunchPads-1.2.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.0.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.1.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.2.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.3.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.4.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.5.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.6.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.7.ckan
- ModularLaunchPads/ModularLaunchPads-1.3.8.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.0.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.1.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.2.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.3.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.4.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.5.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.6.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.7.ckan
- ModularLaunchPads/ModularLaunchPads-2.0.7b.ckan
Historical version of KSP-CKAN/NetKAN#7865.
Apparently these dependencies go all the way back, as they're bundled as ZIPs-within-a-ZIP in even the earliest versions.
ckan compat add 1.7.3
> ModularLaunchPads historical dependencies

- AIESAerospace-Unofficial/AIESAerospace-Unofficial-1.6.1-patched.ckan
See KSP-CKAN/CKAN#3000; @linuxgurugamer made an AIES-Patches module to make AIESAerospace-Unofficial work on recent versions, but installation currently requires setting KSP 1.0 as compatible temporarily.
This PR implements the suggested workaround of a special version compatible with all KSP versions but depending on the patches.
> Create patched AIES release

- AstronomersVisualPack/AstronomersVisualPack-2-4.0.2.0.ckan
See KSP-CKAN/NetKAN#7876 and themaster402/AstronomersVisualPack#16, this mod's 4.0.3 release replaced 4.0.2 because its version file wasn't updated. This reverts commit 548803b3c76a0198d12b5dd2b234ccb702710ee5.
ckan compat add 1.8
> Restore AVP 4.0.2

- BreakingGround-DLC/BreakingGround-DLC-1.0.0.ckan
- BreakingGround-DLC/BreakingGround-DLC-1.1.0.ckan
- BreakingGround-DLC/BreakingGround-DLC-1.2.0.ckan
- BreakingGround-DLC/BreakingGround-DLC-1.3.0.ckan
- BreakingGround-DLC/BreakingGround-DLC-1.3.1.ckan
- BreakingGround-DLC/BreakingGround-DLC-1.4.0.ckan
- BreakingGround-DLC/BreakingGround-DLC-1.4.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.0.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.1.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.2.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.3.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.4.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.5.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.5.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.6.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.6.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.7.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.7.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.8.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.8.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.9.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.9.1.ckan
This PR adds a .ckan file for each known version of each DLC, based on the change logs in their `readme.txt` files, following the format created in KSP-CKAN/CKAN#3038.
The spec version is `v1.28`, so it should be safe to merge this without disrupting the existing clients, all of which are on `v1.27` or earlier.
> Add modules for DLC

- ASETAvionics/ASETAvionics-1.0.ckan
- ASETAvionics/ASETAvionics-2.0.ckan
Historical version of KSP-CKAN/NetKAN#7908, these are data files that can be used on any game version where the dependencies are available.
> Make historical ASETAvionics compatible with all game versions

- ASETProps/ASETProps-1.3.ckan
- ASETProps/ASETProps-1.4.ckan
Historical version of KSP-CKAN/NetKAN#7909, these are data files that can be used on any game version where the dependencies are available.
> Make historical ASETProps compatible with all game versions

- SeparatorDestroyer/SeparatorDestroyer-1.0.0.0.ckan
- SeparatorDestroyer/SeparatorDestroyer-1.0.0.1.ckan
See https://github.com/KSP-CKAN/CKAN-meta/pull/1922 and https://github.com/KSP-CKAN/NetKAN/pull/7921
Fixes the historical compatibility data to how I think it's supposed to be.
Also took the opportunity to backport the tags and the ModuleManager dependency, because why not.
> Fix historical compatibility for SeparatorDestroyer

- RSSDateTimeFormatter/RSSDateTimeFormatter-1.4.3.0.ckan
- RSSDateTimeFormatter/RSSDateTimeFormatter-1.4.5.0.ckan
- RSSDateTimeFormatter/RSSDateTimeFormatter-1.5.1.0.ckan
See KSP-RO/RSSTimeFormatter#16, this mod used to have a version file, but it got dropped. Now the compatibility of historical versions is updated to reflect the release announcements.
- https://github.com/KSP-RO/RSSTimeFormatter/releases
The current version is not updated because the bot will just overwrite it until that issue is fixed.
> Fix historical RSSDateTimeFormatter compatibility

- SpaceXLaunchVehicles-StockSize/SpaceXLaunchVehicles-StockSize-6.1.ckan
- SpaceXLaunchVehicles/SpaceXLaunchVehicles-6.0.ckan
See https://github.com/KSP-CKAN/NetKAN/pull/7962
This backports the `find`->`file` change until version `6.0`, before there was no `Rescaled/Ships/VAB` folder, so no ambiguity problem.
Also backported the name change and the new conflict with `SpaceXLaunchVehicles-StockSize` along the way.
I also created the `SpaceXLaunchVehicles-StockSize` ckan file for `6.1`.
`6.0` had a different folder structure and is also for 1.9.1, so it's not worth the effort to hand-craft a ckan file just for this.
Before `6.0` there were no files for a stock size version.
> Historic SpaceXLaunchVehicles installation fixes

- SCANsat/SCANsat-v20.0.ckan
See S-C-A-N/SCANsat#371, this version of SCANsat has a syntax error in its version file, so it has been erroring out in the bot and hasn't been indexed.
A fix version hasn't come out yet, and people continue to ask about it despite repeated announcements on the forum and Discord, so we might as well work around the issue.
Process for generating this file:
1. Temporarily remove the vref from a local copy of the netkan
2. `netkan.exe NetKAN/SCANsat.netkan`
3. Edit `SCANsat-v20.0.ckan` to add the version compatibility that it's supposed to have
4. Move to `CKAN-meta/SCANsat`
> Manually index SCANsat v20.0

- PersistentThrust/PersistentThrust-1-1.2.1.ckan
- PersistentThrust/PersistentThrust-1-1.4.5.ckan
Users are complaining about hash mismatches on this thread; some versions must have been replaced after indexing. I ran `netkan.exe --releases 15`.
https://forum.kerbalspaceprogram.com/index.php?/topic/194707-171181191-persistent-thrust-extended-145/
> Update PersistentThrust hashes

- RP-0/RP-0-v1.3.ckan
- RP-0/RP-0-v1.4.1.ckan
- RP-0/RP-0-v1.4.ckan
Historical version of KSP-RO/RP-0#1303; RP-0 has been recommending conflicting mods, and TestLite has just been indexed.
Now RP-0 versions back to KSP 1.6.1 through 1.7.3 are fixed and updated.
> Recommend TestLite for historical RP-0 versions

- SmokeScreen/SmokeScreen-2.8.3.0.ckan
- SmokeScreen/SmokeScreen-2.8.4.0.ckan
- SmokeScreen/SmokeScreen-2.8.5.0.ckan
- SmokeScreen/SmokeScreen-2.8.6.0.ckan
The [RP-0 installation wiki] for KSP 1.6.1 includes this odd and mysterious tidbit:
> Via CKAN, revert SmokeScreen version to v2.8.1. The version that gets installed automatically doesn't work correctly
>
> ![screenshot](https://cdn.discordapp.com/attachments/512556137380315139/623208783522299914/2019-09-16_20-28-12.jpg)
Digging into [the forum thread], it turns out that 2.8.2.0 was buggy and threw exceptions like crazy. 2.8.3.0 through 2.8.6.0 were fix releases that had no new version requirements announced. 2.8.7.0 was announced for KSP 1.8.
However, KSP-CKAN/NetKAN#7312 was merged between 2.8.2.0 and 2.8.3.0 and set the minimum compatibility of the netkan to 1.7, and thus the buggy release ended up being the last one for KSP 1.5 and 1.6.
Now these releases are compatible with KSP 1.5 …
> Mark historical SmokeScreen versions as compatible back to KSP 1.5

- AdvancedJetEngine/AdvancedJetEngine-1.6.4.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.6.8.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.6.ckan
- AdvancedJetEngine/AdvancedJetEngine-1.7a.ckan
- CustomBiomes/CustomBiomes-1.6.8.ckan
- DynamicBatteryStorage/DynamicBatteryStorage-1.0.0.ckan
- EarlyBird/EarlyBird-0.1.5.0.ckan
- EarlyBird/EarlyBird-0.1.6.0.ckan
- EarlyBird/EarlyBird-0.1.7.0.ckan
- EarlyBird/EarlyBird-0.2.0.0.ckan
- PunishTheLazy/PunishTheLazy-0.01.ckan
- ResetSAS/ResetSAS-0.01.ckan
- SciFiVisualEnhancements/SciFiVisualEnhancements-v1.4.ckan
- SciFiVisualEnhancements/SciFiVisualEnhancements-v1.5.ckan
- kOS/kOS-0.14.ckan
See https://github.com/KSP-CKAN/CKAN/pull/3111, these ckans are missing the author property.
This PR adds it to those that validate successfully,there's another PR for those that fail validation (#2109).
There will also be a PR for some NetKAN files, which I have yet to create, but should be merged first.
`grep -L "author" **/*.ckan`
```
AdvancedJetEngine/AdvancedJetEngine-1.6.4.ckan
AdvancedJetEngine/AdvancedJetEngine-1.6.8.ckan
AdvancedJetEngine/AdvancedJetEngine-1.6.ckan
AdvancedJetEngine/AdvancedJetEngine-1.7a.ckan
CustomBiomes/CustomBiomes-1.6.8.ckan
DynamicBatteryStorage/DynamicBatteryStorage-1.0.0.ckan
EarlyBird/EarlyBird-0.1.5.0.ckan
EarlyBird/EarlyBird-0.1.6.0.ckan
EarlyBird/EarlyBird-0.1.7.0.ckan
EarlyBird/EarlyBird-0.2.0.0.ckan
kOS/kOS-0.14.ckan …
```
> Fill in missing author properties

- CommunityDeltaVMaps/CommunityDeltaVMaps-v2.6.0.ckan
Fixes KSP-CKAN/NetKAN#8045.
No point in updating the netkan because it doesn't inflate, the latest release doesn't have the KSPedia files.
> Set ksp_version_max for CommunityDeltaVMaps

- BreakingGround-DLC/BreakingGround-DLC-1.5.0.ckan
- BreakingGround-DLC/BreakingGround-DLC-1.5.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.10.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.10.1.ckan
The KSP 1.10.0 and 1.10.1 releases have their own DLC verisons, which currently have no .ckan files.
Now they're added based on the readme file for each DLC.
(There is code to autogenerate these in the client, but it has a bug that we'll fix in a separate PR.)
> Add recent DLC versions

- ConfigurableContainers/ConfigurableContainers-2.6.0.ckan
See KSP-CKAN/NetKAN#8085, the PRs submitted to fix that will only affect the current release. This PR fixes CC 2.6.0.
> Fix compatibility (KSP 1.10.x)

- SSTOProject/SSTOProject-1.3.1.ckan
- SSTOProject/SSTOProject-1.3.2.ckan
- SSTOProject/SSTOProject-1.3.3.ckan
- SSTOProject/SSTOProject-1.3.ckan
I've tested SSTO Project to work with both KSP 1.8.1 and 1.9.1. No updates were pushed, but SpaceDock description were updated with:
> Works with KSP 1.9.x too
> Edit SSTO Project 1.3.x to be installable with 1.9.x

- TestFlight/TestFlight-1.10.0.0.ckan
- TestFlight/TestFlight-1.11.0.0.ckan
- TestFlight/TestFlight-1.3.1.0.ckan
- TestFlight/TestFlight-1.3.1.0a.ckan
- TestFlight/TestFlight-1.3.1.1.ckan
- TestFlight/TestFlight-1.4.0.2.ckan
- TestFlight/TestFlight-1.5.0.1.ckan
- TestFlight/TestFlight-1.5.1.0.ckan
- TestFlight/TestFlight-1.5.2.0.ckan
- TestFlight/TestFlight-1.5.3.0.ckan
- TestFlight/TestFlight-1.5.4.0.ckan
- TestFlight/TestFlight-1.5.4.2.ckan
- TestFlight/TestFlight-1.5.4.4.ckan
- TestFlight/TestFlight-1.5.5.0.ckan
- TestFlight/TestFlight-1.6.0.0.ckan
- TestFlight/TestFlight-1.6.0.1.ckan
- TestFlight/TestFlight-1.6.0.2.ckan
- TestFlight/TestFlight-1.6.0.3.ckan
- TestFlight/TestFlight-1.7.0.0.ckan
- TestFlight/TestFlight-1.7.0.1.ckan
- TestFlight/TestFlight-1.8.0.0.ckan
- TestFlight/TestFlight-1.8.0.1.ckan
- TestFlight/TestFlight-1.9.0.0.ckan
- TestFlight/TestFlight-1.9.1.0.ckan
See https://github.com/KSP-CKAN/NetKAN/pull/8128
This backports the dependency until version 1.3.1.0, which was the first one containing the TestFlightContracts DLL.
> Add ContractConfigurator dependency to historical TestFlight versions

- ThrottleControlledAvionics/ThrottleControlledAvionics-v3.7.1.ckan
Now this is reflected in the CKAN metadata for the non-current versions.
This is part of the fix for KSP-CKAN/NetKAN#8140, along with allista/ThrottleControlledAvionics#102.
> Fix historical ThrottleControlledAvionics compatibility

- repositories.json
People might want this...  or not.  Who knows?
> Add Kopernicus Bleeding Edge repository

- CommunityResourcePack/CommunityResourcePack-1.3.0.0.ckan
There was some churn with this release's versioning due to remote version file shenanigans, see BobPalmer/CommunityResourcePack#249.
Now that there's a newer release, we can update the previous one to what was intended.
> Remove max version for CRP 1.3

- AECS-Motion-Suppressor/AECS-Motion-Suppressor-1.3.0.ckan
- AECS-Motion-Suppressor/AECS-Motion-Suppressor-1.3.1.1.ckan
- AECS-Motion-Suppressor/AECS-Motion-Suppressor-1.3.1.ckan
- AECS-Motion-Suppressor/AECS-Motion-Suppressor-1.3.2.1.ckan
- AECS-Motion-Suppressor/AECS-Motion-Suppressor-1.3.2.2.ckan
- AECS-Motion-Suppressor/AECS-Motion-Suppressor-1.3.2.ckan
Historical piece of KSP-CKAN/NetKAN#8181. The ZERO WIDTH NO-BREAK SPACE characters originally came from the SpaceDock abstract, so it was already in .ckan files prior to #7729.
> Fix historical AECS-Motion-Suppressor abstracts

- Parallax-StockTextures/Parallax-StockTextures-1.1.0_-_PRE.ckan
- Parallax/Parallax-1.1.0_-_PRE.ckan
Backport of https://github.com/KSP-CKAN/NetKAN/pull/8219
This adds the `Parallax-StockTextures-1.1.0_-_PRE.ckan`, and updates Parallax 1.0.1 and 1.1.0 to depend on Parallax-Textures (and Kopernicus).
There will be another PR for Parallax 1.1.1, splitting to try to mitigate our disk space problem.
ckan compat add 1.9
> Backport Parallax-Textures to Parallax 1.1.0

- Parallax-StockTextures/Parallax-StockTextures-1.1.1.ckan
Continuation of #2172 
This adds the `Parallax-StockTextures-1.1.1.ckan`, and updates Parallax 1.1.1 to depend on Parallax-Textures (and Kopernicus).
ckan compat add 1.9
> Backport Parallax-Textures to Parallax 1.1.1

- Kerbulator/Kerbulator-1-0.4.ckan
- Kerbulator/Kerbulator-1-0.41.ckan
- Kerbulator/Kerbulator-1-0.42.ckan
- Kerbulator/Kerbulator-1-0.43.ckan
- Kerbulator/Kerbulator-1-0.44.ckan
- Kerbulator/Kerbulator-1-0.45.ckan
- Kerbulator/Kerbulator-1-0.46.ckan
This mod's version system assumes dots are optional, and goes from versions like 0.36 to 0.4 to 0.41, and 0.46 to 0.5
Version 0.4 has been released before our auto-epoching feature and has been missed to epoch manually, so all the 0.4* versions needed an epoch as well.
> Epoch Kerbulator versions

- Pathfinder/Pathfinder-v1.35.1.ckan
- Pathfinder/Pathfinder-v1.35.2.ckan
- Pathfinder/Pathfinder-v1.36.0.ckan
Historical counterpart of KSP-CKAN/NetKAN#8254, Pathfinder was installing a folder from a bundled mod. Now it doesn't.
> Don't install Buffalo's Ships folder as part of Pathfinder

- ProceduralAirships/ProceduralAirships-1.3.ckan
This mod's forum thread has people stating it's broken starting in March of 2015, continuing into this year.
Noticed while looking for mods that use `"install_to": "Tutorial"` (this is the only one).
Also that install stanza is wrong and is now fixed.
Also fake instances didn't have the needed dir until https://github.com/KSP-CKAN/CKAN/commit/042c3f52c4685a42c3b05b2b00568c587fe955e9
> ProceduralAirships is not compatible with 1.0 or later

- repositories.json
I talked with @R-T-B about moving his CKAN metadata repository for Kopernicus Bleeding Edge to GitHub, so we can use the automatically generated archive tar.gz, and avoid disruptions for CKAN users when his personal internet connection and/or server suffers from an outage.
All the metadata files are now also uploaded to https://github.com/R-T-B/CKAN-meta-dev-Kopernicus_BE, so we can switch over the URL.
IIRC (without checking the code) tthe link won't automatically update for existing users of this custom repo, so they need to remove and add it again. @R-T-B said he is going to keep the old URI up-to-date for the time being, and maybe he can work out a proxy-like setup.
> Change Kopernicus_BE repo URI to GitHub generated archive

- ContractConfigurator-PlanesWithPurposes/ContractConfigurator-PlanesWithPurposes-1.2.ckan
- ContractConfigurator-PlanesWithPurposes/ContractConfigurator-PlanesWithPurposes-1.3.ckan
See https://github.com/KSP-CKAN/NetKAN/pull/8312
1.2 still needs the folder fixup, but the destination folder is now renames to `PWP`.
1.3 comes with its own `PWP` subfolder, and a cleaned zip.
> Fix PlanesWithPurposes install stanza

- .github/workflows/validate.yml
See KSP-CKAN/NetKAN#8332, `actions/cache` can't read some of our cached files, so we need to chmod them.
> Cache permissions workaround

- MissingHistory/MissingHistory-1.9.ckan
Meant to take care of this in #2246, but got confused by multiple posts saying slightly different things:
- 1.9 shouldn't be used on 1.11
- 1.9 is OK for 1.10.0
> Update MissingHistory 1.9 compat again

- Kopernicus/Kopernicus-2-release-1.8.1-23.ckan
This was uploaded rapidly with dd406ef70784a821fa64cacfa97447c5904ba5c7 and got skipped.
Just a simple `--releases 2` run.
> Backfill Kopernicus 1.8.1 backport

- Kopernicus/Kopernicus-2-release-1.8.1-24.ckan
Version `1.8.1-24` got uploaded shortly before `1.9.1-24` and thus has been missed;
Version `1.8.1-23` has been deleted and recreated with a slightly different tag name.
> Backfill Kopernicus 1.8.1-24 and fix Kopernicus 1.8.1-23 download

- AdvancedFlyByWire-OSX/AdvancedFlyByWire-OSX-1.8.3.1.ckan
Historical continuation of part of KSP-CKAN/NetKAN#8341. AFBW-OSX has been using the wrong asset since KSP-CKAN/NetKAN#7729, now all historical versions are fixed.
> Don't use Linux asset for AFBW-OSX

- ReStock/ReStock-1.3.0.ckan
The min part of this commit:
https://github.com/PorktoberRevolution/ReStocked/commit/2cceb95dac1c8c90edf50378111ada03ba4f0549#diff-7f788e8a221c9ac1ef7c4ac82021c69b918f6bc0e3b2b6f98ac53bcc77dc9502
Was meant to be done with this commit:
https://github.com/PorktoberRevolution/ReStocked/commit/135a775aab9520cc958b26522975bdd692ac27e5#diff-7f788e8a221c9ac1ef7c4ac82021c69b918f6bc0e3b2b6f98ac53bcc77dc9502
Since a mod version change to 1.3.1 accompanied it, the compatibility of 1.3.0 wasn't updated.
Now the min is 1.10.0.
> Fix ReStock 1.3.0 min compat

- Kopernicus/Kopernicus-2-release-1.10.1-27.ckan
- Kopernicus/Kopernicus-2-release-1.11.1-27.ckan
The `release-27` release tag of Kopernicus introduced new assets for KSP 1.10.1 and 1.11.1.
However they included incorrect version files, stating a compatibility with KSP 1.9.1, see https://github.com/Kopernicus/Kopernicus/pull/477
Now we've got a `release-28` which, after a handful of attempts, includes the fixed version files with correct compatibility. It should be updated any minute.
So we're fixing the compatibility of `release-1.10.1-27` and `release-1.11.1-27` here to ensure users don't install or upgrade to an incompatible version.
> Fix Kopernicus -27 release compat

- GPO/GPO-3.3.1.ckan
- GPO/GPO-3.4.0.ckan
- SemioticStandard/SemioticStandard-1.1.1.ckan
These mods have been frozen in https://github.com/KSP-CKAN/NetKAN/pull/8390, however the compatibility data of their latest releases isn't 100% correct. Now that they're frozen it#s quite easy to fix.
Probably not very useful, but why not give those mods with correct data as a last salute, someone doing a nostalgic KSP run might benefit from this after all.
Originally released for KSP 1.4:
https://github.com/KSP-CKAN/CKAN-meta/commit/9d50c38fcc73f3d70f658da03a569ae7937859d4#diff-cd74631dc015e2a6949fee3d295520286016b7bc19dc66a28b0e35166d3de1a2
But according to the forum thread compatible with up to KSP 1.7:
This one is caused by incorrect .version files included in the download.
> Fix compatibility of frozen mods

- BluedogDB/BluedogDB-v1.7.0.ckan
See https://github.com/CobaltWolf/Bluedog-Design-Bureau/pull/1040
v1.7.1 got updated via the remote version file ([bot commit here](https://github.com/KSP-CKAN/CKAN-meta/commit/20f6283992fc30effc2df231453727644bbf88db)), the author additionally asked me to change the compatibility of v1.7.0 to min KSP 1.8.1:
> Set BluedogDB v1.7.0 min KSP version to 1.8.1

- Kerbalism-Config-RO/Kerbalism-Config-RO-v0.1.1.ckan
- Kerbalism-Config-RO/Kerbalism-Config-RO-v0.1.2.ckan
- Kerbalism-Config-RO/Kerbalism-Config-RO-v0.1.ckan
- Kerbalism-Config-RO/Kerbalism-Config-RO-v0.2.ckan
- Kerbalism-Config-RO/Kerbalism-Config-RO-v0.9.1.ckan
- Kerbalism-Config-RO/Kerbalism-Config-RO-v0.9.ckan
Historical counterpart to KSP-CKAN/NetKAN#8401, this module should conflict with life support.
> Make Kerbalism-Config-RO conflict with life support mods

- BreakingGround-DLC/BreakingGround-DLC-1.6.0.ckan
- BreakingGround-DLC/BreakingGround-DLC-1.6.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.11.0.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.11.1.ckan
Upstream DLC maintenance has gotten a bit sloppy, see part of KSP-CKAN/CKAN#3243 and KSP-CKAN/CKAN#3302.
In KSP 1.11.1, both DLCs were updated in the changelog but not in the version declared at the top of the readme:
```
$ egrep '^Version|1.11' */readme.txt
MakingHistory/readme.txt:Version 1.11.0
MakingHistory/readme.txt:=================================== v1.11.1 - Requires KSP v1.11.1 ================================
MakingHistory/readme.txt:=================================== v1.11.0 - Requires KSP v1.11.0 ================================
Serenity/readme.txt:Version 1.6.0	
Serenity/readme.txt:====================================== v1.6.1 - Requires KSP v1.11.1 ==============================
Serenity/readme.txt:====================================== v1.6.0 - Requires KSP v1.11.0 …
```
> Make recent DLCs compatible with KSP 1.11.2

- AirlockPlus/AirlockPlus-v0.0.10.ckan
- AirlockPlus/AirlockPlus-v0.0.9.ckan
- Kerbalism/Kerbalism-3.0.1.ckan
- Kerbalism/Kerbalism-3.0.2.ckan
- Kerbalism/Kerbalism-3.0.ckan
- Kerbalism/Kerbalism-3.1.ckan
- Kerbalism/Kerbalism-3.10.ckan
- Kerbalism/Kerbalism-3.11.ckan
- Kerbalism/Kerbalism-3.2.ckan
- Kerbalism/Kerbalism-3.3.ckan
- Kerbalism/Kerbalism-3.4.ckan
- Kerbalism/Kerbalism-3.5.ckan
- Kerbalism/Kerbalism-3.6.ckan
- Kerbalism/Kerbalism-3.7.ckan
- Kerbalism/Kerbalism-3.8.ckan
- Kerbalism/Kerbalism-3.9.ckan
- LunaMultiplayer/LunaMultiplayer-0.26.0.ckan
- TiltEm/TiltEm-1.2.0.ckan
- TiltEm/TiltEm-1.2.1.ckan
- TiltEm/TiltEm-1.2.2.ckan
Historical counterpart of KSP-CKAN/NetKAN#8288.
These mods bundle a Harmony 1 DLL. Now they provide the Harmony1 identifier.
> Mark Harmony1 bundlers

- BluedogDB/BluedogDB-v1.7.1.ckan
This reverts commit 026defc567c50b4801b253ae9ff6ad0082eccdcc.
That commit was the bot picking up on https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/4f345c1727f6988df9a474b5f8e3ab0eed0bf1bb. Since the `VERSION` is updated for a new release, the compat update from CobaltWolf/Bluedog-Design-Bureau#1040 is no longer available.
This should be merged after KSP-CKAN/NetKAN#8434.
> Revert BluedogDB-v1.7.1 compat change

- StandardPropulsionSystems/StandardPropulsionSystems-1.0.5.ckan
This mod's author intends that it be treated as compatible with all future game versions:
https://forum.kerbalspaceprogram.com/index.php?/topic/200041-110x-111x-moar-station-science-out-of-beta/&do=findComment&comment=3946101
> It's a very simple part mod under the hood, so it should remain compatible with both KSP and other mods pretty much indefinitely.
The netkan was frozen as idle in KSP-CKAN/NetKAN#7513, so if we unfreeze it in the future we'll have to figure out the compatibility anew at that time.
> Make StandardPropulsionSystems indefinitely compatible

- UniversalStorage/UniversalStorage-1.3.0.0.ckan
- UniversalStorage/UniversalStorage-1.4.0.0.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.2.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.3.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.4.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.5.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.6.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.7.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.8.ckan
- UniversalStorage2/UniversalStorage2-1.3.1.9.ckan
- UniversalStorage2/UniversalStorage2-1.4.5.2.ckan
- UniversalStorage2/UniversalStorage2-1.4.5.3.ckan
- UniversalStorage2/UniversalStorage2-1.4.5.4.ckan
- UniversalStorage2/UniversalStorage2-1.5.1.5.ckan
- UniversalStorage2/UniversalStorage2-1.5.1.6.ckan
- UniversalStorage2/UniversalStorage2-1.5.1.7.ckan
- UniversalStorage2/UniversalStorage2-1.5.1.8.ckan
- UniversalStorage2/UniversalStorage2-1.6.0.9.ckan
- UniversalStorage2/UniversalStorage2-1.7.0.10.ckan
- UniversalStorage2/UniversalStorage2-1.9.1.1.ckan
The domain expired and is reportedly redirecting to scam/phishing sites for people without ad- & scriptblocker.
We don't want our users to catch a virus, especially not these days.
I've already replaced the links on the SpaceDock page, now I'm backporting the change to older releases.
The homepage link now goes to the forum thread, the repository link goes to a OneDrive archive of the source code. Yes, 1drv.ms is legit, please ask Microsoft why they thought using a domain looking as shady as this for link shortening would be a good idea.
The UniversalStorage 1 metadata contains a bunch of links to a different domain, www.kingtiger.co.uk, which also seems to be abandoned, but is not leading to any phishing sites so I kept it as is for now.
Fixes …
> Replace bad UniversalStorage links

- TechTreeKompacted/TechTreeKompacted-1.4.ckan
Backport of https://github.com/KSP-CKAN/NetKAN/pull/8481 to version 1.4 of TechTreeKompacted , which was the first one without these conflicts.
> Remove UnKerballedStart and ProbesBeforeCrew from TechTreeKompacted 1.4 conflicts

- ROEngines/ROEngines-v1.3.1.0.ckan
- ROEngines/ROEngines-v1.4.0.0.ckan
- ROEngines/ROEngines-v1.5.ckan
- ROEngines/ROEngines-v1.6.ckan
See KSP-RO/ROEngines#140, this mod always included ND content from @raidernick and should have had the CC-BY-NC-ND license all along.
> Fix ROEngines historical licenses

- TheWorldBeyond/TheWorldBeyond-v1.1.1.ckan
See https://github.com/KSP-CKAN/NetKAN/pull/8580, this mod has been discontinued, and to allow adoption by another author the license has been changed to CC-BY-NC-SA-4.0.
The compatibility is updated as well, to reflect the latest state of the forum thread:
> Update TheWorldBeyond license and compatibility

- KSPInterstellarExtended/KSPInterstellarExtended-1.28.12.ckan
Backport of https://github.com/KSP-CKAN/NetKAN/pull/8610, release `1.28.12` was the first one that moved this DLL out of the mod folder to the root of GameData.
ckan compat add 1.12
> Add InterstellarRedistributable dependency to KSPIE

- Parallax/Parallax-1.2.3.ckan
See https://github.com/KSP-CKAN/NetKAN/pull/8631, the previous release of Parallax, 1.2.3, also works on KSP 1.12, maybe someone wants to stay on this one for the time being for whatever reason. And it's good to have the metadata accurate.
> Update compatibility of Parallax 1.2.3

- GPP/GPP-1-1.6.4.0.ckan
- GPP/GPP-1-1.6.4.1.ckan
- GPP/GPP-1-1.6.4.2.ckan
- GPPCloudsHighRes/GPPCloudsHighRes-1.6.4.0.ckan
- GPPCloudsHighRes/GPPCloudsHighRes-1.6.4.1.ckan
- GPPCloudsHighRes/GPPCloudsHighRes-1.6.4.2.ckan
- GPPCloudsLowRes/GPPCloudsLowRes-1.6.4.0.ckan
- GPPCloudsLowRes/GPPCloudsLowRes-1.6.4.1.ckan
- GPPCloudsLowRes/GPPCloudsLowRes-1.6.4.2.ckan
- GPPSecondary/GPPSecondary-1.6.4.0.ckan
- GPPSecondary/GPPSecondary-1.6.4.1.ckan
- GPPSecondary/GPPSecondary-1.6.4.2.ckan
- GPPTextures/GPPTextures-3.0.0.ckan
- GPPTextures/GPPTextures-4.0.0.ckan
- GPPTextures/GPPTextures-4.1.0.ckan
- GPPTextures/GPPTextures-4.1.1.ckan
- GPPTextures/GPPTextures-4.2.0.ckan
Historical backport of https://github.com/KSP-CKAN/NetKAN/pull/8644
Compatibility is taken from the version file, the embedded file matched the remote file at all times (https://github.com/Galileo88/Galileos-Planet-Pack/commits/master/GameData/GPP/Version/GalileosPlanetPack.version).
The Grannus-RibbonPack filter is also put on the right isntall stanza, another NetKAN PR will follow to correct it for the netkan file.
> Fix GPP mod suite compat and dependencies

- Notes2Log/Notes2Log-0.0.1.ckan
- Notes2Log/Notes2Log-0.0.2.ckan
`utility` slipped through without discussion in KSP-CKAN/NetKAN#8261, so it's currently the dreaded single-mod tag.
Already removed from the netkan in https://github.com/KSP-CKAN/NetKAN/commit/445257e4e225937d476a2b6dad10167c136c81a7
> Purge rogue tag

- Scatterer-config/Scatterer-config-3-v0.0770.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0770.ckan
- Scatterer/Scatterer-3-v0.0770.ckan
Historical correlate of KSP-CKAN/NetKAN#8700, Scatterer's min compat still goes back to 1.9, now the previous version reflects this as well.
> Update historical Scatterer compat

- Scatterer-config/Scatterer-config-3-v0.0600.ckan
- Scatterer-config/Scatterer-config-3-v0.0610.ckan
- Scatterer-config/Scatterer-config-3-v0.0621b.ckan
- Scatterer-config/Scatterer-config-3-v0.0621c.ckan
- Scatterer-config/Scatterer-config-3-v0.0630.ckan
- Scatterer-config/Scatterer-config-3-v0.0632.ckan
- Scatterer-config/Scatterer-config-3-v0.0722.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0600.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0610.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0621b.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0621c.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0630.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0632.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0722.ckan
- Scatterer/Scatterer-3-v0.0600.ckan
- Scatterer/Scatterer-3-v0.0610.ckan
- Scatterer/Scatterer-3-v0.0621b.ckan
- Scatterer/Scatterer-3-v0.0621c.ckan
- Scatterer/Scatterer-3-v0.0630.ckan
- Scatterer/Scatterer-3-v0.0632.ckan
- Scatterer/Scatterer-3-v0.0722.ckan
I should have looked at the new version/compat table in #2427, it's very unlikely that the true min compat version went forwards to 1.11.0 and then backwards to 1.9:
Now all of the versions that have compatibility beyond 1.9, also have min compat of 1.9.
> Update more historical Scatterer compat

- KSPBurst/KSPBurst-v1.5.0.0.ckan
- KSPBurst/KSPBurst-v1.5.4.0.ckan
- KSPBurst/KSPBurst-v1.5.4.1.ckan
- KSPBurst/KSPBurst-v1.5.5.0.ckan
Historical component of KSP-CKAN/NetKAN#8706, now `KSPBurst-Full` is provided by all versions of `KSPBurst`.
> Provide unique identifier for the full KSPBurst module

- FMRSContinued/FMRSContinued-1.2.1.ckan
- FMRSContinued/FMRSContinued-1.2.2.1.ckan
- FMRSContinued/FMRSContinued-1.2.2.ckan
- FMRSContinued/FMRSContinued-1.2.3.1.ckan
- FMRSContinued/FMRSContinued-1.2.3.8.ckan
- FMRSContinued/FMRSContinued-1.2.3.ckan
- FMRSContinued/FMRSContinued-1.2.4.ckan
- FMRSContinued/FMRSContinued-1.2.5.ckan
- FMRSContinued/FMRSContinued-1.2.6.ckan
- FMRSContinued/FMRSContinued-1.2.7.1.ckan
- FMRSContinued/FMRSContinued-1.2.7.2.ckan
- FMRSContinued/FMRSContinued-1.2.7.3.ckan
- FMRSContinued/FMRSContinued-1.2.7.4.ckan
- FMRSContinued/FMRSContinued-1.2.8.1.ckan
- FMRSContinued/FMRSContinued-1.2.8.ckan
- FMRSContinued/FMRSContinued-1.2.9.1.ckan
- FMRSContinued/FMRSContinued-1.2.9.ckan
Historical component of https://github.com/KSP-CKAN/NetKAN/commit/20ea93204faa1e9c01a272a54048832c1c241ed5, which I accidentally misclicked into a master commit instead of a PR.
Long and elaborate relationship trees with very permissive compatibility settings can pull in both FMRS and FMRSContinued, resulting in a file overwriting error:
```
Error: 383414 [1] ERROR CKAN.CmdLine.ConsoleUser (null) - Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.
If this problem re-occurs, then it maybe a packaging bug.
Please report it at:
https://github.com/KSP-CKAN/NetKAN/issues/new
Please including the following information in your report:
File           : GameData/FMRS/FMRS_MM.cfg
Installing Mod : FMRS v1.1.0.1
Owning Mod     : FMRSContinued
CKAN …
```
> Make FMRSContinued provide and conflict with FMRS

- Scatterer-config/Scatterer-config-3-v0.0723.ckan
- Scatterer-config/Scatterer-config-3-v0.0770.ckan
- Scatterer-config/Scatterer-config-3-v0.0772.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0723.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0770.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0772.ckan
Backport of https://github.com/KSP-CKAN/NetKAN/pull/8722 to Scatterer-sunflare and Scatterer-config releases v0.0723, v0.0770 and v0.0772.
> Revert Scatterer-sunflare and Scatterer-config dependency on Scatterer

- ScrapYard/ScrapYard-2.1.1.0.ckan
See comments in KSP-CKAN/NetKAN#8764, the MagiCore depends was removed in the release before current. Now the metdata will reflect this.
> Remove MagiCore depends from historical ScrapYard

- SerialIO/SerialIO-v0.19.2.ckan
This mod had two changes in rapid succession, a change to the compatibility and then a new release. If not for the new release, we would have had to use `x_netkan_override` to pin the minimum compatibility, but now we can just update the .ckan file directly based on its original compatibility.
> Historical SerialIO min compat

- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.1.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.2.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.3.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.4.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.5.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.1.6.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.2.0.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.2.1.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.2.2.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.3.0.ckan
- MinorPlanetsExpansionRevived/MinorPlanetsExpansionRevived-1.3.1.ckan
Historical component of KSP-CKAN/NetKAN#8860.
Now all versions of MPER conflict with MPE, so the relationship resolver won't try to install old releases to get around the conflict.
___
ckan compat add 1.11
> Conflicts between MinorPlanetsExpansionRevived and MinorPlanetsExpansion

- Scatterer-config/Scatterer-config-3-v0.0824.ckan
- Scatterer-config/Scatterer-config-3-v0.0825.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0824.ckan
- Scatterer-sunflare/Scatterer-sunflare-3-v0.0825.ckan
- Scatterer/Scatterer-3-v0.0824.ckan
- Scatterer/Scatterer-3-v0.0825.ckan
Backport of https://github.com/KSP-CKAN/NetKAN/pull/8862 to releases `v0.0825` and `v0.0824`, which have been deleted from SpaceDock but are still downloadable from our archive.org fallback.
I've confirmed that both versions already had the capitalized directory name.
> Fix install_to capitalization of Scatterer config and sunflare

- CryoEngines/CryoEngines-1-0.4.5.ckan
- CryoEngines/CryoEngines-1-0.4.6.ckan
- CryoEngines/CryoEngines-1-0.5.0.ckan
- CryoEngines/CryoEngines-1-0.5.1.ckan
- CryoEngines/CryoEngines-1-0.5.10.ckan
- CryoEngines/CryoEngines-1-0.5.11.ckan
- CryoEngines/CryoEngines-1-0.5.2.ckan
- CryoEngines/CryoEngines-1-0.5.3.ckan
- CryoEngines/CryoEngines-1-0.5.4.ckan
- CryoEngines/CryoEngines-1-0.5.5.ckan
- CryoEngines/CryoEngines-1-0.5.6.ckan
- CryoEngines/CryoEngines-1-0.5.7.ckan
- CryoEngines/CryoEngines-1-0.5.8.ckan
- CryoEngines/CryoEngines-1-0.5.9.ckan
- CryoEngines/CryoEngines-1-0.6.0.ckan
- CryoEngines/CryoEngines-1-0.6.1.ckan
- CryoEngines/CryoEngines-1-0.6.2.ckan
- CryoEngines/CryoEngines-1-0.6.3.ckan
- CryoEngines/CryoEngines-1-0.6.4.ckan
- CryoEngines/CryoEngines-1-0.6.5.ckan
Up to its 0.4.3 release, `CryoEngines` was under the CC-BY-NC-SA-4.0 license, see the `readme.txt`:
https://spacedock.info/mod/709/Cryogenic%20Engines/download/0.4.3
As of the 0.4.5 release, the art assets were All Rights Reserved, again see the `readme.txt`:
https://spacedock.info/mod/709/Cryogenic%20Engines/download/0.4.5
This was specifically announced on the forum as well:
https://forum.kerbalspaceprogram.com/index.php?/topic/106089-112x-cryogenic-engines-liquid-hydrogen-and-methane-rockets-october-25-2021/page/31/&tab=comments#comment-2931998
This change was reflected in CKAN about 2 years later, in KSP-CKAN/NetKAN#7157 when the mod was moved to a metanetkan, which has had the license field as `restricted` since it was created. The first version with the new license in the CKAN …
> Fix historical CryoEngine licenses

- MalemuteRover/MalemuteRover-0.1.4.0.ckan
- MalemuteRover/MalemuteRover-0.2.0.0.ckan
- MalemuteRover/MalemuteRover-0.2.1.0.ckan
- MalemuteRover/MalemuteRover-0.2.2.0.ckan
- MalemuteRover/MalemuteRover-0.2.3.0.ckan
- MalemuteRover/MalemuteRover-0.2.4.0.ckan
- MalemuteRover/MalemuteRover-0.2.5.0.ckan
- MalemuteRover/MalemuteRover-0.2.6.0.ckan
- MalemuteRover/MalemuteRover-0.2.7.0.ckan
Follow-up of #2522, #2521, #2520, #2512, #2511, #2510, #2509, #2508, #2507
Updating the repo and download links of MalemuteRover
This one had the metnetkan file [updated in 2017](https://github.com/UmbraSpaceIndustries/CKAN/commit/33681b612d6bcb2fa467632f19592bb1ea7949a4#diff-e2207c103227179d0f342e58a3998a93f2a25d4c12e0132322100e5b3a1b4e14) already, so it was only a handful of older releases with pre-move repo links
> Update MalemuteRover links after repo move

- BreakingGround-DLC/BreakingGround-DLC-1.7.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.12.1.ckan
As far as I can tell, KSP 1.12.3 shipped without updating the DLCs, so the existing versions must be compatible with it.
> Update current DLC compat

- FacilityTree/FacilityTree-1-V1.ckan
- FacilityTree/FacilityTree-1-V2.ckan
Historical extension of KSP-CKAN/NetKAN#8929.
https://spacedock.info/mod/2918/FacilityTree#changelog
> Remove CustomBarnKit depends from FacilityTree

- FacilityTree/FacilityTree-1-V2.1.ckan
- KerbalHero/KerbalHero-1-V2.1.ckan
- KerbalWitchery/KerbalWitchery-1-V1.ckan
- OpenTree/OpenTree-1-v2.5.5.ckan
These mods lost some metadata in the process of the author partially removing them by renaming them and replacing them with blank downloads:
https://github.com/KSP-CKAN/CKAN-meta/compare/1682c8ad98...14aae3d
Now that KSP-CKAN/NetKAN#8940 has frozen these mods, these changes are reverted and the new `resources.curse` links are added, so users will still be able to find the original forum thread and see that it has been cleared out, and also find the new homes on Curseforge.
> Restore sunnypunny's forum thread, add curse links

- KerbalImprovedSaveSystem/KerbalImprovedSaveSystem-v2.1.0.ckan
See KSP-CKAN/NetKAN#8979, this mod's netkan had an override for this version that was failing to apply. Now the intended compatibility is set.
> Fix historical KerbalImprovedSaveSystem compat

- HazardTanksTextures/HazardTanksTextures-1.0.ckan
`HazardTanksTextures` contains textures to be used by `ProceduralParts`, but it only `suggests` PP rather than `depends`.
This seems to have been done in KSP-CKAN/NetKAN#5106 to bypass installation errors from Travis. The validation script at that time installed on KSP 1.2.2, but ProceduralParts was only compatible up to 1.2.1 until KSP-CKAN/NetKAN#5448. We don't have the logs from that time, but we can see that the first commit failed to validate, and the second commit moved PP from depends to suggests:
But this doesn't reflect the intended relationship between these modules.
Now `HazardTanksTextures` depends on `ProceduralParts` again.
Fixes KSP-CKAN/NetKAN#8998. (The part of that issue about Ven's Revamp Style Textures is not applicable and already working as intended.)
> Restore HazardTanks depends on ProceduralParts

- AT-Utils/AT-Utils-v1.9.6.ckan
- ConfigurableContainers/ConfigurableContainers-2.6.1.ckan
- ThrottleControlledAvionics/ThrottleControlledAvionics-v3.7.2.ckan
These commits happened because the remote version files were updated to reflect new versions that haven't been created yet:
- da8386e3c9175b8127c109b1220d4c5b73badfa7, see KSP-CKAN/NetKAN#8085 and allista/ConfigurableContainers#40
- a1118defe0a68bf71f1c01f2d8773a0302a10155, see KSP-CKAN/NetKAN#8085 and allista/AT_Utils#24
- c555650a5d910ac1e21f551376aa1e3f5a86a1b8, see KSP-CKAN/NetKAN#8140 and allista/ThrottleControlledAvionics#102
This PR reverts that so the correct compatibility is restored. Merge after the new versions are indexed so the bot doesn't re-apply the bad changes.
> Revert compat of allista's mods

- AstronomersVisualPack/AstronomersVisualPack-3-v4.11.ckan
1. themaster402/AstronomersVisualPack#23 updated AVP's remote version file to reflect the correct compatibility
2. https://github.com/themaster402/AstronomersVisualPack/commit/05059fa817597b150bc479f6e3fa72aa2a3ebac5 changed the `VERSION` property before the referenced version was released, so those changes were lost in e0718307b1a12373d9e951e42e8f82dac6d2948c
3. After the next version is released, merging this PR will fix it
> Revert AVP compat

- RocketSoundEnhancement-Config-Default/RocketSoundEnhancement-Config-Default-0.5.1.ckan
- RocketSoundEnhancement-Config-Default/RocketSoundEnhancement-Config-Default-0.5.2.ckan
- RocketSoundEnhancement-Config-Default/RocketSoundEnhancement-Config-Default-0.5.3.ckan
- RocketSoundEnhancement-Config-Default/RocketSoundEnhancement-Config-Default-0.5.4.ckan
This mod's `name` had a typo in it. Now it's fixed.
"Configs" is removed from the name as well as per author request.
> Fix RocketSoundEnhancement Default Configs name typo

- MechJeb2/MechJeb2-2.14.0.0.ckan
This is the historical part of KSP-CKAN/NetKAN#9059.
An old MechJeb version needs to have its min compat bumped up to 1.12.
> Fix historical MechJeb compat

- MechJeb2/MechJeb2-2.8.3.0.ckan
After #2634 I double checked the overrides for MechJeb, and sure enough the one from https://github.com/KSP-CKAN/NetKAN/commit/74a8335b126a38d133ffe030b0d32840dd121036 was never applied to CKAN-meta because there was already a newer version.
Now 2.8.3.0 is updated.
> Fix more historical MechJeb compat

- PartWizardContinued/PartWizardContinued-1.3.8.3.ckan
Fixes KSP-CKAN/NetKAN#9082. See discussion on that issue for background on why we think this makes sense; to sum up, this release targeted .NET Framework v4.7.2, and the release announcement can be interpreted to mean it was only compatible with KSP 1.12 and up.
> Update PartWizardContinued historical compat

- CraftManager/CraftManager-1.1.5.ckan
Follow-up to https://github.com/KSP-CKAN/NetKAN/pull/9110
I just noticed that the previous release also had no max KSP version set, but is supposed to be 1.4-1.7 only according to release notes.
> Limit CraftManager 1.1.5 compat to 1.4-1.7

- DeepFreeze/DeepFreeze-V0.29.0.ckan
- DeepFreeze/DeepFreeze-V0.30.0.0.ckan
Historical component of KSP-CKAN/NetKAN#9126, author confirmed BackgroundResources is supposed to be a dependency.
> Require BackgroundResources for DeepFreeze

- KerbolsHumbleNeighboringStars/KerbolsHumbleNeighboringStars-1-Beta-1.1.ckan
Backport of https://github.com/KSP-CKAN/NetKAN/pull/9128
> KHNS Beta-1.1 already shipped with a full Scatterer config & sunflare

- MechJeb2/MechJeb2-2.12.3.0.ckan
An old version of MechJeb has a download link that's a 404 now.
I guess @sarbian removed that build?
https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/33/
These seem to be the ones that are left:
https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/
Now the download is switched to the previous build, which was for the same version: 
https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/32/
> Fix historical MechJeb2 download

- Kopernicus/Kopernicus-2-release-1.12.1-132.ckan
- Kopernicus/Kopernicus-2-release-1.8.1-132.ckan
While https://github.com/KSP-CKAN/NetKAN/pull/9202 has been merged after the new releases happened (which the CI run confirmed by showing the new releases), the bot somehow still ended up updating the metadata of the previous releases instead of pulling in the new one.
So let's revert the changes.
> Revert too early Kopernicus metadata updates

- Spectra/Spectra-v1.1.3.ckan
- Spectra/Spectra-v1.1.4.ckan
- Spectra/Spectra-v1.1.5.ckan
- Spectra/Spectra-v1.1.6.ckan
- Spectra/Spectra-v1.1.7.ckan
- Spectra/Spectra-v1.2.1.ckan
- Spectra/Spectra-v1.2.2.ckan
- Spectra/Spectra-v1.2.3.ckan
- Spectra/Spectra-v1.2.4.ckan
- Spectra/Spectra-v1.2.5.ckan
Removing `PlanetShine-config` from `provides:` in all previous versions of Spectra, as this is causing CKAN to recommend installing ancient versions of Spectra to satisfy the config.
> Spectra ckan fixes

- RealRoster/RealRoster-v2.1.frozen
@linuxgurugamer found an ancient mod for KSP 0.25 that no longer has a working download, repository, or homepage. It was announced as abandoned a very long time ago, and apparently even the author doesn't have a copy of the source anymore:
Now it's frozen, and `resources.homepage` is updated to the new forum URL format in case anybody is browsing frozen modules and wants to find the thread.
Fixes KSP-CKAN/NetKAN#9284.
> Freeze RealRoster and update its homepage

- KerbolsHumbleNeighboringStars/KerbolsHumbleNeighboringStars-1-Beta-1.1.ckan
- KerbolsHumbleNeighboringStars/KerbolsHumbleNeighboringStars-1-Beta-1.2.ckan
This is KSP-CKAN/NetKAN#9285 for historical data. ErsteSterne only has one release, so the bot has already updated it. KHNS has two prior releases with the affected `provides` values.
> Add conflicts to KHNS for provides

- KerbalWind/KerbalWind-1-7.1.ckan
- KerbalWind/KerbalWind-1-R10.ckan
- KerbalWind/KerbalWind-1-R11.ckan
- KerbalWind/KerbalWind-1-R12.ckan
- KerbalWind/KerbalWind-1-R13.ckan
- KerbalWind/KerbalWind-1-R8.ckan
- KerbalWind/KerbalWind-1-R9.ckan
KerbalWind has an out of order version:
Noticed while investigating KSP-CKAN/NetKAN#9307.
Now an epoch is added to 7.1 and later.
> Epoch historical KerbalWind versions

- DynamicBatteryStorage/DynamicBatteryStorage-1.0.0.ckan
- KSPRC-Textures/KSPRC-Textures-0.7.ckan
- SASS-RevJ/SASS-RevJ-1.ckan
- SASS-SE/SASS-SE-1.0.ckan
After KSP-CKAN/NetKAN-Infra#273, the download counter will print errors to Discord if it can't parse the mod id from a SpaceDock `download` URL. Such mods will be excluded from the download counts, and SpaceDock would fail to count any downloads originating from CKAN.
There are currently 4 such mods.
The visible download links on SpaceDock are received by the Python code, which updates the download counts for that mod and redirects to the `/content/` location where the ZIP file actually lives, which is then handled by the Apache Traffic Server reverse proxy server for speed and caching. The URLs in question here have skipped that first step and gone directly to the "real" `/content/` link.
Checking the revision history, these URLs seem to have been generated by the bot in mid-late 2017, …
> Fix SpaceDock deep links

- ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-0.ckan
- ProceduralParts-Textures-SCCKSCS/ProceduralParts-Textures-SCCKSCS-1.ckan
@siimav reported on Discord that this mod fails to download and doesn't fallback to archive.org.
The license is CC-BY-NC-ND-3.0 (which is redistributable), and it is archived:
- https://archive.org/details/ProceduralParts-Textures-SCCKSCS-0
- https://archive.org/details/ProceduralParts-Textures-SCCKSCS-1
Dropbox doesn't have the file anymore, but it reports an HTTP status of 200 instead of 404:
https://www.dropbox.com/s/amgpjjd7qfx84q4/blackheart%206-8-15.zip?dl=1
This makes CKAN save the error page to disk and try to add it to the cache, which fails the integrity checks.
Now these mods are updated to use the archive.org link as primary.
> Fix blackheart texture downloads

- WildBlue-PlayMode-USI/WildBlue-PlayMode-USI-v1.0.0.2.ckan
This repo was deleted, see KSP-CKAN/NetKAN#9072.
Now we download it from archive.org by default.
> Fix WBI USI play mode download

- Parallax-StockTextures/Parallax-StockTextures-1.1.0_-_PRE.ckan
- Parallax-StockTextures/Parallax-StockTextures-1.1.1.ckan
- Parallax-StockTextures/Parallax-StockTextures-1.1.1b.ckan
- Parallax-StockTextures/Parallax-StockTextures-1.2.1.ckan
- Parallax-StockTextures/Parallax-StockTextures-1.2.2.ckan
- Parallax-StockTextures/Parallax-StockTextures-1.2.3.ckan
- Parallax-StockTextures/Parallax-StockTextures-1.3.0.ckan
- Parallax-StockTextures/Parallax-StockTextures-1.3.1.ckan
Related to https://github.com/KSP-CKAN/NetKAN/pull/9323 / https://github.com/KSP-CKAN/NetKAN/pull/9321
https://github.com/KSP-CKAN/NetKAN/pull/9323 fixed 2.0.0 of Parallax, and installing 1.3.1 through RP-1 still works, but installing 1.3.1 on its own doesn't because Parallax still tries to pull in 2.0.0 of Parallax-StockTextures, which in turn conflicts with the selected Parallax 1.3.1.
```
The following inconsistencies were found:
* Parallax-StockTextures 2.0.0 conflicts with Parallax 1.3.1
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: …
```
> Couple Parallax-StockTextures releases with the corresponding Parallax release

- BreakingGround-DLC/BreakingGround-DLC-1.7.1.ckan
- MakingHistory-DLC/MakingHistory-DLC-1.12.1.ckan
The version numbers of the DLC were not updated with the latest KSP release, so the compatibility of the current versions is now extended to 1.12.4.
> Update DLC compatibility

- ContractConfigurator/ContractConfigurator-1.28.0.ckan
- ContractConfigurator/ContractConfigurator-1.30.1.ckan
- ContractConfigurator/ContractConfigurator-1.30.2.ckan
- ContractConfigurator/ContractConfigurator-1.30.3.ckan
- ContractConfigurator/ContractConfigurator-1.30.4.ckan
- ContractConfigurator/ContractConfigurator-1.30.5.ckan
There's an old version with much broader compatibility than its successors:
Hmm, I guess I missed a few...
> Fix compat of old ContractConfigurator

- Kopernicus/Kopernicus-2-release-1.12.1-140.ckan
- Kopernicus/Kopernicus-2-release-1.12.1-141.ckan
Release-140 and release-141 both are mistakenly marked as compatible with 1.10.x and 1.11.x when in actuality support was dropped.  This PR fixes that.
> Update Kopernicus CKAN metadata for legacy releases

- HyperDriveMod/HyperDriveMod-2.4.ckan
- HyperDriveMod/HyperDriveMod-2.5.ckan
<https://www.curseforge.com/kerbal/ksp-mods/simplehyperdrive>
This is the historical counterpart of KSP-CKAN/NetKAN#9575.
> Mark HyperDriveMod as version independent

- MK12PodIVAReplacementbyASET/MK12PodIVAReplacementbyASET-1-2.0.0.ckan
- Mk1CockpitIVAReplbyASET/Mk1CockpitIVAReplbyASET-2.0.0.ckan
- Mk1LanderCanIVAReplbyASET/Mk1LanderCanIVAReplbyASET-2.0.0.ckan
KSP-CKAN/NetKAN#9560 switched the ASET IVA mods to a new fork, and in the process the install was changed from finding `ASET` to finding `ASET_StockRpl_IVAs`. This was wrong, and so far I have not been able to determine the cause of the error; it may have been a side effect of fiddling with `include_only` and figuring out how it works.
Now it's fixed.
Noticed while working on KSP-CKAN/NetKAN#9614.
> Fix historical ASET Consolidated installs

- Parallax-StockScatterTextures/Parallax-StockScatterTextures-2.0.0.ckan
This is the historical counterpart of KSP-CKAN/NetKAN#9810.
Only one older module has an affected dependency.
> Put more specific Parallax texture dependencies first

- ArtemisConstructionKit/ArtemisConstructionKit-1.0.0.ckan
- ArtemisConstructionKit/ArtemisConstructionKit-1.1.0.ckan
- ArtemisConstructionKit/ArtemisConstructionKit-1.2.0.ckan
- ArtemisConstructionKit/ArtemisConstructionKit-1.3.0.ckan
- ArtemisConstructionKit/ArtemisConstructionKit-1.4.0.ckan
Updated the dependencies and recommendations for the ArtimisConstructionKit mod by Benjee_10 for all the historical versions that are downloadable through CKAN. 
- https://spacedock.info/mod/3098/Artemis%20Construction%20Kit#changelog
- https://github.com/benjee10/Benjee10_Orion/commits/main/ReadMe.txt
- https://forum.kerbalspaceprogram.com/topic/209546-112x-artemis-construction-kit-stockalike-orion-sls-v140-lockheed-lander/
___
ckan compat add 1.11
> Update ACK Dependencies & Recommendations

- KeminiResearchProgram/KeminiResearchProgram-0.7b2.ckan
- KerbalEnvironmentalEffectsStudy/KerbalEnvironmentalEffectsStudy-0.7b2.ckan
- KerbalLifeScience/KerbalLifeScience-0.7b2.ckan
- NehemiahInc-Complete/NehemiahInc-Complete-0.7b2.ckan
- NehemiahMultiPurposeParts/NehemiahMultiPurposeParts-1-0.7b2.ckan
- NehemiahScienceCommon/NehemiahScienceCommon-1-0.7b2.ckan
- OrbitalMaterialScience/OrbitalMaterialScience-0.7b2.ckan
KSP-CKAN/NetKAN#7100 attempted to mark several old mods as replaced by a newer one. This was not successful because those netkans were already frozen, and if they hadn't been, there were syntax errors and the property name was wrong (see KSP-CKAN/NetKAN#10109 and KSP-CKAN/NetKAN#10110).
Now the old modules have `replaced_by` set as originally intended.
> Mark old Nehemiah mods as `replaced_by` newer one

- EBRCPartspack/EBRCPartspack-Wise_Penguin.ckan
- EasyLaunchpads/EasyLaunchpads-1.0.ckan
- FairingWithMass/FairingWithMass-1.3.1.ckan
- GeometricShapeAeroTests/GeometricShapeAeroTests-0.2f.ckan
- JettisonFuel/JettisonFuel-1.0.1.ckan
- JettisonFuel/JettisonFuel-1.ckan
- KerbalFuels/KerbalFuels-0.1.ckan
- MeatlessIndustries/MeatlessIndustries-1.1.1.1.1.1.ckan
- MeatlessIndustries/MeatlessIndustries-1.1.1.ckan
- MinkTechnologies/MinkTechnologies-1.02.ckan
- StockHeatManagementforKSPI/StockHeatManagementforKSPI-1.0.ckan
- StockHeatManagementforKSPI/StockHeatManagementforKSPI-1.1.ckan
- TACLSMining/TACLSMining-1-1.ckan
- TACLSMining/TACLSMining-1.ckan
- TrizzleAeroSpaceCompany/TrizzleAeroSpaceCompany-0.3.ckan
A few old frozen mods still have `resources.homepage` pointing to KerbalStuff, which has been squatted by a malicious site for several years now.
Now these links are removed.
> Purge lingering KerbalStuff homepage links

- StarshipExpansionProject/StarshipExpansionProject-v.3.0.0-b1.ckan
- StarshipExpansionProjectIVA/StarshipExpansionProjectIVA-v.2.0.1.ckan
- StarshipExpansionProjectIVA/StarshipExpansionProjectIVA-v.2.0.2.ckan
- StarshipExpansionProjectIVA/StarshipExpansionProjectIVA-v.2.0.3.1.ckan
- StarshipExpansionProjectIVA/StarshipExpansionProjectIVA-v.2.0.3.ckan
- StarshipExpansionProjectIVA/StarshipExpansionProjectIVA-v.2.1.0.ckan
- StarshipExpansionProjectIVA/StarshipExpansionProjectIVA-v.2.2.0.ckan
- StarshipExpansionProjectIVA/StarshipExpansionProjectIVA-v.3.0.0-b1.ckan
- StarshipExpansionProjectIVA/StarshipExpansionProjectIVA-v2.0.0.ckan
While making changes to move SEP’s relationships to internal .ckan files I noticed that the IVA section of the mod had always been missing its dependency on B9PartSwitch, even though it depends on SEP, which itself depends on B9PS this seemed best to fix anyways.
Secondly there were a few small mistakes in the relationships for the first beta release of version 3.0.0 for SEP itself so these have also been corrected.
this should ideally only be merged after both https://github.com/KSP-CKAN/NetKAN/pull/10325 has been merged and SEP v3.0.0-b2 has been indexed on ckan.
Thanks in advance again!
> Update StarshipExpansionProject MetaData

- KopernicusExpansionContinueder/KopernicusExpansionContinueder-Beta9.1.ckan
All of this mod's releases are labeled "Beta" in their version strings on SpaceDock. After KSP-CKAN/CKAN#4260, the latest release was marked as a prerelease, which has caused the previous release to be treated as the latest for users with the current stable CKAN client. But they're both betas, so they shouldn't be treated differently.
Now the historical beta release has a `release_status` of `testing`, the same as the latest release.
> Mark historical KopernicusExpansionContinueder beta version as prerelease

- KaribouExpeditionRover/KaribouExpeditionRover-0.0.4.ckan
- KaribouExpeditionRover/KaribouExpeditionRover-0.0.5.ckan
- KaribouExpeditionRover/KaribouExpeditionRover-0.1.0.1.ckan
- KaribouExpeditionRover/KaribouExpeditionRover-0.1.0.ckan
- KaribouExpeditionRover/KaribouExpeditionRover-0.1.1.0.ckan
Many years ago (circa KSP 1.0), there was a mod called Karibou Expedition Rover. It was merged into UKS and sunsetted:
<https://forum.kerbalspaceprogram.com/topic/119907-12-karibou-expedition-rover-030/?do=findComment&comment=2906423>
In response, CKAN deleted the netkan (see KSP-CKAN/NetKAN#5362) and updated KaribouExpeditionRover's abstract to note the merger (see 049eb32f5111e902840a25f5643344a55f808c80):
If you nonetheless attempt to install the old mod and the mod into which it was merged at the same time, you get a file conflict.
Now KaribouExpeditionRover has a `conflict` with UKS so CKAN won't even get to the install stage.
Fixes #10432.
> Add conflict between UKS and KaribouExpeditionRover

- SmartTank/SmartTank-v0.1.0.ckan
- SmartTank/SmartTank-v0.1.1.ckan
- SmartTank/SmartTank-v0.1.2.ckan
- SmartTank/SmartTank-v0.2.0.ckan
- SmartTank/SmartTank-v0.2.1.ckan
- SmartTank/SmartTank-v0.3.0.ckan
- SmartTank/SmartTank-v0.4.0.ckan
- SmartTank/SmartTank-v0.5.0.ckan
After KSP-CKAN/CKAN#4348, SmartTank's `install_size` needs to be updated, but KSP-CKAN/NetKAN#10490 couldn't do it without also setting `release_status: development`. So now the .ckans are updated directly.
> Update install_size for SmartTank

- Parallax-StockScatterTextures/Parallax-StockScatterTextures-2.0.8.ckan
Apparently the latest download of this mod was replaced after release (and archiving of the repo) and freezing of the netkan in KSP-CKAN/NetKAN#10459, presumably related to Gameslinx/Tessellation#170 (fixed in https://github.com/Gameslinx/Tessellation/compare/bc27cb8ec5dd33b335b3eb42e11fa75046dad180...9abc858630088e4110a3246c4747ca6c703b3670), leaving the hashes out of sync.
Now it's updated manually.
Fixes KSP-CKAN/NetKAN#10508.
> Update Parallax-StockScatterTextures hashes

- KopernicusTech/KopernicusTech-0.13.ckan
This mod has been removed from Dropbox:
- <https://www.dropbox.com/s/7b999gme8p7cgfr/KopernicusTech_v0.13.zip?dl=1>
But it's still on archive.org:
- <https://archive.org/details/KopernicusTech-0.13>
I need this to try to reproduce KSP-CKAN/CKAN#930.
> Download KopernicusTech from archive.org

- .github/pull_request_template.md
Inspired by #3355, users starting a new CKAN-meta PR will now be told not to do so and directed to the NetKAN repo where new mods belong.
I looked for ways to make a separate banner but did not find any. The `.yml`-style templates appear to only be supported for issues, not pull requests.
> PR template for CKAN-meta directing users to NetKAN repo

- HeapPadder/HeapPadder-0.0.1.5.ckan
- HeapPadder/HeapPadder-0.0.2.1.ckan
- HeapPadder/HeapPadder-0.0.2.2.ckan
- HeapPadder/HeapPadder-0.0.2.3.ckan
- HeapPadder/HeapPadder-0.0.2.4.ckan
- HeapPadder/HeapPadder-0.0.2.5.ckan
- HeapPadder/HeapPadder-0.0.2.ckan
See linuxgurugamer/HeapPadder#3, HeapPadder is only supposed to be used on KSP 1.7 and earlier.
@linuxgurugamer tried to address this with a new release, but unfortunately the version file says `_MIN` where it should have said `_MAX`, so the compatibility ended up basically the opposite of what it should be.
Now all HeapPadder releases are marked compatible with 1.5–1.7. I froze the netkan a few minutes ago, so the bot shouldn't re-break it with the bad upstream data.
> Fix HeapPadder compatibility
